In [1]:
 print("Hello World")

Hello World

## 1.1 Option 1

In [2]:
import pandas as pd
import numpy as np

In [3]:
#creating an array
data = np.array([[1,8],[7,3],[8,9]])

In [4]:
# Creating a dataframe
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'], columns=['col1','col2'] )

In [5]:
#Showing DataFrame
df

      col1  col2
row1     1     8
row2     7     3
row3     8     9

## 1.2 Option 2

In [6]:
# Creating an array with list shape
data = [[1,8],[7,3],[8,9]]

In [7]:
# Creating a dataframe
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'], columns=['col1','col2'] )

In [8]:
# Showing the dataframe
df

      col1  col2
row1     1     8
row2     7     3
row3     8     9

# 2 Creating a DataFrame from a dictionary

In [9]:
# lists used for this example
states = ['California', 'Texas', 'Florida', 'New York']
population = [39613493, 29730311, 21944577, 19299981]

In [10]:
# Storing lists within a dictionary
dict_states = {'States': states, 'Population':population}

In [11]:
# Creating the dataframe
df_population = pd.DataFrame(dict_states)

In [12]:
# Showing the dataframe
df_population

       States  Population
0  California    39613493
1       Texas    29730311
2     Florida    21944577
3    New York    19299981

# 3 Creating a DataFrame from a CSV file

# Reading the CSV file

In [13]:
df_exams = pd.read_csv('D:/Projects and Work/python/StudentsPerformance.csv')

In [14]:
# Show first 5 rows in a dataframe
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [15]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# 2. Displaying a Dataframe

In [16]:
import pandas as pd

In [17]:
# reading the csv file
df_exams = pd.read_csv('D:/Projects and Work/python/StudentsPerformance.csv')

In [18]:
# summery of dataframe
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [19]:
# show first 5 rows in the dataframe
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [20]:
# show last 5 rows in a dataframe
df_exams.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [21]:
# show last n rows in a datafram
df_exams.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [22]:
# getting access to the shape attribute
df_exams.shape

(1000, 8)

In [23]:
# display n rows 
pd.set_option('display.max_rows', 1000)
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
12,female,group B,high school,standard,none,65,81,73
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
15,female,group C,some high school,standard,none,69,75,78
16,male,group C,high school,standard,none,88,89,86
17,female,group B,some high school,free/reduced,none,18,32,28
18,male,group C,master's degree,free/reduced,completed,46,42,46
19,female,group C,associate's degree,free/reduced,none,54,58,61
20,male,group D,high school,standard,none,66,69,63
21,female,group B,some college,free/reduced,completed,65,75,70
22,male,group D,some college,standard,none,44,54,53
23,female,group C,some high school,standard,none,69,73,73
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80
25,male,group A,master's degree,free/reduced,none,73,74,72
26,male,group B,some college,standard,none,69,54,55
27,female,group C,bachelor's degree,standard,none,67,69,75
28,male,group C,high school,standard,none,70,70,65
29,female,group D,master's degree,standard,none,62,70,75
30,female,group D,some college,standard,none,69,74,74
31,female,group B,some college,standard,none,63,65,61
32,female,group E,master's degree,free/reduced,none,56,72,65
33,male,group D,some college,standard,none,40,42,38
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79
36,female,group D,associate's degree,standard,none,74,81,83
37,female,group D,some high school,free/reduced,none,50,64,59
38,female,group D,associate's degree,free/reduced,completed,75,90,88
39,male,group B,associate's degree,free/reduced,none,57,56,57
40,male,group C,associate's degree,free/reduced,none,55,61,54
41,female,group C,associate's degree,standard,none,58,73,68
42,female,group B,associate's degree,standard,none,53,58,65
43,male,group B,some college,free/reduced,completed,59,65,66
44,female,group E,associate's degree,free/reduced,none,50,56,54
45,male,group B,associate's degree,standard,none,65,54,57
46,female,group A,associate's degree,standard,completed,55,65,62
47,female,group C,high school,standard,none,66,71,76
48,female,group D,associate's degree,free/reduced,completed,57,74,76
49,male,group C,high school,standard,completed,82,84,82
50,male,group E,some college,standard,none,53,55,48
51,male,group E,associate's degree,free/reduced,completed,77,69,68
52,male,group C,some college,standard,none,53,44,42
53,male,group D,high school,standard,none,88,78,75
54,female,group C,some high school,free/reduced,completed,71,84,87
55,female,group C,high school,free/reduced,none,33,41,43
56,female,group E,associate's degree,standard,completed,82,85,86
57,male,group D,associate's degree,standard,none,52,55,49
58,male,group D,some college,standard,completed,58,59,58
59,female,group C,some high school,free/reduced,none,0,17,10
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72
61,male,group A,some high school,free/reduced,none,39,39,34
62,male,group A,associate's degree,free/reduced,none,62,61,55
63,female,group C,associate's degree,standard,none,69,80,71
64,female,group D,some high school,standard,none,59,58,59
65,male,group B,some high school,standard,none,67,64,61
66,male,group D,some high school,free/reduced,none,45,37,37
67,female,group C,some college,standard,none,60,72,74
68,male,group B,associate's degree,free/reduced,none,61,58,56
69,female,group C,associate's degree,standard,none,39,64,57
70,female,group D,some college,free/reduced,completed,58,63,73
71,male,group D,some college,standard,completed,63,55,63
72,female,group A,associate's degree,free/reduced,none,41,51,48
73,male,group C,some high school,free/reduced,none,61,57,56
74,male,group C,some high school,standard,none,49,49,41
75,male,group B,associate's degree,free/reduced,none,44,41,38
76,male,group E,some high school,standard,none,30,26,22
77,male,group A,bachelor's degree,standard,completed,80,78,81
78,female,group D,some high school,standard,completed,61,74,72
79,female,group E,master's degree,standard,none,62,68,68
80,female,group B,associate's degree,standard,none,47,49,50
81,male,group B,high school,free/reduced,none,49,45,45
82,male,group A,some college,free/reduced,completed,50,47,54
83,male,group E,associate's degree,standard,none,72,64,63
84,male,group D,high school,free/reduced,none,42,39,34
85,female,group C,some college,standard,none,73,80,82
86,female,group C,some college,free/reduced,none,76,83,88
87,female,group D,associate's degree,standard,none,71,71,74
88,female,group A,some college,standard,none,58,70,67
89,female,group D,some high school,standard,none,73,86,82
90,female,group C,bachelor's degree,standard,none,65,72,74
91,male,group C,high school,free/reduced,none,27,34,36
92,male,group C,high school,standard,none,71,79,71
93,male,group C,associate's degree,free/reduced,completed,43,45,50
94,female,group B,some college,standard,none,79,86,92
95,male,group C,associate's degree,free/reduced,completed,78,81,82
96,male,group B,some high school,standard,completed,65,66,62
97,female,group E,some college,standard,completed,63,72,70
98,female,group D,some college,free/reduced,none,58,67,62
99,female,group D,bachelor's degree,standard,none,65,67,62
100,male,group B,some college,standard,none,79,67,67
101,male,group D,bachelor's degree,standard,completed,68,74,74
102,female,group D,associate's degree,standard,none,85,91,89
103,male,group B,high school,standard,completed,60,44,47
104,male,group C,some college,standard,completed,98,86,90
105,female,group C,some college,standard,none,58,67,72
106,female,group D,master's degree,standard,none,87,100,100
107,male,group E,associate's degree,standard,completed,66,63,64
108,female,group B,associate's degree,free/reduced,none,52,76,70
109,female,group B,some high school,standard,none,70,64,72
110,female,group D,associate's degree,free/reduced,completed,77,89,98
111,male,group C,high school,standard,none,62,55,49
112,male,group A,associate's degree,standard,none,54,53,47
113,female,group D,some college,standard,none,51,58,54
114,female,group E,bachelor's degree,standard,completed,99,100,100
115,male,group C,high school,standard,none,84,77,74
116,female,group B,bachelor's degree,free/reduced,none,75,85,82
117,female,group D,bachelor's degree,standard,none,78,82,79
118,female,group D,some high school,standard,none,51,63,61
119,female,group C,some college,standard,none,55,69,65
120,female,group C,bachelor's degree,standard,completed,79,92,89
121,male,group B,associate's degree,standard,completed,91,89,92
122,female,group C,some college,standard,completed,88,93,93
123,male,group D,high school,free/reduced,none,63,57,56
124,male,group E,some college,standard,none,83,80,73
125,female,group B,high school,standard,none,87,95,86
126,male,group B,some high school,standard,none,72,68,67
127,male,group D,some college,standard,completed,65,77,74
128,male,group D,master's degree,standard,none,82,82,74
129,female,group A,bachelor's degree,standard,none,51,49,51
130,male,group D,master's degree,standard,none,89,84,82
131,male,group C,some high school,free/reduced,completed,53,37,40
132,male,group E,some college,free/reduced,completed,87,74,70
133,female,group C,some college,standard,completed,75,81,84
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75
135,male,group C,bachelor's degree,standard,none,58,55,48
136,male,group B,some high school,standard,completed,51,54,41
137,male,group E,high school,standard,none,70,55,56
138,female,group C,associate's degree,standard,none,59,66,67
139,male,group D,some college,standard,completed,71,61,69
140,female,group D,some high school,standard,none,76,72,71
141,female,group C,some college,free/reduced,none,59,62,64
142,female,group E,some college,free/reduced,completed,42,55,54
143,male,group A,high school,standard,none,57,43,47
144,male,group D,some college,standard,none,88,73,78
145,female,group C,some college,free/reduced,none,22,39,33
146,male,group B,some high school,standard,none,88,84,75
147,male,group C,associate's degree,free/reduced,none,73,68,66
148,female,group D,bachelor's degree,standard,completed,68,75,81
149,male,group E,associate's degree,free/reduced,completed,100,100,93
150,male,group A,some high school,standard,completed,62,67,69
151,male,group A,bachelor's degree,standard,none,77,67,68
152,female,group B,associate's degree,standard,completed,59,70,66
153,male,group D,bachelor's degree,standard,none,54,49,47
154,male,group D,some high school,standard,none,62,67,61
155,female,group C,some college,standard,completed,70,89,88
156,female,group E,high school,free/reduced,completed,66,74,78
157,male,group B,some college,free/reduced,none,60,60,60
158,female,group B,associate's degree,standard,completed,61,86,87
159,male,group D,associate's degree,free/reduced,none,66,62,64
160,male,group B,associate's degree,free/reduced,completed,82,78,74
161,female,group E,some college,free/reduced,completed,75,88,85
162,male,group B,master's degree,free/reduced,none,49,53,52
163,male,group C,high school,standard,none,52,53,49
164,female,group E,master's degree,standard,none,81,92,91
165,female,group C,bachelor's degree,standard,completed,96,100,100
166,male,group C,high school,free/reduced,completed,53,51,51
167,female,group B,master's degree,free/reduced,completed,58,76,78
168,female,group B,high school,standard,completed,68,83,78
169,female,group C,some college,free/reduced,completed,67,75,70
170,male,group A,high school,standard,completed,72,73,74
171,male,group E,some high school,standard,none,94,88,78
172,female,group D,some college,standard,none,79,86,81
173,female,group C,associate's degree,standard,none,63,67,70
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54
175,female,group C,master's degree,standard,completed,81,91,87
176,female,group B,high school,free/reduced,completed,46,54,58
177,female,group C,associate's degree,standard,completed,71,77,77
178,female,group B,master's degree,free/reduced,completed,52,70,62
179,female,group D,some high school,standard,completed,97,100,100
180,male,group C,master's degree,free/reduced,completed,62,68,75
181,female,group C,some college,free/reduced,none,46,64,66
182,female,group E,high school,standard,none,50,50,47
183,female,group D,associate's degree,standard,none,65,69,70
184,male,group C,some high school,free/reduced,completed,45,52,49
185,male,group C,associate's degree,free/reduced,completed,65,67,65
186,male,group E,high school,standard,none,80,76,65
187,male,group D,some high school,standard,completed,62,66,68
188,male,group B,some high school,free/reduced,none,48,52,45
189,female,group C,bachelor's degree,standard,none,77,88,87
190,female,group E,associate's degree,standard,none,66,65,69
191,male,group D,some college,standard,completed,76,83,79
192,female,group B,some high school,standard,none,62,64,66
193,male,group D,some college,standard,completed,77,62,62
194,female,group C,master's degree,standard,completed,69,84,85
195,male,group D,associate's degree,standard,none,61,55,52
196,male,group C,some high school,free/reduced,completed,59,69,65
197,male,group E,high school,free/reduced,none,55,56,51
198,female,group B,some college,free/reduced,none,45,53,55
199,female,group B,bachelor's degree,free/reduced,none,78,79,76
200,female,group C,associate's degree,standard,completed,67,84,86
201,female,group D,some college,free/reduced,none,65,81,77
202,male,group C,associate's degree,standard,none,69,77,69
203,female,group B,associate's degree,standard,none,57,69,68
204,male,group C,some college,standard,none,59,41,42
205,male,group D,some high school,standard,completed,74,71,78
206,male,group E,bachelor's degree,standard,none,82,62,62
207,male,group E,high school,standard,completed,81,80,76
208,female,group B,some college,free/reduced,none,74,81,76
209,female,group B,some college,free/reduced,none,58,61,66
210,male,group D,some high school,free/reduced,completed,80,79,79
211,male,group C,some college,free/reduced,none,35,28,27
212,female,group C,high school,free/reduced,none,42,62,60
213,male,group C,associate's degree,free/reduced,completed,60,51,56
214,male,group E,high school,standard,completed,87,91,81
215,male,group B,some high school,standard,completed,84,83,75
216,female,group E,associate's degree,free/reduced,completed,83,86,88
217,female,group C,high school,free/reduced,none,34,42,39
218,male,group B,high school,free/reduced,none,66,77,70
219,male,group B,some high school,standard,completed,61,56,56
220,female,group D,high school,standard,completed,56,68,74
221,male,group B,associate's degree,standard,none,87,85,73
222,female,group C,some high school,free/reduced,none,55,65,62
223,male,group D,some high school,standard,none,86,80,75
224,female,group B,associate's degree,standard,completed,52,66,73
225,female,group E,master's degree,free/reduced,none,45,56,54
226,female,group C,some college,standard,none,72,72,71
227,male,group D,high school,standard,none,57,50,54
228,male,group A,some high school,free/reduced,none,68,72,64
229,female,group C,some college,standard,completed,88,95,94
230,male,group D,some college,standard,none,76,64,66
231,male,group C,associate's degree,standard,none,46,43,42
232,female,group B,bachelor's degree,standard,none,67,86,83
233,male,group E,some high school,standard,none,92,87,78
234,male,group C,bachelor's degree,standard,completed,83,82,84
235,male,group D,associate's degree,standard,none,80,75,77
236,male,group D,bachelor's degree,free/reduced,none,63,66,67
237,female,group D,some high school,standard,completed,64,60,74
238,male,group B,some college,standard,none,54,52,51
239,male,group C,associate's degree,standard,none,84,80,80
240,male,group D,high school,free/reduced,completed,73,68,66
241,female,group E,bachelor's degree,standard,none,80,83,83
242,female,group D,high school,standard,none,56,52,55
243,male,group E,some college,standard,none,59,51,43
244,male,group D,some high school,standard,none,75,74,69
245,male,group C,associate's degree,standard,none,85,76,71
246,male,group E,associate's degree,standard,none,89,76,74
247,female,group B,high school,standard,completed,58,70,68
248,female,group B,high school,standard,none,65,64,62
249,male,group C,high school,standard,none,68,60,53
250,male,group A,some high school,standard,completed,47,49,49
251,female,group D,some college,free/reduced,none,71,83,83
252,female,group B,some high school,standard,completed,60,70,70
253,male,group D,master's degree,standard,none,80,80,72
254,male,group D,high school,standard,none,54,52,52
255,female,group E,some college,standard,none,62,73,70
256,female,group C,associate's degree,free/reduced,none,64,73,68
257,male,group C,associate's degree,standard,completed,78,77,77
258,female,group B,some college,standard,none,70,75,78
259,female,group C,master's degree,free/reduced,completed,65,81,81
260,female,group C,some high school,free/reduced,completed,64,79,77
261,male,group C,some college,standard,completed,79,79,78
262,female,group C,some high school,free/reduced,none,44,50,51
263,female,group E,high school,standard,none,99,93,90
264,male,group D,high school,standard,none,76,73,68
265,male,group D,some high school,free/reduced,none,59,42,41
266,female,group C,bachelor's degree,standard,none,63,75,81
267,female,group D,high school,standard,none,69,72,77
268,female,group D,associate's degree,standard,completed,88,92,95
269,female,group E,some college,free/reduced,none,71,76,70
270,male,group C,bachelor's degree,standard,none,69,63,61
271,male,group C,some college,standard,none,58,49,42
272,female,group D,associate's degree,free/reduced,none,47,53,58
273,female,group D,some college,standard,none,65,70,71
274,male,group B,some college,standard,completed,88,85,76
275,male,group C,bachelor's degree,standard,none,83,78,73
276,female,group C,some high school,standard,completed,85,92,93
277,female,group E,high school,standard,completed,59,63,75
278,female,group C,some high school,free/reduced,none,65,86,80
279,male,group B,bachelor's degree,free/reduced,none,73,56,57
280,male,group D,high school,standard,none,53,52,42
281,male,group D,high school,standard,none,45,48,46
282,female,group D,bachelor's degree,free/reduced,none,73,79,84
283,female,group D,some college,free/reduced,completed,70,78,78
284,female,group B,some high school,standard,none,37,46,46
285,male,group B,associate's degree,standard,completed,81,82,82
286,male,group E,associate's degree,standard,completed,97,82,88
287,female,group B,some high school,standard,none,67,89,82
288,male,group B,bachelor's degree,free/reduced,none,88,75,76
289,male,group E,some high school,standard,completed,77,76,77
290,male,group C,associate's degree,standard,none,76,70,68
291,male,group D,some high school,standard,none,86,73,70
292,male,group C,some high school,standard,completed,63,60,57
293,female,group E,bachelor's degree,standard,none,65,73,75
294,male,group D,high school,free/reduced,completed,78,77,80
295,male,group B,associate's degree,free/reduced,none,67,62,60
296,male,group A,some high school,standard,completed,46,41,43
297,male,group E,associate's degree,standard,completed,71,74,68
298,male,group C,high school,free/reduced,completed,40,46,50
299,male,group D,associate's degree,free/reduced,none,90,87,75
300,male,group A,some college,free/reduced,completed,81,78,81
301,male,group D,some high school,free/reduced,none,56,54,52
302,female,group C,associate's degree,standard,completed,67,84,81
303,male,group B,associate's degree,standard,none,80,76,64
304,female,group C,associate's degree,standard,completed,74,75,83
305,male,group A,some college,standard,none,69,67,69
306,male,group E,some college,standard,completed,99,87,81
307,male,group C,some high school,standard,none,51,52,44
308,female,group B,associate's degree,free/reduced,none,53,71,67
309,female,group D,high school,free/reduced,none,49,57,52
310,female,group B,associate's degree,standard,none,73,76,80
311,male,group B,bachelor's degree,standard,none,66,60,57
312,male,group D,bachelor's degree,standard,completed,67,61,68
313,female,group C,associate's degree,free/reduced,completed,68,67,69
314,female,group C,bachelor's degree,standard,completed,59,64,75
315,male,group C,high school,standard,none,71,66,65
316,female,group D,master's degree,standard,completed,77,82,91
317,male,group C,associate's degree,standard,none,83,72,78
318,male,group B,bachelor's degree,standard,none,63,71,69
319,female,group D,associate's degree,free/reduced,none,56,65,63
320,female,group C,high school,free/reduced,completed,67,79,84
321,female,group E,high school,standard,none,75,86,79
322,female,group C,some college,standard,none,71,81,80
323,female,group C,some high school,free/reduced,none,43,53,53
324,female,group C,high school,free/reduced,none,41,46,43
325,female,group C,some college,standard,none,82,90,94
326,male,group C,some college,standard,none,61,61,62
327,male,group A,some college,free/reduced,none,28,23,19
328,male,group C,associate's degree,standard,completed,82,75,77
329,female,group B,some high school,standard,none,41,55,51
330,male,group C,high school,standard,none,71,60,61
331,male,group C,associate's degree,standard,none,47,37,35
332,male,group E,associate's degree,standard,completed,62,56,53

# 1 Attributes

In [24]:
# getting access to the shape attribute
df_exams.shape

(1000, 8)

In [25]:
# getting access to the index attribute
df_exams.index

RangeIndex(start=0, stop=1000, step=1)

In [26]:
# getting access to the column attribute
df_exams.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [27]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
12,female,group B,high school,standard,none,65,81,73
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
15,female,group C,some high school,standard,none,69,75,78
16,male,group C,high school,standard,none,88,89,86
17,female,group B,some high school,free/reduced,none,18,32,28
18,male,group C,master's degree,free/reduced,completed,46,42,46
19,female,group C,associate's degree,free/reduced,none,54,58,61
20,male,group D,high school,standard,none,66,69,63
21,female,group B,some college,free/reduced,completed,65,75,70
22,male,group D,some college,standard,none,44,54,53
23,female,group C,some high school,standard,none,69,73,73
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80
25,male,group A,master's degree,free/reduced,none,73,74,72
26,male,group B,some college,standard,none,69,54,55
27,female,group C,bachelor's degree,standard,none,67,69,75
28,male,group C,high school,standard,none,70,70,65
29,female,group D,master's degree,standard,none,62,70,75
30,female,group D,some college,standard,none,69,74,74
31,female,group B,some college,standard,none,63,65,61
32,female,group E,master's degree,free/reduced,none,56,72,65
33,male,group D,some college,standard,none,40,42,38
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79
36,female,group D,associate's degree,standard,none,74,81,83
37,female,group D,some high school,free/reduced,none,50,64,59
38,female,group D,associate's degree,free/reduced,completed,75,90,88
39,male,group B,associate's degree,free/reduced,none,57,56,57
40,male,group C,associate's degree,free/reduced,none,55,61,54
41,female,group C,associate's degree,standard,none,58,73,68
42,female,group B,associate's degree,standard,none,53,58,65
43,male,group B,some college,free/reduced,completed,59,65,66
44,female,group E,associate's degree,free/reduced,none,50,56,54
45,male,group B,associate's degree,standard,none,65,54,57
46,female,group A,associate's degree,standard,completed,55,65,62
47,female,group C,high school,standard,none,66,71,76
48,female,group D,associate's degree,free/reduced,completed,57,74,76
49,male,group C,high school,standard,completed,82,84,82
50,male,group E,some college,standard,none,53,55,48
51,male,group E,associate's degree,free/reduced,completed,77,69,68
52,male,group C,some college,standard,none,53,44,42
53,male,group D,high school,standard,none,88,78,75
54,female,group C,some high school,free/reduced,completed,71,84,87
55,female,group C,high school,free/reduced,none,33,41,43
56,female,group E,associate's degree,standard,completed,82,85,86
57,male,group D,associate's degree,standard,none,52,55,49
58,male,group D,some college,standard,completed,58,59,58
59,female,group C,some high school,free/reduced,none,0,17,10
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72
61,male,group A,some high school,free/reduced,none,39,39,34
62,male,group A,associate's degree,free/reduced,none,62,61,55
63,female,group C,associate's degree,standard,none,69,80,71
64,female,group D,some high school,standard,none,59,58,59
65,male,group B,some high school,standard,none,67,64,61
66,male,group D,some high school,free/reduced,none,45,37,37
67,female,group C,some college,standard,none,60,72,74
68,male,group B,associate's degree,free/reduced,none,61,58,56
69,female,group C,associate's degree,standard,none,39,64,57
70,female,group D,some college,free/reduced,completed,58,63,73
71,male,group D,some college,standard,completed,63,55,63
72,female,group A,associate's degree,free/reduced,none,41,51,48
73,male,group C,some high school,free/reduced,none,61,57,56
74,male,group C,some high school,standard,none,49,49,41
75,male,group B,associate's degree,free/reduced,none,44,41,38
76,male,group E,some high school,standard,none,30,26,22
77,male,group A,bachelor's degree,standard,completed,80,78,81
78,female,group D,some high school,standard,completed,61,74,72
79,female,group E,master's degree,standard,none,62,68,68
80,female,group B,associate's degree,standard,none,47,49,50
81,male,group B,high school,free/reduced,none,49,45,45
82,male,group A,some college,free/reduced,completed,50,47,54
83,male,group E,associate's degree,standard,none,72,64,63
84,male,group D,high school,free/reduced,none,42,39,34
85,female,group C,some college,standard,none,73,80,82
86,female,group C,some college,free/reduced,none,76,83,88
87,female,group D,associate's degree,standard,none,71,71,74
88,female,group A,some college,standard,none,58,70,67
89,female,group D,some high school,standard,none,73,86,82
90,female,group C,bachelor's degree,standard,none,65,72,74
91,male,group C,high school,free/reduced,none,27,34,36
92,male,group C,high school,standard,none,71,79,71
93,male,group C,associate's degree,free/reduced,completed,43,45,50
94,female,group B,some college,standard,none,79,86,92
95,male,group C,associate's degree,free/reduced,completed,78,81,82
96,male,group B,some high school,standard,completed,65,66,62
97,female,group E,some college,standard,completed,63,72,70
98,female,group D,some college,free/reduced,none,58,67,62
99,female,group D,bachelor's degree,standard,none,65,67,62
100,male,group B,some college,standard,none,79,67,67
101,male,group D,bachelor's degree,standard,completed,68,74,74
102,female,group D,associate's degree,standard,none,85,91,89
103,male,group B,high school,standard,completed,60,44,47
104,male,group C,some college,standard,completed,98,86,90
105,female,group C,some college,standard,none,58,67,72
106,female,group D,master's degree,standard,none,87,100,100
107,male,group E,associate's degree,standard,completed,66,63,64
108,female,group B,associate's degree,free/reduced,none,52,76,70
109,female,group B,some high school,standard,none,70,64,72
110,female,group D,associate's degree,free/reduced,completed,77,89,98
111,male,group C,high school,standard,none,62,55,49
112,male,group A,associate's degree,standard,none,54,53,47
113,female,group D,some college,standard,none,51,58,54
114,female,group E,bachelor's degree,standard,completed,99,100,100
115,male,group C,high school,standard,none,84,77,74
116,female,group B,bachelor's degree,free/reduced,none,75,85,82
117,female,group D,bachelor's degree,standard,none,78,82,79
118,female,group D,some high school,standard,none,51,63,61
119,female,group C,some college,standard,none,55,69,65
120,female,group C,bachelor's degree,standard,completed,79,92,89
121,male,group B,associate's degree,standard,completed,91,89,92
122,female,group C,some college,standard,completed,88,93,93
123,male,group D,high school,free/reduced,none,63,57,56
124,male,group E,some college,standard,none,83,80,73
125,female,group B,high school,standard,none,87,95,86
126,male,group B,some high school,standard,none,72,68,67
127,male,group D,some college,standard,completed,65,77,74
128,male,group D,master's degree,standard,none,82,82,74
129,female,group A,bachelor's degree,standard,none,51,49,51
130,male,group D,master's degree,standard,none,89,84,82
131,male,group C,some high school,free/reduced,completed,53,37,40
132,male,group E,some college,free/reduced,completed,87,74,70
133,female,group C,some college,standard,completed,75,81,84
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75
135,male,group C,bachelor's degree,standard,none,58,55,48
136,male,group B,some high school,standard,completed,51,54,41
137,male,group E,high school,standard,none,70,55,56
138,female,group C,associate's degree,standard,none,59,66,67
139,male,group D,some college,standard,completed,71,61,69
140,female,group D,some high school,standard,none,76,72,71
141,female,group C,some college,free/reduced,none,59,62,64
142,female,group E,some college,free/reduced,completed,42,55,54
143,male,group A,high school,standard,none,57,43,47
144,male,group D,some college,standard,none,88,73,78
145,female,group C,some college,free/reduced,none,22,39,33
146,male,group B,some high school,standard,none,88,84,75
147,male,group C,associate's degree,free/reduced,none,73,68,66
148,female,group D,bachelor's degree,standard,completed,68,75,81
149,male,group E,associate's degree,free/reduced,completed,100,100,93
150,male,group A,some high school,standard,completed,62,67,69
151,male,group A,bachelor's degree,standard,none,77,67,68
152,female,group B,associate's degree,standard,completed,59,70,66
153,male,group D,bachelor's degree,standard,none,54,49,47
154,male,group D,some high school,standard,none,62,67,61
155,female,group C,some college,standard,completed,70,89,88
156,female,group E,high school,free/reduced,completed,66,74,78
157,male,group B,some college,free/reduced,none,60,60,60
158,female,group B,associate's degree,standard,completed,61,86,87
159,male,group D,associate's degree,free/reduced,none,66,62,64
160,male,group B,associate's degree,free/reduced,completed,82,78,74
161,female,group E,some college,free/reduced,completed,75,88,85
162,male,group B,master's degree,free/reduced,none,49,53,52
163,male,group C,high school,standard,none,52,53,49
164,female,group E,master's degree,standard,none,81,92,91
165,female,group C,bachelor's degree,standard,completed,96,100,100
166,male,group C,high school,free/reduced,completed,53,51,51
167,female,group B,master's degree,free/reduced,completed,58,76,78
168,female,group B,high school,standard,completed,68,83,78
169,female,group C,some college,free/reduced,completed,67,75,70
170,male,group A,high school,standard,completed,72,73,74
171,male,group E,some high school,standard,none,94,88,78
172,female,group D,some college,standard,none,79,86,81
173,female,group C,associate's degree,standard,none,63,67,70
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54
175,female,group C,master's degree,standard,completed,81,91,87
176,female,group B,high school,free/reduced,completed,46,54,58
177,female,group C,associate's degree,standard,completed,71,77,77
178,female,group B,master's degree,free/reduced,completed,52,70,62
179,female,group D,some high school,standard,completed,97,100,100
180,male,group C,master's degree,free/reduced,completed,62,68,75
181,female,group C,some college,free/reduced,none,46,64,66
182,female,group E,high school,standard,none,50,50,47
183,female,group D,associate's degree,standard,none,65,69,70
184,male,group C,some high school,free/reduced,completed,45,52,49
185,male,group C,associate's degree,free/reduced,completed,65,67,65
186,male,group E,high school,standard,none,80,76,65
187,male,group D,some high school,standard,completed,62,66,68
188,male,group B,some high school,free/reduced,none,48,52,45
189,female,group C,bachelor's degree,standard,none,77,88,87
190,female,group E,associate's degree,standard,none,66,65,69
191,male,group D,some college,standard,completed,76,83,79
192,female,group B,some high school,standard,none,62,64,66
193,male,group D,some college,standard,completed,77,62,62
194,female,group C,master's degree,standard,completed,69,84,85
195,male,group D,associate's degree,standard,none,61,55,52
196,male,group C,some high school,free/reduced,completed,59,69,65
197,male,group E,high school,free/reduced,none,55,56,51
198,female,group B,some college,free/reduced,none,45,53,55
199,female,group B,bachelor's degree,free/reduced,none,78,79,76
200,female,group C,associate's degree,standard,completed,67,84,86
201,female,group D,some college,free/reduced,none,65,81,77
202,male,group C,associate's degree,standard,none,69,77,69
203,female,group B,associate's degree,standard,none,57,69,68
204,male,group C,some college,standard,none,59,41,42
205,male,group D,some high school,standard,completed,74,71,78
206,male,group E,bachelor's degree,standard,none,82,62,62
207,male,group E,high school,standard,completed,81,80,76
208,female,group B,some college,free/reduced,none,74,81,76
209,female,group B,some college,free/reduced,none,58,61,66
210,male,group D,some high school,free/reduced,completed,80,79,79
211,male,group C,some college,free/reduced,none,35,28,27
212,female,group C,high school,free/reduced,none,42,62,60
213,male,group C,associate's degree,free/reduced,completed,60,51,56
214,male,group E,high school,standard,completed,87,91,81
215,male,group B,some high school,standard,completed,84,83,75
216,female,group E,associate's degree,free/reduced,completed,83,86,88
217,female,group C,high school,free/reduced,none,34,42,39
218,male,group B,high school,free/reduced,none,66,77,70
219,male,group B,some high school,standard,completed,61,56,56
220,female,group D,high school,standard,completed,56,68,74
221,male,group B,associate's degree,standard,none,87,85,73
222,female,group C,some high school,free/reduced,none,55,65,62
223,male,group D,some high school,standard,none,86,80,75
224,female,group B,associate's degree,standard,completed,52,66,73
225,female,group E,master's degree,free/reduced,none,45,56,54
226,female,group C,some college,standard,none,72,72,71
227,male,group D,high school,standard,none,57,50,54
228,male,group A,some high school,free/reduced,none,68,72,64
229,female,group C,some college,standard,completed,88,95,94
230,male,group D,some college,standard,none,76,64,66
231,male,group C,associate's degree,standard,none,46,43,42
232,female,group B,bachelor's degree,standard,none,67,86,83
233,male,group E,some high school,standard,none,92,87,78
234,male,group C,bachelor's degree,standard,completed,83,82,84
235,male,group D,associate's degree,standard,none,80,75,77
236,male,group D,bachelor's degree,free/reduced,none,63,66,67
237,female,group D,some high school,standard,completed,64,60,74
238,male,group B,some college,standard,none,54,52,51
239,male,group C,associate's degree,standard,none,84,80,80
240,male,group D,high school,free/reduced,completed,73,68,66
241,female,group E,bachelor's degree,standard,none,80,83,83
242,female,group D,high school,standard,none,56,52,55
243,male,group E,some college,standard,none,59,51,43
244,male,group D,some high school,standard,none,75,74,69
245,male,group C,associate's degree,standard,none,85,76,71
246,male,group E,associate's degree,standard,none,89,76,74
247,female,group B,high school,standard,completed,58,70,68
248,female,group B,high school,standard,none,65,64,62
249,male,group C,high school,standard,none,68,60,53
250,male,group A,some high school,standard,completed,47,49,49
251,female,group D,some college,free/reduced,none,71,83,83
252,female,group B,some high school,standard,completed,60,70,70
253,male,group D,master's degree,standard,none,80,80,72
254,male,group D,high school,standard,none,54,52,52
255,female,group E,some college,standard,none,62,73,70
256,female,group C,associate's degree,free/reduced,none,64,73,68
257,male,group C,associate's degree,standard,completed,78,77,77
258,female,group B,some college,standard,none,70,75,78
259,female,group C,master's degree,free/reduced,completed,65,81,81
260,female,group C,some high school,free/reduced,completed,64,79,77
261,male,group C,some college,standard,completed,79,79,78
262,female,group C,some high school,free/reduced,none,44,50,51
263,female,group E,high school,standard,none,99,93,90
264,male,group D,high school,standard,none,76,73,68
265,male,group D,some high school,free/reduced,none,59,42,41
266,female,group C,bachelor's degree,standard,none,63,75,81
267,female,group D,high school,standard,none,69,72,77
268,female,group D,associate's degree,standard,completed,88,92,95
269,female,group E,some college,free/reduced,none,71,76,70
270,male,group C,bachelor's degree,standard,none,69,63,61
271,male,group C,some college,standard,none,58,49,42
272,female,group D,associate's degree,free/reduced,none,47,53,58
273,female,group D,some college,standard,none,65,70,71
274,male,group B,some college,standard,completed,88,85,76
275,male,group C,bachelor's degree,standard,none,83,78,73
276,female,group C,some high school,standard,completed,85,92,93
277,female,group E,high school,standard,completed,59,63,75
278,female,group C,some high school,free/reduced,none,65,86,80
279,male,group B,bachelor's degree,free/reduced,none,73,56,57
280,male,group D,high school,standard,none,53,52,42
281,male,group D,high school,standard,none,45,48,46
282,female,group D,bachelor's degree,free/reduced,none,73,79,84
283,female,group D,some college,free/reduced,completed,70,78,78
284,female,group B,some high school,standard,none,37,46,46
285,male,group B,associate's degree,standard,completed,81,82,82
286,male,group E,associate's degree,standard,completed,97,82,88
287,female,group B,some high school,standard,none,67,89,82
288,male,group B,bachelor's degree,free/reduced,none,88,75,76
289,male,group E,some high school,standard,completed,77,76,77
290,male,group C,associate's degree,standard,none,76,70,68
291,male,group D,some high school,standard,none,86,73,70
292,male,group C,some high school,standard,completed,63,60,57
293,female,group E,bachelor's degree,standard,none,65,73,75
294,male,group D,high school,free/reduced,completed,78,77,80
295,male,group B,associate's degree,free/reduced,none,67,62,60
296,male,group A,some high school,standard,completed,46,41,43
297,male,group E,associate's degree,standard,completed,71,74,68
298,male,group C,high school,free/reduced,completed,40,46,50
299,male,group D,associate's degree,free/reduced,none,90,87,75
300,male,group A,some college,free/reduced,completed,81,78,81
301,male,group D,some high school,free/reduced,none,56,54,52
302,female,group C,associate's degree,standard,completed,67,84,81
303,male,group B,associate's degree,standard,none,80,76,64
304,female,group C,associate's degree,standard,completed,74,75,83
305,male,group A,some college,standard,none,69,67,69
306,male,group E,some college,standard,completed,99,87,81
307,male,group C,some high school,standard,none,51,52,44
308,female,group B,associate's degree,free/reduced,none,53,71,67
309,female,group D,high school,free/reduced,none,49,57,52
310,female,group B,associate's degree,standard,none,73,76,80
311,male,group B,bachelor's degree,standard,none,66,60,57
312,male,group D,bachelor's degree,standard,completed,67,61,68
313,female,group C,associate's degree,free/reduced,completed,68,67,69
314,female,group C,bachelor's degree,standard,completed,59,64,75
315,male,group C,high school,standard,none,71,66,65
316,female,group D,master's degree,standard,completed,77,82,91
317,male,group C,associate's degree,standard,none,83,72,78
318,male,group B,bachelor's degree,standard,none,63,71,69
319,female,group D,associate's degree,free/reduced,none,56,65,63
320,female,group C,high school,free/reduced,completed,67,79,84
321,female,group E,high school,standard,none,75,86,79
322,female,group C,some college,standard,none,71,81,80
323,female,group C,some high school,free/reduced,none,43,53,53
324,female,group C,high school,free/reduced,none,41,46,43
325,female,group C,some college,standard,none,82,90,94
326,male,group C,some college,standard,none,61,61,62
327,male,group A,some college,free/reduced,none,28,23,19
328,male,group C,associate's degree,standard,completed,82,75,77
329,female,group B,some high school,standard,none,41,55,51
330,male,group C,high school,standard,none,71,60,61
331,male,group C,associate's degree,standard,none,47,37,35
332,male,group E,associate's degree,standard,completed,62,56,53

In [28]:
# data types of each column
df_exams.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

# 2 Methods

In [29]:
# showing the first 5 columns
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [30]:
# showing the info of the dataframe
df_exams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [31]:
# describing the basic statistics of the dataframe
df_exams.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

# 3 Functions

In [32]:
# obtaining the length of the dataframe (Number of rows)
len(df_exams)

1000

In [33]:
# obtaining the highest index of the dataframe
max(df_exams.index)

999

In [34]:
# obtaining the lowest index of the datframe
min(df_exams.index)

0

In [35]:
# obtaining the data type
type(df_exams)

pandas.core.frame.DataFrame

In [36]:
# rounding the values of the of the dataset
round(df_exams, 2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
12,female,group B,high school,standard,none,65,81,73
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
15,female,group C,some high school,standard,none,69,75,78
16,male,group C,high school,standard,none,88,89,86
17,female,group B,some high school,free/reduced,none,18,32,28
18,male,group C,master's degree,free/reduced,completed,46,42,46
19,female,group C,associate's degree,free/reduced,none,54,58,61
20,male,group D,high school,standard,none,66,69,63
21,female,group B,some college,free/reduced,completed,65,75,70
22,male,group D,some college,standard,none,44,54,53
23,female,group C,some high school,standard,none,69,73,73
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80
25,male,group A,master's degree,free/reduced,none,73,74,72
26,male,group B,some college,standard,none,69,54,55
27,female,group C,bachelor's degree,standard,none,67,69,75
28,male,group C,high school,standard,none,70,70,65
29,female,group D,master's degree,standard,none,62,70,75
30,female,group D,some college,standard,none,69,74,74
31,female,group B,some college,standard,none,63,65,61
32,female,group E,master's degree,free/reduced,none,56,72,65
33,male,group D,some college,standard,none,40,42,38
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79
36,female,group D,associate's degree,standard,none,74,81,83
37,female,group D,some high school,free/reduced,none,50,64,59
38,female,group D,associate's degree,free/reduced,completed,75,90,88
39,male,group B,associate's degree,free/reduced,none,57,56,57
40,male,group C,associate's degree,free/reduced,none,55,61,54
41,female,group C,associate's degree,standard,none,58,73,68
42,female,group B,associate's degree,standard,none,53,58,65
43,male,group B,some college,free/reduced,completed,59,65,66
44,female,group E,associate's degree,free/reduced,none,50,56,54
45,male,group B,associate's degree,standard,none,65,54,57
46,female,group A,associate's degree,standard,completed,55,65,62
47,female,group C,high school,standard,none,66,71,76
48,female,group D,associate's degree,free/reduced,completed,57,74,76
49,male,group C,high school,standard,completed,82,84,82
50,male,group E,some college,standard,none,53,55,48
51,male,group E,associate's degree,free/reduced,completed,77,69,68
52,male,group C,some college,standard,none,53,44,42
53,male,group D,high school,standard,none,88,78,75
54,female,group C,some high school,free/reduced,completed,71,84,87
55,female,group C,high school,free/reduced,none,33,41,43
56,female,group E,associate's degree,standard,completed,82,85,86
57,male,group D,associate's degree,standard,none,52,55,49
58,male,group D,some college,standard,completed,58,59,58
59,female,group C,some high school,free/reduced,none,0,17,10
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72
61,male,group A,some high school,free/reduced,none,39,39,34
62,male,group A,associate's degree,free/reduced,none,62,61,55
63,female,group C,associate's degree,standard,none,69,80,71
64,female,group D,some high school,standard,none,59,58,59
65,male,group B,some high school,standard,none,67,64,61
66,male,group D,some high school,free/reduced,none,45,37,37
67,female,group C,some college,standard,none,60,72,74
68,male,group B,associate's degree,free/reduced,none,61,58,56
69,female,group C,associate's degree,standard,none,39,64,57
70,female,group D,some college,free/reduced,completed,58,63,73
71,male,group D,some college,standard,completed,63,55,63
72,female,group A,associate's degree,free/reduced,none,41,51,48
73,male,group C,some high school,free/reduced,none,61,57,56
74,male,group C,some high school,standard,none,49,49,41
75,male,group B,associate's degree,free/reduced,none,44,41,38
76,male,group E,some high school,standard,none,30,26,22
77,male,group A,bachelor's degree,standard,completed,80,78,81
78,female,group D,some high school,standard,completed,61,74,72
79,female,group E,master's degree,standard,none,62,68,68
80,female,group B,associate's degree,standard,none,47,49,50
81,male,group B,high school,free/reduced,none,49,45,45
82,male,group A,some college,free/reduced,completed,50,47,54
83,male,group E,associate's degree,standard,none,72,64,63
84,male,group D,high school,free/reduced,none,42,39,34
85,female,group C,some college,standard,none,73,80,82
86,female,group C,some college,free/reduced,none,76,83,88
87,female,group D,associate's degree,standard,none,71,71,74
88,female,group A,some college,standard,none,58,70,67
89,female,group D,some high school,standard,none,73,86,82
90,female,group C,bachelor's degree,standard,none,65,72,74
91,male,group C,high school,free/reduced,none,27,34,36
92,male,group C,high school,standard,none,71,79,71
93,male,group C,associate's degree,free/reduced,completed,43,45,50
94,female,group B,some college,standard,none,79,86,92
95,male,group C,associate's degree,free/reduced,completed,78,81,82
96,male,group B,some high school,standard,completed,65,66,62
97,female,group E,some college,standard,completed,63,72,70
98,female,group D,some college,free/reduced,none,58,67,62
99,female,group D,bachelor's degree,standard,none,65,67,62
100,male,group B,some college,standard,none,79,67,67
101,male,group D,bachelor's degree,standard,completed,68,74,74
102,female,group D,associate's degree,standard,none,85,91,89
103,male,group B,high school,standard,completed,60,44,47
104,male,group C,some college,standard,completed,98,86,90
105,female,group C,some college,standard,none,58,67,72
106,female,group D,master's degree,standard,none,87,100,100
107,male,group E,associate's degree,standard,completed,66,63,64
108,female,group B,associate's degree,free/reduced,none,52,76,70
109,female,group B,some high school,standard,none,70,64,72
110,female,group D,associate's degree,free/reduced,completed,77,89,98
111,male,group C,high school,standard,none,62,55,49
112,male,group A,associate's degree,standard,none,54,53,47
113,female,group D,some college,standard,none,51,58,54
114,female,group E,bachelor's degree,standard,completed,99,100,100
115,male,group C,high school,standard,none,84,77,74
116,female,group B,bachelor's degree,free/reduced,none,75,85,82
117,female,group D,bachelor's degree,standard,none,78,82,79
118,female,group D,some high school,standard,none,51,63,61
119,female,group C,some college,standard,none,55,69,65
120,female,group C,bachelor's degree,standard,completed,79,92,89
121,male,group B,associate's degree,standard,completed,91,89,92
122,female,group C,some college,standard,completed,88,93,93
123,male,group D,high school,free/reduced,none,63,57,56
124,male,group E,some college,standard,none,83,80,73
125,female,group B,high school,standard,none,87,95,86
126,male,group B,some high school,standard,none,72,68,67
127,male,group D,some college,standard,completed,65,77,74
128,male,group D,master's degree,standard,none,82,82,74
129,female,group A,bachelor's degree,standard,none,51,49,51
130,male,group D,master's degree,standard,none,89,84,82
131,male,group C,some high school,free/reduced,completed,53,37,40
132,male,group E,some college,free/reduced,completed,87,74,70
133,female,group C,some college,standard,completed,75,81,84
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75
135,male,group C,bachelor's degree,standard,none,58,55,48
136,male,group B,some high school,standard,completed,51,54,41
137,male,group E,high school,standard,none,70,55,56
138,female,group C,associate's degree,standard,none,59,66,67
139,male,group D,some college,standard,completed,71,61,69
140,female,group D,some high school,standard,none,76,72,71
141,female,group C,some college,free/reduced,none,59,62,64
142,female,group E,some college,free/reduced,completed,42,55,54
143,male,group A,high school,standard,none,57,43,47
144,male,group D,some college,standard,none,88,73,78
145,female,group C,some college,free/reduced,none,22,39,33
146,male,group B,some high school,standard,none,88,84,75
147,male,group C,associate's degree,free/reduced,none,73,68,66
148,female,group D,bachelor's degree,standard,completed,68,75,81
149,male,group E,associate's degree,free/reduced,completed,100,100,93
150,male,group A,some high school,standard,completed,62,67,69
151,male,group A,bachelor's degree,standard,none,77,67,68
152,female,group B,associate's degree,standard,completed,59,70,66
153,male,group D,bachelor's degree,standard,none,54,49,47
154,male,group D,some high school,standard,none,62,67,61
155,female,group C,some college,standard,completed,70,89,88
156,female,group E,high school,free/reduced,completed,66,74,78
157,male,group B,some college,free/reduced,none,60,60,60
158,female,group B,associate's degree,standard,completed,61,86,87
159,male,group D,associate's degree,free/reduced,none,66,62,64
160,male,group B,associate's degree,free/reduced,completed,82,78,74
161,female,group E,some college,free/reduced,completed,75,88,85
162,male,group B,master's degree,free/reduced,none,49,53,52
163,male,group C,high school,standard,none,52,53,49
164,female,group E,master's degree,standard,none,81,92,91
165,female,group C,bachelor's degree,standard,completed,96,100,100
166,male,group C,high school,free/reduced,completed,53,51,51
167,female,group B,master's degree,free/reduced,completed,58,76,78
168,female,group B,high school,standard,completed,68,83,78
169,female,group C,some college,free/reduced,completed,67,75,70
170,male,group A,high school,standard,completed,72,73,74
171,male,group E,some high school,standard,none,94,88,78
172,female,group D,some college,standard,none,79,86,81
173,female,group C,associate's degree,standard,none,63,67,70
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54
175,female,group C,master's degree,standard,completed,81,91,87
176,female,group B,high school,free/reduced,completed,46,54,58
177,female,group C,associate's degree,standard,completed,71,77,77
178,female,group B,master's degree,free/reduced,completed,52,70,62
179,female,group D,some high school,standard,completed,97,100,100
180,male,group C,master's degree,free/reduced,completed,62,68,75
181,female,group C,some college,free/reduced,none,46,64,66
182,female,group E,high school,standard,none,50,50,47
183,female,group D,associate's degree,standard,none,65,69,70
184,male,group C,some high school,free/reduced,completed,45,52,49
185,male,group C,associate's degree,free/reduced,completed,65,67,65
186,male,group E,high school,standard,none,80,76,65
187,male,group D,some high school,standard,completed,62,66,68
188,male,group B,some high school,free/reduced,none,48,52,45
189,female,group C,bachelor's degree,standard,none,77,88,87
190,female,group E,associate's degree,standard,none,66,65,69
191,male,group D,some college,standard,completed,76,83,79
192,female,group B,some high school,standard,none,62,64,66
193,male,group D,some college,standard,completed,77,62,62
194,female,group C,master's degree,standard,completed,69,84,85
195,male,group D,associate's degree,standard,none,61,55,52
196,male,group C,some high school,free/reduced,completed,59,69,65
197,male,group E,high school,free/reduced,none,55,56,51
198,female,group B,some college,free/reduced,none,45,53,55
199,female,group B,bachelor's degree,free/reduced,none,78,79,76
200,female,group C,associate's degree,standard,completed,67,84,86
201,female,group D,some college,free/reduced,none,65,81,77
202,male,group C,associate's degree,standard,none,69,77,69
203,female,group B,associate's degree,standard,none,57,69,68
204,male,group C,some college,standard,none,59,41,42
205,male,group D,some high school,standard,completed,74,71,78
206,male,group E,bachelor's degree,standard,none,82,62,62
207,male,group E,high school,standard,completed,81,80,76
208,female,group B,some college,free/reduced,none,74,81,76
209,female,group B,some college,free/reduced,none,58,61,66
210,male,group D,some high school,free/reduced,completed,80,79,79
211,male,group C,some college,free/reduced,none,35,28,27
212,female,group C,high school,free/reduced,none,42,62,60
213,male,group C,associate's degree,free/reduced,completed,60,51,56
214,male,group E,high school,standard,completed,87,91,81
215,male,group B,some high school,standard,completed,84,83,75
216,female,group E,associate's degree,free/reduced,completed,83,86,88
217,female,group C,high school,free/reduced,none,34,42,39
218,male,group B,high school,free/reduced,none,66,77,70
219,male,group B,some high school,standard,completed,61,56,56
220,female,group D,high school,standard,completed,56,68,74
221,male,group B,associate's degree,standard,none,87,85,73
222,female,group C,some high school,free/reduced,none,55,65,62
223,male,group D,some high school,standard,none,86,80,75
224,female,group B,associate's degree,standard,completed,52,66,73
225,female,group E,master's degree,free/reduced,none,45,56,54
226,female,group C,some college,standard,none,72,72,71
227,male,group D,high school,standard,none,57,50,54
228,male,group A,some high school,free/reduced,none,68,72,64
229,female,group C,some college,standard,completed,88,95,94
230,male,group D,some college,standard,none,76,64,66
231,male,group C,associate's degree,standard,none,46,43,42
232,female,group B,bachelor's degree,standard,none,67,86,83
233,male,group E,some high school,standard,none,92,87,78
234,male,group C,bachelor's degree,standard,completed,83,82,84
235,male,group D,associate's degree,standard,none,80,75,77
236,male,group D,bachelor's degree,free/reduced,none,63,66,67
237,female,group D,some high school,standard,completed,64,60,74
238,male,group B,some college,standard,none,54,52,51
239,male,group C,associate's degree,standard,none,84,80,80
240,male,group D,high school,free/reduced,completed,73,68,66
241,female,group E,bachelor's degree,standard,none,80,83,83
242,female,group D,high school,standard,none,56,52,55
243,male,group E,some college,standard,none,59,51,43
244,male,group D,some high school,standard,none,75,74,69
245,male,group C,associate's degree,standard,none,85,76,71
246,male,group E,associate's degree,standard,none,89,76,74
247,female,group B,high school,standard,completed,58,70,68
248,female,group B,high school,standard,none,65,64,62
249,male,group C,high school,standard,none,68,60,53
250,male,group A,some high school,standard,completed,47,49,49
251,female,group D,some college,free/reduced,none,71,83,83
252,female,group B,some high school,standard,completed,60,70,70
253,male,group D,master's degree,standard,none,80,80,72
254,male,group D,high school,standard,none,54,52,52
255,female,group E,some college,standard,none,62,73,70
256,female,group C,associate's degree,free/reduced,none,64,73,68
257,male,group C,associate's degree,standard,completed,78,77,77
258,female,group B,some college,standard,none,70,75,78
259,female,group C,master's degree,free/reduced,completed,65,81,81
260,female,group C,some high school,free/reduced,completed,64,79,77
261,male,group C,some college,standard,completed,79,79,78
262,female,group C,some high school,free/reduced,none,44,50,51
263,female,group E,high school,standard,none,99,93,90
264,male,group D,high school,standard,none,76,73,68
265,male,group D,some high school,free/reduced,none,59,42,41
266,female,group C,bachelor's degree,standard,none,63,75,81
267,female,group D,high school,standard,none,69,72,77
268,female,group D,associate's degree,standard,completed,88,92,95
269,female,group E,some college,free/reduced,none,71,76,70
270,male,group C,bachelor's degree,standard,none,69,63,61
271,male,group C,some college,standard,none,58,49,42
272,female,group D,associate's degree,free/reduced,none,47,53,58
273,female,group D,some college,standard,none,65,70,71
274,male,group B,some college,standard,completed,88,85,76
275,male,group C,bachelor's degree,standard,none,83,78,73
276,female,group C,some high school,standard,completed,85,92,93
277,female,group E,high school,standard,completed,59,63,75
278,female,group C,some high school,free/reduced,none,65,86,80
279,male,group B,bachelor's degree,free/reduced,none,73,56,57
280,male,group D,high school,standard,none,53,52,42
281,male,group D,high school,standard,none,45,48,46
282,female,group D,bachelor's degree,free/reduced,none,73,79,84
283,female,group D,some college,free/reduced,completed,70,78,78
284,female,group B,some high school,standard,none,37,46,46
285,male,group B,associate's degree,standard,completed,81,82,82
286,male,group E,associate's degree,standard,completed,97,82,88
287,female,group B,some high school,standard,none,67,89,82
288,male,group B,bachelor's degree,free/reduced,none,88,75,76
289,male,group E,some high school,standard,completed,77,76,77
290,male,group C,associate's degree,standard,none,76,70,68
291,male,group D,some high school,standard,none,86,73,70
292,male,group C,some high school,standard,completed,63,60,57
293,female,group E,bachelor's degree,standard,none,65,73,75
294,male,group D,high school,free/reduced,completed,78,77,80
295,male,group B,associate's degree,free/reduced,none,67,62,60
296,male,group A,some high school,standard,completed,46,41,43
297,male,group E,associate's degree,standard,completed,71,74,68
298,male,group C,high school,free/reduced,completed,40,46,50
299,male,group D,associate's degree,free/reduced,none,90,87,75
300,male,group A,some college,free/reduced,completed,81,78,81
301,male,group D,some high school,free/reduced,none,56,54,52
302,female,group C,associate's degree,standard,completed,67,84,81
303,male,group B,associate's degree,standard,none,80,76,64
304,female,group C,associate's degree,standard,completed,74,75,83
305,male,group A,some college,standard,none,69,67,69
306,male,group E,some college,standard,completed,99,87,81
307,male,group C,some high school,standard,none,51,52,44
308,female,group B,associate's degree,free/reduced,none,53,71,67
309,female,group D,high school,free/reduced,none,49,57,52
310,female,group B,associate's degree,standard,none,73,76,80
311,male,group B,bachelor's degree,standard,none,66,60,57
312,male,group D,bachelor's degree,standard,completed,67,61,68
313,female,group C,associate's degree,free/reduced,completed,68,67,69
314,female,group C,bachelor's degree,standard,completed,59,64,75
315,male,group C,high school,standard,none,71,66,65
316,female,group D,master's degree,standard,completed,77,82,91
317,male,group C,associate's degree,standard,none,83,72,78
318,male,group B,bachelor's degree,standard,none,63,71,69
319,female,group D,associate's degree,free/reduced,none,56,65,63
320,female,group C,high school,free/reduced,completed,67,79,84
321,female,group E,high school,standard,none,75,86,79
322,female,group C,some college,standard,none,71,81,80
323,female,group C,some high school,free/reduced,none,43,53,53
324,female,group C,high school,free/reduced,none,41,46,43
325,female,group C,some college,standard,none,82,90,94
326,male,group C,some college,standard,none,61,61,62
327,male,group A,some college,free/reduced,none,28,23,19
328,male,group C,associate's degree,standard,completed,82,75,77
329,female,group B,some high school,standard,none,41,55,51
330,male,group C,high school,standard,none,71,60,61
331,male,group C,associate's degree,standard,none,47,37,35
332,male,group E,associate's degree,standard,completed,62,56,53

# 1 Selecting one column

## 1.1 Syntax

In [37]:
# select a column with [] (preferred way to select a column)
df_exams['gender']

0      female
1      female
2      female
3        male
4        male
5      female
6      female
7        male
8        male
9      female
10       male
11       male
12     female
13       male
14     female
15     female
16       male
17     female
18       male
19     female
20       male
21     female
22       male
23     female
24       male
25       male
26       male
27     female
28       male
29     female
30     female
31     female
32     female
33       male
34       male
35       male
36     female
37     female
38     female
39       male
40       male
41     female
42     female
43       male
44     female
45       male
46     female
47     female
48     female
49       male
50       male
51       male
52       male
53       male
54     female
55     female
56     female
57       male
58       male
59     female
60       male
61       male
62       male
63     female
64     female
65       male
66       male
67     female
68       male
69     female
70     female
71       male
72     female
73       male
74       male
75       male
76       male
77       male
78     female
79     female
80     female
81       male
82       male
83       male
84       male
85     female
86     female
87     female
88     female
89     female
90     female
91       male
92       male
93       male
94     female
95       male
96       male
97     female
98     female
99     female
100      male
101      male
102    female
103      male
104      male
105    female
106    female
107      male
108    female
109    female
110    female
111      male
112      male
113    female
114    female
115      male
116    female
117    female
118    female
119    female
120    female
121      male
122    female
123      male
124      male
125    female
126      male
127      male
128      male
129    female
130      male
131      male
132      male
133    female
134      male
135      male
136      male
137      male
138    female
139      male
140    female
141    female
142    female
143      male
144      male
145    female
146      male
147      male
148    female
149      male
150      male
151      male
152    female
153      male
154      male
155    female
156    female
157      male
158    female
159      male
160      male
161    female
162      male
163      male
164    female
165    female
166      male
167    female
168    female
169    female
170      male
171      male
172    female
173    female
174    female
175    female
176    female
177    female
178    female
179    female
180      male
181    female
182    female
183    female
184      male
185      male
186      male
187      male
188      male
189    female
190    female
191      male
192    female
193      male
194    female
195      male
196      male
197      male
198    female
199    female
200    female
201    female
202      male
203    female
204      male
205      male
206      male
207      male
208    female
209    female
210      male
211      male
212    female
213      male
214      male
215      male
216    female
217    female
218      male
219      male
220    female
221      male
222    female
223      male
224    female
225    female
226    female
227      male
228      male
229    female
230      male
231      male
232    female
233      male
234      male
235      male
236      male
237    female
238      male
239      male
240      male
241    female
242    female
243      male
244      male
245      male
246      male
247    female
248    female
249      male
250      male
251    female
252    female
253      male
254      male
255    female
256    female
257      male
258    female
259    female
260    female
261      male
262    female
263    female
264      male
265      male
266    female
267    female
268    female
269    female
270      male
271      male
272    female
273    female
274      male
275      male
276    female
277    female
278    female
279      male
280      male
281      male
282    female
283    female
284    female
285      male
286      male
287    female
288      male
289      male
290      male
291      male
292      male
293    female
294      male
295      male
296      male
297      male
298      male
299      male
300      male
301      male
302    female
303      male
304    female
305      male
306      male
307      male
308    female
309    female
310    female
311      male
312      male
313    female
314    female
315      male
316    female
317      male
318      male
319    female
320    female
321    female
322    female
323    female
324    female
325    female
326      male
327      male
328      male
329    female
330      male
331      male
332      male
333      male
334    female
335    female
336      male
337      male
338    female
339    female
340      male
341    female
342    female
343      male
344      male
345    female
346      male
347    female
348      male
349      male
350    female
351      male
352    female
353    female
354    female
355    female
356      male
357    female
358      male
359    female
360    female
361      male
362    female
363    female
364      male
365      male
366      male
367      male
368    female
369    female
370      male
371    female
372      male
373    female
374    female
375      male
376    female
377    female
378    female
379      male
380    female
381      male
382      male
383    female
384    female
385    female
386    female
387    female
388    female
389      male
390      male
391    female
392      male
393      male
394    female
395      male
396    female
397    female
398      male
399      male
400    female
401      male
402    female
403    female
404    female
405    female
406      male
407    female
408    female
409      male
410    female
411      male
412      male
413      male
414    female
415      male
416      male
417      male
418      male
419      male
420    female
421    female
422    female
423    female
424      male
425    female
426      male
427      male
428      male
429      male
430      male
431    female
432      male
433    female
434      male
435      male
436      male
437      male
438      male
439      male
440    female
441    female
442    female
443    female
444      male
445    female
446      male
447      male
448      male
449      male
450    female
451    female
452    female
453      male
454    female
455      male
456    female
457      male
458    female
459      male
460      male
461      male
462    female
463    female
464      male
465    female
466    female
467      male
468    female
469      male
470    female
471    female
472    female
473    female
474    female
475    female
476      male
477      male
478    female
479      male
480      male
481    female
482      male
483      male
484    female
485      male
486      male
487    female
488      male
489      male
490    female
491    female
492    female
493    female
494    female
495      male
496    female
497    female
498    female
499      male
500    female
501    female
502      male
503    female
504    female
505    female
506      male
507      male
508      male
509    female
510      male
511      male
512      male
513    female
514    female
515    female
516    female
517    female
518    female
519    female
520      male
521    female
522      male
523      male
524      male
525      male
526      male
527    female
528    female
529    female
530    female
531    female
532      male
533    female
534      male
535    female
536      male
537    female
538      male
539      male
540      male
541      male
542    female
543    female
544    female
545      male
546    female
547      male
548    female
549      male
550      male
551      male
552    female
553      male
554      male
555    female
556    female
557      male
558    female
559      male
560    female
561    female
562      male
563    female
564      male
565      male
566    female
567    female
568      male
569      male
570      male
571      male
572    female
573    female
574    female
575      male
576      male
577    female
578    female
579    female
580    female
581    female
582    female
583    female
584    female
585    female
586    female
587    female
588    female
589    female
590      male
591      male
592      male
593    female
594    female
595    female
596      male
597      male
598    female
599    female
600    female
601    female
602    female
603      male
604      male
605      male
606    female
607    female
608    female
609    female
610      male
611    female
612      male
613    female
614    female
615    female
616    female
617      male
618      male
619      male
620    female
621      male
622      male
623      male
624    female
625      male
626      male
627      male
628      male
629    female
630      male
631      male
632    female
633    female
634      male
635      male
636    female
637    female
638      male
639    female
640      male
641    female
642    female
643    female
644      male
645    female
646    female
647    female
648    female
649    female
650      male
651    female
652    female
653    female
654    female
655    female
656      male
657      male
658    female
659      male
660      male
661      male
662    female
663    female
664      male
665    female
666    female
667    female
668      male
669      male
670    female
671      male
672    female
673    female
674    female
675    female
676    female
677    female
678      male
679      male
680    female
681      male
682      male
683    female
684      male
685    female
686      male
687      male
688      male
689      male
690    female
691    female
692    female
693    female
694    female
695    female
696    female
697    female
698    female
699      male
700    female
701    female
702      male
703    female
704    female
705      male
706      male
707      male
708      male
709    female
710      male
711    female
712    female
713      male
714    female
715    female
716      male
717    female
718    female
719      male
720    female
721      male
722    female
723      male
724      male
725      male
726    female
727      male
728    female
729      male
730    female
731      male
732    female
733      male
734    female
735      male
736      male
737    female
738      male
739      male
740      male
741    female
742    female
743    female
744      male
745      male
746      male
747      male
748    female
749      male
750      male
751      male
752      male
753    female
754      male
755    female
756      male
757      male
758    female
759      male
760    female
761    female
762      male
763    female
764      male
765    female
766    female
767      male
768    female
769      male
770      male
771      male
772    female
773    female
774      male
775    female
776    female
777    female
778    female
779      male
780    female
781    female
782    female
783    female
784      male
785    female
786    female
787    female
788      male
789    female
790    female
791    female
792      male
793      male
794    female
795    female
796      male
797    female
798      male
799    female
800      male
801      male
802    female
803    female
804    female
805      male
806    female
807    female
808      male
809      male
810      male
811      male
812    female
813      male
814    female
815      male
816    female
817      male
818    female
819    female
820    female
821    female
822      male
823    female
824    female
825      male
826    female
827    female
828    female
829      male
830    female
831    female
832      male
833    female
834      male
835    female
836      male
837    female
838      male
839    female
840    female
841      male
842    female
843      male
844    female
845      male
846      male
847      male
848    female
849      male
850      male
851    female
852    female
853      male
854      male
855    female
856      male
857    female
858      male
859      male
860    female
861    female
862      male
863    female
864      male
865      male
866      male
867      male
868      male
869      male
870      male
871    female
872      male
873      male
874    female
875      male
876      male
877      male
878    female
879    female
880      male
881    female
882    female
883      male
884    female
885    female
886    female
887      male
888    female
889      male
890    female
891    female
892    female
893      male
894    female
895    female
896      male
897    female
898      male
899    female
900      male
901    female
902    female
903    female
904    female
905      male
906      male
907    female
908    female
909      male
910      male
911    female
912    female
913    female
914    female
915    female
916      male
917    female
918    female
919      male
920      male
921    female
922      male
923    female
924      male
925      male
926      male
927    female
928      male
929    female
930      male
931      male
932      male
933      male
934      male
935      male
936      male
937    female
938      male
939      male
940      male
941    female
942      male
943      male
944    female
945    female
946      male
947    female
948      male
949    female
950      male
951    female
952    female
953      male
954    female
955      male
956      male
957    female
958    female
959      male
960    female
961    female
962    female
963    female
964      male
965    female
966      male
967      male
968    female
969    female
970    female
971      male
972    female
973    female
974    female
975    female
976      male
977      male
978      male
979    female
980    female
981      male
982      male
983    female
984    female
985      male
986    female
987      male
988    female
989    female
990      male
991    female
992    female
993    female
994      male
995    female
996      male
997    female
998    female
999    female
Name: gender, dtype: object

In [38]:
# check out the data type a column
type(df_exams['gender'])

pandas.core.series.Series

In [39]:
# series: attributes and the methods
df_exams['gender'].index
df_exams['gender'].head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

## 1.2 Syntax

In [40]:
# select a column with .
df_exams.gender

0      female
1      female
2      female
3        male
4        male
5      female
6      female
7        male
8        male
9      female
10       male
11       male
12     female
13       male
14     female
15     female
16       male
17     female
18       male
19     female
20       male
21     female
22       male
23     female
24       male
25       male
26       male
27     female
28       male
29     female
30     female
31     female
32     female
33       male
34       male
35       male
36     female
37     female
38     female
39       male
40       male
41     female
42     female
43       male
44     female
45       male
46     female
47     female
48     female
49       male
50       male
51       male
52       male
53       male
54     female
55     female
56     female
57       male
58       male
59     female
60       male
61       male
62       male
63     female
64     female
65       male
66       male
67     female
68       male
69     female
70     female
71       male
72     female
73       male
74       male
75       male
76       male
77       male
78     female
79     female
80     female
81       male
82       male
83       male
84       male
85     female
86     female
87     female
88     female
89     female
90     female
91       male
92       male
93       male
94     female
95       male
96       male
97     female
98     female
99     female
100      male
101      male
102    female
103      male
104      male
105    female
106    female
107      male
108    female
109    female
110    female
111      male
112      male
113    female
114    female
115      male
116    female
117    female
118    female
119    female
120    female
121      male
122    female
123      male
124      male
125    female
126      male
127      male
128      male
129    female
130      male
131      male
132      male
133    female
134      male
135      male
136      male
137      male
138    female
139      male
140    female
141    female
142    female
143      male
144      male
145    female
146      male
147      male
148    female
149      male
150      male
151      male
152    female
153      male
154      male
155    female
156    female
157      male
158    female
159      male
160      male
161    female
162      male
163      male
164    female
165    female
166      male
167    female
168    female
169    female
170      male
171      male
172    female
173    female
174    female
175    female
176    female
177    female
178    female
179    female
180      male
181    female
182    female
183    female
184      male
185      male
186      male
187      male
188      male
189    female
190    female
191      male
192    female
193      male
194    female
195      male
196      male
197      male
198    female
199    female
200    female
201    female
202      male
203    female
204      male
205      male
206      male
207      male
208    female
209    female
210      male
211      male
212    female
213      male
214      male
215      male
216    female
217    female
218      male
219      male
220    female
221      male
222    female
223      male
224    female
225    female
226    female
227      male
228      male
229    female
230      male
231      male
232    female
233      male
234      male
235      male
236      male
237    female
238      male
239      male
240      male
241    female
242    female
243      male
244      male
245      male
246      male
247    female
248    female
249      male
250      male
251    female
252    female
253      male
254      male
255    female
256    female
257      male
258    female
259    female
260    female
261      male
262    female
263    female
264      male
265      male
266    female
267    female
268    female
269    female
270      male
271      male
272    female
273    female
274      male
275      male
276    female
277    female
278    female
279      male
280      male
281      male
282    female
283    female
284    female
285      male
286      male
287    female
288      male
289      male
290      male
291      male
292      male
293    female
294      male
295      male
296      male
297      male
298      male
299      male
300      male
301      male
302    female
303      male
304    female
305      male
306      male
307      male
308    female
309    female
310    female
311      male
312      male
313    female
314    female
315      male
316    female
317      male
318      male
319    female
320    female
321    female
322    female
323    female
324    female
325    female
326      male
327      male
328      male
329    female
330      male
331      male
332      male
333      male
334    female
335    female
336      male
337      male
338    female
339    female
340      male
341    female
342    female
343      male
344      male
345    female
346      male
347    female
348      male
349      male
350    female
351      male
352    female
353    female
354    female
355    female
356      male
357    female
358      male
359    female
360    female
361      male
362    female
363    female
364      male
365      male
366      male
367      male
368    female
369    female
370      male
371    female
372      male
373    female
374    female
375      male
376    female
377    female
378    female
379      male
380    female
381      male
382      male
383    female
384    female
385    female
386    female
387    female
388    female
389      male
390      male
391    female
392      male
393      male
394    female
395      male
396    female
397    female
398      male
399      male
400    female
401      male
402    female
403    female
404    female
405    female
406      male
407    female
408    female
409      male
410    female
411      male
412      male
413      male
414    female
415      male
416      male
417      male
418      male
419      male
420    female
421    female
422    female
423    female
424      male
425    female
426      male
427      male
428      male
429      male
430      male
431    female
432      male
433    female
434      male
435      male
436      male
437      male
438      male
439      male
440    female
441    female
442    female
443    female
444      male
445    female
446      male
447      male
448      male
449      male
450    female
451    female
452    female
453      male
454    female
455      male
456    female
457      male
458    female
459      male
460      male
461      male
462    female
463    female
464      male
465    female
466    female
467      male
468    female
469      male
470    female
471    female
472    female
473    female
474    female
475    female
476      male
477      male
478    female
479      male
480      male
481    female
482      male
483      male
484    female
485      male
486      male
487    female
488      male
489      male
490    female
491    female
492    female
493    female
494    female
495      male
496    female
497    female
498    female
499      male
500    female
501    female
502      male
503    female
504    female
505    female
506      male
507      male
508      male
509    female
510      male
511      male
512      male
513    female
514    female
515    female
516    female
517    female
518    female
519    female
520      male
521    female
522      male
523      male
524      male
525      male
526      male
527    female
528    female
529    female
530    female
531    female
532      male
533    female
534      male
535    female
536      male
537    female
538      male
539      male
540      male
541      male
542    female
543    female
544    female
545      male
546    female
547      male
548    female
549      male
550      male
551      male
552    female
553      male
554      male
555    female
556    female
557      male
558    female
559      male
560    female
561    female
562      male
563    female
564      male
565      male
566    female
567    female
568      male
569      male
570      male
571      male
572    female
573    female
574    female
575      male
576      male
577    female
578    female
579    female
580    female
581    female
582    female
583    female
584    female
585    female
586    female
587    female
588    female
589    female
590      male
591      male
592      male
593    female
594    female
595    female
596      male
597      male
598    female
599    female
600    female
601    female
602    female
603      male
604      male
605      male
606    female
607    female
608    female
609    female
610      male
611    female
612      male
613    female
614    female
615    female
616    female
617      male
618      male
619      male
620    female
621      male
622      male
623      male
624    female
625      male
626      male
627      male
628      male
629    female
630      male
631      male
632    female
633    female
634      male
635      male
636    female
637    female
638      male
639    female
640      male
641    female
642    female
643    female
644      male
645    female
646    female
647    female
648    female
649    female
650      male
651    female
652    female
653    female
654    female
655    female
656      male
657      male
658    female
659      male
660      male
661      male
662    female
663    female
664      male
665    female
666    female
667    female
668      male
669      male
670    female
671      male
672    female
673    female
674    female
675    female
676    female
677    female
678      male
679      male
680    female
681      male
682      male
683    female
684      male
685    female
686      male
687      male
688      male
689      male
690    female
691    female
692    female
693    female
694    female
695    female
696    female
697    female
698    female
699      male
700    female
701    female
702      male
703    female
704    female
705      male
706      male
707      male
708      male
709    female
710      male
711    female
712    female
713      male
714    female
715    female
716      male
717    female
718    female
719      male
720    female
721      male
722    female
723      male
724      male
725      male
726    female
727      male
728    female
729      male
730    female
731      male
732    female
733      male
734    female
735      male
736      male
737    female
738      male
739      male
740      male
741    female
742    female
743    female
744      male
745      male
746      male
747      male
748    female
749      male
750      male
751      male
752      male
753    female
754      male
755    female
756      male
757      male
758    female
759      male
760    female
761    female
762      male
763    female
764      male
765    female
766    female
767      male
768    female
769      male
770      male
771      male
772    female
773    female
774      male
775    female
776    female
777    female
778    female
779      male
780    female
781    female
782    female
783    female
784      male
785    female
786    female
787    female
788      male
789    female
790    female
791    female
792      male
793      male
794    female
795    female
796      male
797    female
798      male
799    female
800      male
801      male
802    female
803    female
804    female
805      male
806    female
807    female
808      male
809      male
810      male
811      male
812    female
813      male
814    female
815      male
816    female
817      male
818    female
819    female
820    female
821    female
822      male
823    female
824    female
825      male
826    female
827    female
828    female
829      male
830    female
831    female
832      male
833    female
834      male
835    female
836      male
837    female
838      male
839    female
840    female
841      male
842    female
843      male
844    female
845      male
846      male
847      male
848    female
849      male
850      male
851    female
852    female
853      male
854      male
855    female
856      male
857    female
858      male
859      male
860    female
861    female
862      male
863    female
864      male
865      male
866      male
867      male
868      male
869      male
870      male
871    female
872      male
873      male
874    female
875      male
876      male
877      male
878    female
879    female
880      male
881    female
882    female
883      male
884    female
885    female
886    female
887      male
888    female
889      male
890    female
891    female
892    female
893      male
894    female
895    female
896      male
897    female
898      male
899    female
900      male
901    female
902    female
903    female
904    female
905      male
906      male
907    female
908    female
909      male
910      male
911    female
912    female
913    female
914    female
915    female
916      male
917    female
918    female
919      male
920      male
921    female
922      male
923    female
924      male
925      male
926      male
927    female
928      male
929    female
930      male
931      male
932      male
933      male
934      male
935      male
936      male
937    female
938      male
939      male
940      male
941    female
942      male
943      male
944    female
945    female
946      male
947    female
948      male
949    female
950      male
951    female
952    female
953      male
954    female
955      male
956      male
957    female
958    female
959      male
960    female
961    female
962    female
963    female
964      male
965    female
966      male
967      male
968    female
969    female
970    female
971      male
972    female
973    female
974    female
975    female
976      male
977      male
978      male
979    female
980    female
981      male
982      male
983    female
984    female
985      male
986    female
987      male
988    female
989    female
990      male
991    female
992    female
993    female
994      male
995    female
996      male
997    female
998    female
999    female
Name: gender, dtype: object

In [41]:
# select a column with . (pitfalls)
df_exams.math score

SyntaxError: invalid syntax (3061062658.py, line 2)

In [42]:
# select the same column using []
df_exams['math score']

0       72
1       69
2       90
3       47
4       76
5       71
6       88
7       40
8       64
9       38
10      58
11      40
12      65
13      78
14      50
15      69
16      88
17      18
18      46
19      54
20      66
21      65
22      44
23      69
24      74
25      73
26      69
27      67
28      70
29      62
30      69
31      63
32      56
33      40
34      97
35      81
36      74
37      50
38      75
39      57
40      55
41      58
42      53
43      59
44      50
45      65
46      55
47      66
48      57
49      82
50      53
51      77
52      53
53      88
54      71
55      33
56      82
57      52
58      58
59       0
60      79
61      39
62      62
63      69
64      59
65      67
66      45
67      60
68      61
69      39
70      58
71      63
72      41
73      61
74      49
75      44
76      30
77      80
78      61
79      62
80      47
81      49
82      50
83      72
84      42
85      73
86      76
87      71
88      58
89      73
90      65
91      27
92      71
93      43
94      79
95      78
96      65
97      63
98      58
99      65
100     79
101     68
102     85
103     60
104     98
105     58
106     87
107     66
108     52
109     70
110     77
111     62
112     54
113     51
114     99
115     84
116     75
117     78
118     51
119     55
120     79
121     91
122     88
123     63
124     83
125     87
126     72
127     65
128     82
129     51
130     89
131     53
132     87
133     75
134     74
135     58
136     51
137     70
138     59
139     71
140     76
141     59
142     42
143     57
144     88
145     22
146     88
147     73
148     68
149    100
150     62
151     77
152     59
153     54
154     62
155     70
156     66
157     60
158     61
159     66
160     82
161     75
162     49
163     52
164     81
165     96
166     53
167     58
168     68
169     67
170     72
171     94
172     79
173     63
174     43
175     81
176     46
177     71
178     52
179     97
180     62
181     46
182     50
183     65
184     45
185     65
186     80
187     62
188     48
189     77
190     66
191     76
192     62
193     77
194     69
195     61
196     59
197     55
198     45
199     78
200     67
201     65
202     69
203     57
204     59
205     74
206     82
207     81
208     74
209     58
210     80
211     35
212     42
213     60
214     87
215     84
216     83
217     34
218     66
219     61
220     56
221     87
222     55
223     86
224     52
225     45
226     72
227     57
228     68
229     88
230     76
231     46
232     67
233     92
234     83
235     80
236     63
237     64
238     54
239     84
240     73
241     80
242     56
243     59
244     75
245     85
246     89
247     58
248     65
249     68
250     47
251     71
252     60
253     80
254     54
255     62
256     64
257     78
258     70
259     65
260     64
261     79
262     44
263     99
264     76
265     59
266     63
267     69
268     88
269     71
270     69
271     58
272     47
273     65
274     88
275     83
276     85
277     59
278     65
279     73
280     53
281     45
282     73
283     70
284     37
285     81
286     97
287     67
288     88
289     77
290     76
291     86
292     63
293     65
294     78
295     67
296     46
297     71
298     40
299     90
300     81
301     56
302     67
303     80
304     74
305     69
306     99
307     51
308     53
309     49
310     73
311     66
312     67
313     68
314     59
315     71
316     77
317     83
318     63
319     56
320     67
321     75
322     71
323     43
324     41
325     82
326     61
327     28
328     82
329     41
330     71
331     47
332     62
333     90
334     83
335     61
336     76
337     49
338     24
339     35
340     58
341     61
342     69
343     67
344     79
345     72
346     62
347     77
348     75
349     87
350     52
351     66
352     63
353     46
354     59
355     61
356     63
357     42
358     59
359     80
360     58
361     85
362     52
363     27
364     59
365     49
366     69
367     61
368     44
369     73
370     84
371     45
372     74
373     82
374     59
375     46
376     80
377     85
378     71
379     66
380     80
381     87
382     79
383     38
384     38
385     67
386     64
387     57
388     62
389     73
390     73
391     77
392     76
393     57
394     65
395     48
396     50
397     85
398     74
399     60
400     59
401     53
402     49
403     88
404     54
405     63
406     65
407     82
408     52
409     87
410     70
411     84
412     71
413     63
414     51
415     84
416     71
417     74
418     68
419     57
420     82
421     57
422     47
423     59
424     41
425     62
426     86
427     69
428     65
429     68
430     64
431     61
432     61
433     47
434     73
435     50
436     75
437     75
438     70
439     89
440     67
441     78
442     59
443     73
444     79
445     67
446     69
447     86
448     47
449     81
450     64
451    100
452     65
453     65
454     53
455     37
456     79
457     53
458    100
459     72
460     53
461     54
462     71
463     77
464     75
465     84
466     26
467     72
468     77
469     91
470     83
471     63
472     68
473     59
474     90
475     71
476     76
477     80
478     55
479     76
480     73
481     52
482     68
483     59
484     49
485     70
486     61
487     60
488     64
489     79
490     65
491     64
492     83
493     81
494     54
495     68
496     54
497     59
498     66
499     76
500     74
501     94
502     63
503     95
504     40
505     82
506     68
507     55
508     79
509     86
510     76
511     64
512     62
513     54
514     77
515     76
516     74
517     66
518     66
519     67
520     71
521     91
522     69
523     54
524     53
525     68
526     56
527     36
528     29
529     62
530     68
531     47
532     62
533     79
534     73
535     66
536     51
537     51
538     85
539     97
540     75
541     79
542     81
543     82
544     64
545     78
546     92
547     72
548     62
549     79
550     79
551     87
552     40
553     77
554     53
555     32
556     55
557     61
558     53
559     73
560     74
561     63
562     96
563     63
564     48
565     48
566     92
567     61
568     63
569     68
570     71
571     91
572     53
573     50
574     74
575     40
576     61
577     81
578     48
579     53
580     81
581     77
582     63
583     73
584     69
585     65
586     55
587     44
588     54
589     48
590     58
591     71
592     68
593     74
594     92
595     56
596     30
597     53
598     69
599     65
600     54
601     29
602     76
603     60
604     84
605     75
606     85
607     40
608     61
609     58
610     69
611     58
612     94
613     65
614     82
615     60
616     37
617     88
618     95
619     65
620     35
621     62
622     58
623    100
624     61
625    100
626     69
627     61
628     49
629     44
630     67
631     79
632     66
633     75
634     84
635     71
636     67
637     80
638     86
639     76
640     41
641     74
642     72
643     74
644     70
645     65
646     59
647     64
648     50
649     69
650     51
651     68
652     85
653     65
654     73
655     62
656     77
657     69
658     43
659     90
660     74
661     73
662     55
663     65
664     80
665     50
666     63
667     77
668     73
669     81
670     66
671     52
672     69
673     65
674     69
675     50
676     73
677     70
678     81
679     63
680     67
681     60
682     62
683     29
684     62
685     94
686     85
687     77
688     53
689     93
690     49
691     73
692     66
693     77
694     49
695     79
696     75
697     59
698     57
699     66
700     79
701     57
702     87
703     63
704     59
705     62
706     46
707     66
708     89
709     42
710     93
711     80
712     98
713     81
714     60
715     76
716     73
717     96
718     76
719     91
720     62
721     55
722     74
723     50
724     47
725     81
726     65
727     68
728     73
729     53
730     68
731     55
732     87
733     55
734     53
735     67
736     92
737     53
738     81
739     61
740     80
741     37
742     81
743     59
744     55
745     72
746     69
747     69
748     50
749     87
750     71
751     68
752     79
753     77
754     58
755     84
756     55
757     70
758     52
759     69
760     53
761     48
762     78
763     62
764     60
765     74
766     58
767     76
768     68
769     58
770     52
771     75
772     52
773     62
774     66
775     49
776     66
777     35
778     72
779     94
780     46
781     77
782     76
783     52
784     91
785     32
786     72
787     19
788     68
789     52
790     48
791     60
792     66
793     89
794     42
795     57
796     70
797     70
798     69
799     52
800     67
801     76
802     87
803     82
804     73
805     75
806     64
807     41
808     90
809     59
810     51
811     45
812     54
813     87
814     72
815     94
816     45
817     61
818     60
819     77
820     85
821     78
822     49
823     71
824     48
825     62
826     56
827     65
828     69
829     68
830     61
831     74
832     64
833     77
834     58
835     60
836     73
837     75
838     58
839     66
840     39
841     64
842     23
843     74
844     40
845     90
846     91
847     64
848     59
849     80
850     71
851     61
852     87
853     82
854     62
855     97
856     75
857     65
858     52
859     87
860     53
861     81
862     39
863     71
864     97
865     82
866     59
867     61
868     78
869     49
870     59
871     70
872     82
873     90
874     43
875     80
876     81
877     57
878     59
879     64
880     63
881     71
882     64
883     55
884     51
885     62
886     93
887     54
888     69
889     44
890     86
891     85
892     50
893     88
894     59
895     32
896     36
897     63
898     67
899     65
900     85
901     73
902     34
903     93
904     67
905     88
906     57
907     79
908     67
909     70
910     50
911     69
912     52
913     47
914     46
915     68
916    100
917     44
918     57
919     91
920     69
921     35
922     72
923     54
924     74
925     74
926     64
927     65
928     46
929     48
930     67
931     62
932     61
933     70
934     98
935     70
936     67
937     57
938     85
939     77
940     72
941     78
942     81
943     61
944     58
945     54
946     82
947     49
948     49
949     57
950     94
951     75
952     74
953     58
954     62
955     72
956     84
957     92
958     45
959     75
960     56
961     48
962    100
963     65
964     72
965     62
966     66
967     63
968     68
969     75
970     89
971     78
972     53
973     49
974     54
975     64
976     60
977     62
978     55
979     91
980      8
981     81
982     79
983     78
984     74
985     57
986     40
987     81
988     44
989     67
990     86
991     65
992     55
993     62
994     63
995     88
996     62
997     59
998     68
999     77
Name: math score, dtype: int64

# 2 Selecting two or more columns

In [43]:
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [44]:
# select 2 columns using [[]]
df_exams[['gender', 'math score']]

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
5    female          71
6    female          88
7      male          40
8      male          64
9    female          38
10     male          58
11     male          40
12   female          65
13     male          78
14   female          50
15   female          69
16     male          88
17   female          18
18     male          46
19   female          54
20     male          66
21   female          65
22     male          44
23   female          69
24     male          74
25     male          73
26     male          69
27   female          67
28     male          70
29   female          62
30   female          69
31   female          63
32   female          56
33     male          40
34     male          97
35     male          81
36   female          74
37   female          50
38   female          75
39     male          57
40     male          55
41   female          58
42   female          53
43     male          59
44   female          50
45     male          65
46   female          55
47   female          66
48   female          57
49     male          82
50     male          53
51     male          77
52     male          53
53     male          88
54   female          71
55   female          33
56   female          82
57     male          52
58     male          58
59   female           0
60     male          79
61     male          39
62     male          62
63   female          69
64   female          59
65     male          67
66     male          45
67   female          60
68     male          61
69   female          39
70   female          58
71     male          63
72   female          41
73     male          61
74     male          49
75     male          44
76     male          30
77     male          80
78   female          61
79   female          62
80   female          47
81     male          49
82     male          50
83     male          72
84     male          42
85   female          73
86   female          76
87   female          71
88   female          58
89   female          73
90   female          65
91     male          27
92     male          71
93     male          43
94   female          79
95     male          78
96     male          65
97   female          63
98   female          58
99   female          65
100    male          79
101    male          68
102  female          85
103    male          60
104    male          98
105  female          58
106  female          87
107    male          66
108  female          52
109  female          70
110  female          77
111    male          62
112    male          54
113  female          51
114  female          99
115    male          84
116  female          75
117  female          78
118  female          51
119  female          55
120  female          79
121    male          91
122  female          88
123    male          63
124    male          83
125  female          87
126    male          72
127    male          65
128    male          82
129  female          51
130    male          89
131    male          53
132    male          87
133  female          75
134    male          74
135    male          58
136    male          51
137    male          70
138  female          59
139    male          71
140  female          76
141  female          59
142  female          42
143    male          57
144    male          88
145  female          22
146    male          88
147    male          73
148  female          68
149    male         100
150    male          62
151    male          77
152  female          59
153    male          54
154    male          62
155  female          70
156  female          66
157    male          60
158  female          61
159    male          66
160    male          82
161  female          75
162    male          49
163    male          52
164  female          81
165  female          96
166    male          53
167  female          58
168  female          68
169  female          67
170    male          72
171    male          94
172  female          79
173  female          63
174  female          43
175  female          81
176  female          46
177  female          71
178  female          52
179  female          97
180    male          62
181  female          46
182  female          50
183  female          65
184    male          45
185    male          65
186    male          80
187    male          62
188    male          48
189  female          77
190  female          66
191    male          76
192  female          62
193    male          77
194  female          69
195    male          61
196    male          59
197    male          55
198  female          45
199  female          78
200  female          67
201  female          65
202    male          69
203  female          57
204    male          59
205    male          74
206    male          82
207    male          81
208  female          74
209  female          58
210    male          80
211    male          35
212  female          42
213    male          60
214    male          87
215    male          84
216  female          83
217  female          34
218    male          66
219    male          61
220  female          56
221    male          87
222  female          55
223    male          86
224  female          52
225  female          45
226  female          72
227    male          57
228    male          68
229  female          88
230    male          76
231    male          46
232  female          67
233    male          92
234    male          83
235    male          80
236    male          63
237  female          64
238    male          54
239    male          84
240    male          73
241  female          80
242  female          56
243    male          59
244    male          75
245    male          85
246    male          89
247  female          58
248  female          65
249    male          68
250    male          47
251  female          71
252  female          60
253    male          80
254    male          54
255  female          62
256  female          64
257    male          78
258  female          70
259  female          65
260  female          64
261    male          79
262  female          44
263  female          99
264    male          76
265    male          59
266  female          63
267  female          69
268  female          88
269  female          71
270    male          69
271    male          58
272  female          47
273  female          65
274    male          88
275    male          83
276  female          85
277  female          59
278  female          65
279    male          73
280    male          53
281    male          45
282  female          73
283  female          70
284  female          37
285    male          81
286    male          97
287  female          67
288    male          88
289    male          77
290    male          76
291    male          86
292    male          63
293  female          65
294    male          78
295    male          67
296    male          46
297    male          71
298    male          40
299    male          90
300    male          81
301    male          56
302  female          67
303    male          80
304  female          74
305    male          69
306    male          99
307    male          51
308  female          53
309  female          49
310  female          73
311    male          66
312    male          67
313  female          68
314  female          59
315    male          71
316  female          77
317    male          83
318    male          63
319  female          56
320  female          67
321  female          75
322  female          71
323  female          43
324  female          41
325  female          82
326    male          61
327    male          28
328    male          82
329  female          41
330    male          71
331    male          47
332    male          62
333    male          90
334  female          83
335  female          61
336    male          76
337    male          49
338  female          24
339  female          35
340    male          58
341  female          61
342  female          69
343    male          67
344    male          79
345  female          72
346    male          62
347  female          77
348    male          75
349    male          87
350  female          52
351    male          66
352  female          63
353  female          46
354  female          59
355  female          61
356    male          63
357  female          42
358    male          59
359  female          80
360  female          58
361    male          85
362  female          52
363  female          27
364    male          59
365    male          49
366    male          69
367    male          61
368  female          44
369  female          73
370    male          84
371  female          45
372    male          74
373  female          82
374  female          59
375    male          46
376  female          80
377  female          85
378  female          71
379    male          66
380  female          80
381    male          87
382    male          79
383  female          38
384  female          38
385  female          67
386  female          64
387  female          57
388  female          62
389    male          73
390    male          73
391  female          77
392    male          76
393    male          57
394  female          65
395    male          48
396  female          50
397  female          85
398    male          74
399    male          60
400  female          59
401    male          53
402  female          49
403  female          88
404  female          54
405  female          63
406    male          65
407  female          82
408  female          52
409    male          87
410  female          70
411    male          84
412    male          71
413    male          63
414  female          51
415    male          84
416    male          71
417    male          74
418    male          68
419    male          57
420  female          82
421  female          57
422  female          47
423  female          59
424    male          41
425  female          62
426    male          86
427    male          69
428    male          65
429    male          68
430    male          64
431  female          61
432    male          61
433  female          47
434    male          73
435    male          50
436    male          75
437    male          75
438    male          70
439    male          89
440  female          67
441  female          78
442  female          59
443  female          73
444    male          79
445  female          67
446    male          69
447    male          86
448    male          47
449    male          81
450  female          64
451  female         100
452  female          65
453    male          65
454  female          53
455    male          37
456  female          79
457    male          53
458  female         100
459    male          72
460    male          53
461    male          54
462  female          71
463  female          77
464    male          75
465  female          84
466  female          26
467    male          72
468  female          77
469    male          91
470  female          83
471  female          63
472  female          68
473  female          59
474  female          90
475  female          71
476    male          76
477    male          80
478  female          55
479    male          76
480    male          73
481  female          52
482    male          68
483    male          59
484  female          49
485    male          70
486    male          61
487  female          60
488    male          64
489    male          79
490  female          65
491  female          64
492  female          83
493  female          81
494  female          54
495    male          68
496  female          54
497  female          59
498  female          66
499    male          76
500  female          74
501  female          94
502    male          63
503  female          95
504  female          40
505  female          82
506    male          68
507    male          55
508    male          79
509  female          86
510    male          76
511    male          64
512    male          62
513  female          54
514  female          77
515  female          76
516  female          74
517  female          66
518  female          66
519  female          67
520    male          71
521  female          91
522    male          69
523    male          54
524    male          53
525    male          68
526    male          56
527  female          36
528  female          29
529  female          62
530  female          68
531  female          47
532    male          62
533  female          79
534    male          73
535  female          66
536    male          51
537  female          51
538    male          85
539    male          97
540    male          75
541    male          79
542  female          81
543  female          82
544  female          64
545    male          78
546  female          92
547    male          72
548  female          62
549    male          79
550    male          79
551    male          87
552  female          40
553    male          77
554    male          53
555  female          32
556  female          55
557    male          61
558  female          53
559    male          73
560  female          74
561  female          63
562    male          96
563  female          63
564    male          48
565    male          48
566  female          92
567  female          61
568    male          63
569    male          68
570    male          71
571    male          91
572  female          53
573  female          50
574  female          74
575    male          40
576    male          61
577  female          81
578  female          48
579  female          53
580  female          81
581  female          77
582  female          63
583  female          73
584  female          69
585  female          65
586  female          55
587  female          44
588  female          54
589  female          48
590    male          58
591    male          71
592    male          68
593  female          74
594  female          92
595  female          56
596    male          30
597    male          53
598  female          69
599  female          65
600  female          54
601  female          29
602  female          76
603    male          60
604    male          84
605    male          75
606  female          85
607  female          40
608  female          61
609  female          58
610    male          69
611  female          58
612    male          94
613  female          65
614  female          82
615  female          60
616  female          37
617    male          88
618    male          95
619    male          65
620  female          35
621    male          62
622    male          58
623    male         100
624  female          61
625    male         100
626    male          69
627    male          61
628    male          49
629  female          44
630    male          67
631    male          79
632  female          66
633  female          75
634    male          84
635    male          71
636  female          67
637  female          80
638    male          86
639  female          76
640    male          41
641  female          74
642  female          72
643  female          74
644    male          70
645  female          65
646  female          59
647  female          64
648  female          50
649  female          69
650    male          51
651  female          68
652  female          85
653  female          65
654  female          73
655  female          62
656    male          77
657    male          69
658  female          43
659    male          90
660    male          74
661    male          73
662  female          55
663  female          65
664    male          80
665  female          50
666  female          63
667  female          77
668    male          73
669    male          81
670  female          66
671    male          52
672  female          69
673  female          65
674  female          69
675  female          50
676  female          73
677  female          70
678    male          81
679    male          63
680  female          67
681    male          60
682    male          62
683  female          29
684    male          62
685  female          94
686    male          85
687    male          77
688    male          53
689    male          93
690  female          49
691  female          73
692  female          66
693  female          77
694  female          49
695  female          79
696  female          75
697  female          59
698  female          57
699    male          66
700  female          79
701  female          57
702    male          87
703  female          63
704  female          59
705    male          62
706    male          46
707    male          66
708    male          89
709  female          42
710    male          93
711  female          80
712  female          98
713    male          81
714  female          60
715  female          76
716    male          73
717  female          96
718  female          76
719    male          91
720  female          62
721    male          55
722  female          74
723    male          50
724    male          47
725    male          81
726  female          65
727    male          68
728  female          73
729    male          53
730  female          68
731    male          55
732  female          87
733    male          55
734  female          53
735    male          67
736    male          92
737  female          53
738    male          81
739    male          61
740    male          80
741  female          37
742  female          81
743  female          59
744    male          55
745    male          72
746    male          69
747    male          69
748  female          50
749    male          87
750    male          71
751    male          68
752    male          79
753  female          77
754    male          58
755  female          84
756    male          55
757    male          70
758  female          52
759    male          69
760  female          53
761  female          48
762    male          78
763  female          62
764    male          60
765  female          74
766  female          58
767    male          76
768  female          68
769    male          58
770    male          52
771    male          75
772  female          52
773  female          62
774    male          66
775  female          49
776  female          66
777  female          35
778  female          72
779    male          94
780  female          46
781  female          77
782  female          76
783  female          52
784    male          91
785  female          32
786  female          72
787  female          19
788    male          68
789  female          52
790  female          48
791  female          60
792    male          66
793    male          89
794  female          42
795  female          57
796    male          70
797  female          70
798    male          69
799  female          52
800    male          67
801    male          76
802  female          87
803  female          82
804  female          73
805    male          75
806  female          64
807  female          41
808    male          90
809    male          59
810    male          51
811    male          45
812  female          54
813    male          87
814  female          72
815    male          94
816  female          45
817    male          61
818  female          60
819  female          77
820  female          85
821  female          78
822    male          49
823  female          71
824  female          48
825    male          62
826  female          56
827  female          65
828  female          69
829    male          68
830  female          61
831  female          74

In [45]:
# check out the data type of the selection
type(df_exams[['gender', 'math score']])

pandas.core.frame.DataFrame

In [46]:
# select 2 or more columns using [[]]
df_exams[['gender','writing score','math score','reading score']]

     gender  writing score  math score  reading score
0    female             74          72             72
1    female             88          69             90
2    female             93          90             95
3      male             44          47             57
4      male             75          76             78
5    female             78          71             83
6    female             92          88             95
7      male             39          40             43
8      male             67          64             64
9    female             50          38             60
10     male             52          58             54
11     male             43          40             52
12   female             73          65             81
13     male             70          78             72
14   female             58          50             53
15   female             78          69             75
16     male             86          88             89
17   female             28          18             32
18     male             46          46             42
19   female             61          54             58
20     male             63          66             69
21   female             70          65             75
22     male             53          44             54
23   female             73          69             73
24     male             80          74             71
25     male             72          73             74
26     male             55          69             54
27   female             75          67             69
28     male             65          70             70
29   female             75          62             70
30   female             74          69             74
31   female             61          63             65
32   female             65          56             72
33     male             38          40             42
34     male             82          97             87
35     male             79          81             81
36   female             83          74             81
37   female             59          50             64
38   female             88          75             90
39     male             57          57             56
40     male             54          55             61
41   female             68          58             73
42   female             65          53             58
43     male             66          59             65
44   female             54          50             56
45     male             57          65             54
46   female             62          55             65
47   female             76          66             71
48   female             76          57             74
49     male             82          82             84
50     male             48          53             55
51     male             68          77             69
52     male             42          53             44
53     male             75          88             78
54   female             87          71             84
55   female             43          33             41
56   female             86          82             85
57     male             49          52             55
58     male             58          58             59
59   female             10           0             17
60     male             72          79             74
61     male             34          39             39
62     male             55          62             61
63   female             71          69             80
64   female             59          59             58
65     male             61          67             64
66     male             37          45             37
67   female             74          60             72
68     male             56          61             58
69   female             57          39             64
70   female             73          58             63
71     male             63          63             55
72   female             48          41             51
73     male             56          61             57
74     male             41          49             49
75     male             38          44             41
76     male             22          30             26
77     male             81          80             78
78   female             72          61             74
79   female             68          62             68
80   female             50          47             49
81     male             45          49             45
82     male             54          50             47
83     male             63          72             64
84     male             34          42             39
85   female             82          73             80
86   female             88          76             83
87   female             74          71             71
88   female             67          58             70
89   female             82          73             86
90   female             74          65             72
91     male             36          27             34
92     male             71          71             79
93     male             50          43             45
94   female             92          79             86
95     male             82          78             81
96     male             62          65             66
97   female             70          63             72
98   female             62          58             67
99   female             62          65             67
100    male             67          79             67
101    male             74          68             74
102  female             89          85             91
103    male             47          60             44
104    male             90          98             86
105  female             72          58             67
106  female            100          87            100
107    male             64          66             63
108  female             70          52             76
109  female             72          70             64
110  female             98          77             89
111    male             49          62             55
112    male             47          54             53
113  female             54          51             58
114  female            100          99            100
115    male             74          84             77
116  female             82          75             85
117  female             79          78             82
118  female             61          51             63
119  female             65          55             69
120  female             89          79             92
121    male             92          91             89
122  female             93          88             93
123    male             56          63             57
124    male             73          83             80
125  female             86          87             95
126    male             67          72             68
127    male             74          65             77
128    male             74          82             82
129  female             51          51             49
130    male             82          89             84
131    male             40          53             37
132    male             70          87             74
133  female             84          75             81
134    male             75          74             79
135    male             48          58             55
136    male             41          51             54
137    male             56          70             55
138  female             67          59             66
139    male             69          71             61
140  female             71          76             72
141  female             64          59             62
142  female             54          42             55
143    male             47          57             43
144    male             78          88             73
145  female             33          22             39
146    male             75          88             84
147    male             66          73             68
148  female             81          68             75
149    male             93         100            100
150    male             69          62             67
151    male             68          77             67
152  female             66          59             70
153    male             47          54             49
154    male             61          62             67
155  female             88          70             89
156  female             78          66             74
157    male             60          60             60
158  female             87          61             86
159    male             64          66             62
160    male             74          82             78
161  female             85          75             88
162    male             52          49             53
163    male             49          52             53
164  female             91          81             92
165  female            100          96            100
166    male             51          53             51
167  female             78          58             76
168  female             78          68             83
169  female             70          67             75
170    male             74          72             73
171    male             78          94             88
172  female             81          79             86
173  female             70          63             67
174  female             54          43             51
175  female             87          81             91
176  female             58          46             54
177  female             77          71             77
178  female             62          52             70
179  female            100          97            100
180    male             75          62             68
181  female             66          46             64
182  female             47          50             50
183  female             70          65             69
184    male             49          45             52
185    male             65          65             67
186    male             65          80             76
187    male             68          62             66
188    male             45          48             52
189  female             87          77             88
190  female             69          66             65
191    male             79          76             83
192  female             66          62             64
193    male             62          77             62
194  female             85          69             84
195    male             52          61             55
196    male             65          59             69
197    male             51          55             56
198  female             55          45             53
199  female             76          78             79
200  female             86          67             84
201  female             77          65             81
202    male             69          69             77
203  female             68          57             69
204    male             42          59             41
205    male             78          74             71
206    male             62          82             62
207    male             76          81             80
208  female             76          74             81
209  female             66          58             61
210    male             79          80             79
211    male             27          35             28
212  female             60          42             62
213    male             56          60             51
214    male             81          87             91
215    male             75          84             83
216  female             88          83             86
217  female             39          34             42
218    male             70          66             77
219    male             56          61             56
220  female             74          56             68
221    male             73          87             85
222  female             62          55             65
223    male             75          86             80
224  female             73          52             66
225  female             54          45             56
226  female             71          72             72
227    male             54          57             50
228    male             64          68             72
229  female             94          88             95
230    male             66          76             64
231    male             42          46             43
232  female             83          67             86
233    male             78          92             87
234    male             84          83             82
235    male             77          80             75
236    male             67          63             66
237  female             74          64             60
238    male             51          54             52
239    male             80          84             80
240    male             66          73             68
241  female             83          80             83
242  female             55          56             52
243    male             43          59             51
244    male             69          75             74
245    male             71          85             76
246    male             74          89             76
247  female             68          58             70
248  female             62          65             64
249    male             53          68             60
250    male             49          47             49
251  female             83          71             83
252  female             70          60             70
253    male             72          80             80
254    male             52          54             52
255  female             70          62             73
256  female             68          64             73
257    male             77          78             77
258  female             78          70             75
259  female             81          65             81
260  female             77          64             79
261    male             78          79             79
262  female             51          44             50
263  female             90          99             93
264    male             68          76             73
265    male             41          59             42
266  female             81          63             75
267  female             77          69             72
268  female             95          88             92
269  female             70          71             76
270    male             61          69             63
271    male             42          58             49
272  female             58          47             53
273  female             71          65             70
274    male             76          88             85
275    male             73          83             78
276  female             93          85             92
277  female             75          59             63
278  female             80          65             86
279    male             57          73             56
280    male             42          53             52
281    male             46          45             48
282  female             84          73             79
283  female             78          70             78
284  female             46          37             46
285    male             82          81             82
286    male             88          97             82
287  female             82          67             89
288    male             76          88             75
289    male             77          77             76
290    male             68          76             70
291    male             70          86             73
292    male             57          63             60
293  female             75          65             73
294    male             80          78             77
295    male             60          67             62
296    male             43          46             41
297    male             68          71             74
298    male             50          40             46
299    male             75          90             87
300    male             81          81             78
301    male             52          56             54
302  female             81          67             84
303    male             64          80             76
304  female             83          74             75
305    male             69          69             67
306    male             81          99             87
307    male             44          51             52
308  female             67          53             71
309  female             52          49             57
310  female             80          73             76
311    male             57          66             60
312    male             68          67             61
313  female             69          68             67
314  female             75          59             64
315    male             65          71             66
316  female             91          77             82
317    male             78          83             72
318    male             69          63             71
319  female             63          56             65
320  female             84          67             79
321  female             79          75             86
322  female             80          71             81
323  female             53          43             53
324  female             43          41             46
325  female             94          82             90
326    male             62          61             61
327    male             19          28             23
328    male             77          82             75
329  female             51          41             55
330    male             61          71             60
331    male             35          47             37
332    male             53          62             56
333    male             81          90             78
334  female             95          83             93
335  female             66          61             68
336    male             69          76             70
337    male             43          49             51
338  female             27          24             38
339  female             60          35             55
340    male             52          58             61
341  female             63          61             73
342  female             74          69             76
343    male             67          67             72
344    male             67          79             73
345  female             75          72             80
346    male             57          62             61
347  female             95          77             94
348    male             66          75             74
349    male             76          87             74
350  female             69          52             65
351    male             52          66             57
352  female             80          63             78
353  female             57          46             58
354  female             70          59             71
355  female             70          61             72
356    male             61          63             61
357  female             69          42             66
358    male             61          59             62
359  female             89          80             90
360  female             59          58             62
361    male             78          85             84
362  female             58          52             58
363  female             32          27             34
364    male             58          59             60
365    male             60          49             58
366    male             53          69             58
367    male             61          61             66
368  female             58          44             64

In [47]:
# we cant't select 2 or more columns with the "."
# not possible

# 3 Adiing a new column

## 3.1 Adding a new column with a scalar value

# Adding new column to dataframe
df_exams['language score'] = 70
df_exams

## 3.2 Adding a new column with an array

#### The dataframe has 1000 rows, so we need to create an array with 1000 elements

In [48]:
# import numpy
import numpy as np

In [49]:
# create an array of 1000 elements
language_score = np.arange(0, 1000)

In [50]:
# length of the array
len(language_score)

1000

In [51]:
# adding a new column to dataframe with an array
df_exams['language score'] = language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
5,female,group B,associate's degree,standard,none,71,83,78,5
6,female,group B,some college,standard,completed,88,95,92,6
7,male,group B,some college,free/reduced,none,40,43,39,7
8,male,group D,high school,free/reduced,completed,64,64,67,8
9,female,group B,high school,free/reduced,none,38,60,50,9
10,male,group C,associate's degree,standard,none,58,54,52,10
11,male,group D,associate's degree,standard,none,40,52,43,11
12,female,group B,high school,standard,none,65,81,73,12
13,male,group A,some college,standard,completed,78,72,70,13
14,female,group A,master's degree,standard,none,50,53,58,14
15,female,group C,some high school,standard,none,69,75,78,15
16,male,group C,high school,standard,none,88,89,86,16
17,female,group B,some high school,free/reduced,none,18,32,28,17
18,male,group C,master's degree,free/reduced,completed,46,42,46,18
19,female,group C,associate's degree,free/reduced,none,54,58,61,19
20,male,group D,high school,standard,none,66,69,63,20
21,female,group B,some college,free/reduced,completed,65,75,70,21
22,male,group D,some college,standard,none,44,54,53,22
23,female,group C,some high school,standard,none,69,73,73,23
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80,24
25,male,group A,master's degree,free/reduced,none,73,74,72,25
26,male,group B,some college,standard,none,69,54,55,26
27,female,group C,bachelor's degree,standard,none,67,69,75,27
28,male,group C,high school,standard,none,70,70,65,28
29,female,group D,master's degree,standard,none,62,70,75,29
30,female,group D,some college,standard,none,69,74,74,30
31,female,group B,some college,standard,none,63,65,61,31
32,female,group E,master's degree,free/reduced,none,56,72,65,32
33,male,group D,some college,standard,none,40,42,38,33
34,male,group E,some college,standard,none,97,87,82,34
35,male,group E,associate's degree,standard,completed,81,81,79,35
36,female,group D,associate's degree,standard,none,74,81,83,36
37,female,group D,some high school,free/reduced,none,50,64,59,37
38,female,group D,associate's degree,free/reduced,completed,75,90,88,38
39,male,group B,associate's degree,free/reduced,none,57,56,57,39
40,male,group C,associate's degree,free/reduced,none,55,61,54,40
41,female,group C,associate's degree,standard,none,58,73,68,41
42,female,group B,associate's degree,standard,none,53,58,65,42
43,male,group B,some college,free/reduced,completed,59,65,66,43
44,female,group E,associate's degree,free/reduced,none,50,56,54,44
45,male,group B,associate's degree,standard,none,65,54,57,45
46,female,group A,associate's degree,standard,completed,55,65,62,46
47,female,group C,high school,standard,none,66,71,76,47
48,female,group D,associate's degree,free/reduced,completed,57,74,76,48
49,male,group C,high school,standard,completed,82,84,82,49
50,male,group E,some college,standard,none,53,55,48,50
51,male,group E,associate's degree,free/reduced,completed,77,69,68,51
52,male,group C,some college,standard,none,53,44,42,52
53,male,group D,high school,standard,none,88,78,75,53
54,female,group C,some high school,free/reduced,completed,71,84,87,54
55,female,group C,high school,free/reduced,none,33,41,43,55
56,female,group E,associate's degree,standard,completed,82,85,86,56
57,male,group D,associate's degree,standard,none,52,55,49,57
58,male,group D,some college,standard,completed,58,59,58,58
59,female,group C,some high school,free/reduced,none,0,17,10,59
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72,60
61,male,group A,some high school,free/reduced,none,39,39,34,61
62,male,group A,associate's degree,free/reduced,none,62,61,55,62
63,female,group C,associate's degree,standard,none,69,80,71,63
64,female,group D,some high school,standard,none,59,58,59,64
65,male,group B,some high school,standard,none,67,64,61,65
66,male,group D,some high school,free/reduced,none,45,37,37,66
67,female,group C,some college,standard,none,60,72,74,67
68,male,group B,associate's degree,free/reduced,none,61,58,56,68
69,female,group C,associate's degree,standard,none,39,64,57,69
70,female,group D,some college,free/reduced,completed,58,63,73,70
71,male,group D,some college,standard,completed,63,55,63,71
72,female,group A,associate's degree,free/reduced,none,41,51,48,72
73,male,group C,some high school,free/reduced,none,61,57,56,73
74,male,group C,some high school,standard,none,49,49,41,74
75,male,group B,associate's degree,free/reduced,none,44,41,38,75
76,male,group E,some high school,standard,none,30,26,22,76
77,male,group A,bachelor's degree,standard,completed,80,78,81,77
78,female,group D,some high school,standard,completed,61,74,72,78
79,female,group E,master's degree,standard,none,62,68,68,79
80,female,group B,associate's degree,standard,none,47,49,50,80
81,male,group B,high school,free/reduced,none,49,45,45,81
82,male,group A,some college,free/reduced,completed,50,47,54,82
83,male,group E,associate's degree,standard,none,72,64,63,83
84,male,group D,high school,free/reduced,none,42,39,34,84
85,female,group C,some college,standard,none,73,80,82,85
86,female,group C,some college,free/reduced,none,76,83,88,86
87,female,group D,associate's degree,standard,none,71,71,74,87
88,female,group A,some college,standard,none,58,70,67,88
89,female,group D,some high school,standard,none,73,86,82,89
90,female,group C,bachelor's degree,standard,none,65,72,74,90
91,male,group C,high school,free/reduced,none,27,34,36,91
92,male,group C,high school,standard,none,71,79,71,92
93,male,group C,associate's degree,free/reduced,completed,43,45,50,93
94,female,group B,some college,standard,none,79,86,92,94
95,male,group C,associate's degree,free/reduced,completed,78,81,82,95
96,male,group B,some high school,standard,completed,65,66,62,96
97,female,group E,some college,standard,completed,63,72,70,97
98,female,group D,some college,free/reduced,none,58,67,62,98
99,female,group D,bachelor's degree,standard,none,65,67,62,99
100,male,group B,some college,standard,none,79,67,67,100
101,male,group D,bachelor's degree,standard,completed,68,74,74,101
102,female,group D,associate's degree,standard,none,85,91,89,102
103,male,group B,high school,standard,completed,60,44,47,103
104,male,group C,some college,standard,completed,98,86,90,104
105,female,group C,some college,standard,none,58,67,72,105
106,female,group D,master's degree,standard,none,87,100,100,106
107,male,group E,associate's degree,standard,completed,66,63,64,107
108,female,group B,associate's degree,free/reduced,none,52,76,70,108
109,female,group B,some high school,standard,none,70,64,72,109
110,female,group D,associate's degree,free/reduced,completed,77,89,98,110
111,male,group C,high school,standard,none,62,55,49,111
112,male,group A,associate's degree,standard,none,54,53,47,112
113,female,group D,some college,standard,none,51,58,54,113
114,female,group E,bachelor's degree,standard,completed,99,100,100,114
115,male,group C,high school,standard,none,84,77,74,115
116,female,group B,bachelor's degree,free/reduced,none,75,85,82,116
117,female,group D,bachelor's degree,standard,none,78,82,79,117
118,female,group D,some high school,standard,none,51,63,61,118
119,female,group C,some college,standard,none,55,69,65,119
120,female,group C,bachelor's degree,standard,completed,79,92,89,120
121,male,group B,associate's degree,standard,completed,91,89,92,121
122,female,group C,some college,standard,completed,88,93,93,122
123,male,group D,high school,free/reduced,none,63,57,56,123
124,male,group E,some college,standard,none,83,80,73,124
125,female,group B,high school,standard,none,87,95,86,125
126,male,group B,some high school,standard,none,72,68,67,126
127,male,group D,some college,standard,completed,65,77,74,127
128,male,group D,master's degree,standard,none,82,82,74,128
129,female,group A,bachelor's degree,standard,none,51,49,51,129
130,male,group D,master's degree,standard,none,89,84,82,130
131,male,group C,some high school,free/reduced,completed,53,37,40,131
132,male,group E,some college,free/reduced,completed,87,74,70,132
133,female,group C,some college,standard,completed,75,81,84,133
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75,134
135,male,group C,bachelor's degree,standard,none,58,55,48,135
136,male,group B,some high school,standard,completed,51,54,41,136
137,male,group E,high school,standard,none,70,55,56,137
138,female,group C,associate's degree,standard,none,59,66,67,138
139,male,group D,some college,standard,completed,71,61,69,139
140,female,group D,some high school,standard,none,76,72,71,140
141,female,group C,some college,free/reduced,none,59,62,64,141
142,female,group E,some college,free/reduced,completed,42,55,54,142
143,male,group A,high school,standard,none,57,43,47,143
144,male,group D,some college,standard,none,88,73,78,144
145,female,group C,some college,free/reduced,none,22,39,33,145
146,male,group B,some high school,standard,none,88,84,75,146
147,male,group C,associate's degree,free/reduced,none,73,68,66,147
148,female,group D,bachelor's degree,standard,completed,68,75,81,148
149,male,group E,associate's degree,free/reduced,completed,100,100,93,149
150,male,group A,some high school,standard,completed,62,67,69,150
151,male,group A,bachelor's degree,standard,none,77,67,68,151
152,female,group B,associate's degree,standard,completed,59,70,66,152
153,male,group D,bachelor's degree,standard,none,54,49,47,153
154,male,group D,some high school,standard,none,62,67,61,154
155,female,group C,some college,standard,completed,70,89,88,155
156,female,group E,high school,free/reduced,completed,66,74,78,156
157,male,group B,some college,free/reduced,none,60,60,60,157
158,female,group B,associate's degree,standard,completed,61,86,87,158
159,male,group D,associate's degree,free/reduced,none,66,62,64,159
160,male,group B,associate's degree,free/reduced,completed,82,78,74,160
161,female,group E,some college,free/reduced,completed,75,88,85,161
162,male,group B,master's degree,free/reduced,none,49,53,52,162
163,male,group C,high school,standard,none,52,53,49,163
164,female,group E,master's degree,standard,none,81,92,91,164
165,female,group C,bachelor's degree,standard,completed,96,100,100,165
166,male,group C,high school,free/reduced,completed,53,51,51,166
167,female,group B,master's degree,free/reduced,completed,58,76,78,167
168,female,group B,high school,standard,completed,68,83,78,168
169,female,group C,some college,free/reduced,completed,67,75,70,169
170,male,group A,high school,standard,completed,72,73,74,170
171,male,group E,some high school,standard,none,94,88,78,171
172,female,group D,some college,standard,none,79,86,81,172
173,female,group C,associate's degree,standard,none,63,67,70,173
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54,174
175,female,group C,master's degree,standard,completed,81,91,87,175
176,female,group B,high school,free/reduced,completed,46,54,58,176
177,female,group C,associate's degree,standard,completed,71,77,77,177
178,female,group B,master's degree,free/reduced,completed,52,70,62,178
179,female,group D,some high school,standard,completed,97,100,100,179
180,male,group C,master's degree,free/reduced,completed,62,68,75,180
181,female,group C,some college,free/reduced,none,46,64,66,181
182,female,group E,high school,standard,none,50,50,47,182
183,female,group D,associate's degree,standard,none,65,69,70,183
184,male,group C,some high school,free/reduced,completed,45,52,49,184
185,male,group C,associate's degree,free/reduced,completed,65,67,65,185
186,male,group E,high school,standard,none,80,76,65,186
187,male,group D,some high school,standard,completed,62,66,68,187
188,male,group B,some high school,free/reduced,none,48,52,45,188
189,female,group C,bachelor's degree,standard,none,77,88,87,189
190,female,group E,associate's degree,standard,none,66,65,69,190
191,male,group D,some college,standard,completed,76,83,79,191
192,female,group B,some high school,standard,none,62,64,66,192
193,male,group D,some college,standard,completed,77,62,62,193
194,female,group C,master's degree,standard,completed,69,84,85,194
195,male,group D,associate's degree,standard,none,61,55,52,195
196,male,group C,some high school,free/reduced,completed,59,69,65,196
197,male,group E,high school,free/reduced,none,55,56,51,197
198,female,group B,some college,free/reduced,none,45,53,55,198
199,female,group B,bachelor's degree,free/reduced,none,78,79,76,199
200,female,group C,associate's degree,standard,completed,67,84,86,200
201,female,group D,some college,free/reduced,none,65,81,77,201
202,male,group C,associate's degree,standard,none,69,77,69,202
203,female,group B,associate's degree,standard,none,57,69,68,203
204,male,group C,some college,standard,none,59,41,42,204
205,male,group D,some high school,standard,completed,74,71,78,205
206,male,group E,bachelor's degree,standard,none,82,62,62,206
207,male,group E,high school,standard,completed,81,80,76,207
208,female,group B,some college,free/reduced,none,74,81,76,208
209,female,group B,some college,free/reduced,none,58,61,66,209
210,male,group D,some high school,free/reduced,completed,80,79,79,210
211,male,group C,some college,free/reduced,none,35,28,27,211
212,female,group C,high school,free/reduced,none,42,62,60,212
213,male,group C,associate's degree,free/reduced,completed,60,51,56,213
214,male,group E,high school,standard,completed,87,91,81,214
215,male,group B,some high school,standard,completed,84,83,75,215
216,female,group E,associate's degree,free/reduced,completed,83,86,88,216
217,female,group C,high school,free/reduced,none,34,42,39,217
218,male,group B,high school,free/reduced,none,66,77,70,218
219,male,group B,some high school,standard,completed,61,56,56,219
220,female,group D,high school,standard,completed,56,68,74,220
221,male,group B,associate's degree,standard,none,87,85,73,221
222,female,group C,some high school,free/reduced,none,55,65,62,222
223,male,group D,some high school,standard,none,86,80,75,223
224,female,group B,associate's degree,standard,completed,52,66,73,224
225,female,group E,master's degree,free/reduced,none,45,56,54,225
226,female,group C,some college,standard,none,72,72,71,226
227,male,group D,high school,standard,none,57,50,54,227
228,male,group A,some high school,free/reduced,none,68,72,64,228
229,female,group C,some college,standard,completed,88,95,94,229
230,male,group D,some college,standard,none,76,64,66,230
231,male,group C,associate's degree,standard,none,46,43,42,231
232,female,group B,bachelor's degree,standard,none,67,86,83,232
233,male,group E,some high school,standard,none,92,87,78,233
234,male,group C,bachelor's degree,standard,completed,83,82,84,234
235,male,group D,associate's degree,standard,none,80,75,77,235
236,male,group D,bachelor's degree,free/reduced,none,63,66,67,236
237,female,group D,some high school,standard,completed,64,60,74,237
238,male,group B,some college,standard,none,54,52,51,238
239,male,group C,associate's degree,standard,none,84,80,80,239
240,male,group D,high school,free/reduced,completed,73,68,66,240
241,female,group E,bachelor's degree,standard,none,80,83,83,241
242,female,group D,high school,standard,none,56,52,55,242
243,male,group E,some college,standard,none,59,51,43,243
244,male,group D,some high school,standard,none,75,74,69,244
245,male,group C,associate's degree,standard,none,85,76,71,245
246,male,group E,associate's degree,standard,none,89,76,74,246
247,female,group B,high school,standard,completed,58,70,68,247
248,female,group B,high school,standard,none,65,64,62,248
249,male,group C,high school,standard,none,68,60,53,249
250,male,group A,some high school,standard,completed,47,49,49,250
251,female,group D,some college,free/reduced,none,71,83,83,251
252,female,group B,some high school,standard,completed,60,70,70,252
253,male,group D,master's degree,standard,none,80,80,72,253
254,male,group D,high school,standard,none,54,52,52,254
255,female,group E,some college,standard,none,62,73,70,255
256,female,group C,associate's degree,free/reduced,none,64,73,68,256
257,male,group C,associate's degree,standard,completed,78,77,77,257
258,female,group B,some college,standard,none,70,75,78,258
259,female,group C,master's degree,free/reduced,completed,65,81,81,259
260,female,group C,some high school,free/reduced,completed,64,79,77,260
261,male,group C,some college,standard,completed,79,79,78,261
262,female,group C,some high school,free/reduced,none,44,50,51,262
263,female,group E,high school,standard,none,99,93,90,263
264,male,group D,high school,standard,none,76,73,68,264
265,male,group D,some high school,free/reduced,none,59,42,41,265
266,female,group C,bachelor's degree,standard,none,63,75,81,266
267,female,group D,high school,standard,none,69,72,77,267
268,female,group D,associate's degree,standard,completed,88,92,95,268
269,female,group E,some college,free/reduced,none,71,76,70,269
270,male,group C,bachelor's degree,standard,none,69,63,61,270
271,male,group C,some college,standard,none,58,49,42,271
272,female,group D,associate's degree,free/reduced,none,47,53,58,272
273,female,group D,some college,standard,none,65,70,71,273
274,male,group B,some college,standard,completed,88,85,76,274
275,male,group C,bachelor's degree,standard,none,83,78,73,275
276,female,group C,some high school,standard,completed,85,92,93,276
277,female,group E,high school,standard,completed,59,63,75,277
278,female,group C,some high school,free/reduced,none,65,86,80,278
279,male,group B,bachelor's degree,free/reduced,none,73,56,57,279
280,male,group D,high school,standard,none,53,52,42,280
281,male,group D,high school,standard,none,45,48,46,281
282,female,group D,bachelor's degree,free/reduced,none,73,79,84,282
283,female,group D,some college,free/reduced,completed,70,78,78,283
284,female,group B,some high school,standard,none,37,46,46,284
285,male,group B,associate's degree,standard,completed,81,82,82,285
286,male,group E,associate's degree,standard,completed,97,82,88,286
287,female,group B,some high school,standard,none,67,89,82,287
288,male,group B,bachelor's degree,free/reduced,none,88,75,76,288
289,male,group E,some high school,standard,completed,77,76,77,289
290,male,group C,associate's degree,standard,none,76,70,68,290
291,male,group D,some high school,standard,none,86,73,70,291
292,male,group C,some high school,standard,completed,63,60,57,292
293,female,group E,bachelor's degree,standard,none,65,73,75,293
294,male,group D,high school,free/reduced,completed,78,77,80,294
295,male,group B,associate's degree,free/reduced,none,67,62,60,295
296,male,group A,some high school,standard,completed,46,41,43,296
297,male,group E,associate's degree,standard,completed,71,74,68,297
298,male,group C,high school,free/reduced,completed,40,46,50,298
299,male,group D,associate's degree,free/reduced,none,90,87,75,299
300,male,group A,some college,free/reduced,completed,81,78,81,300
301,male,group D,some high school,free/reduced,none,56,54,52,301
302,female,group C,associate's degree,standard,completed,67,84,81,302
303,male,group B,associate's degree,standard,none,80,76,64,303
304,female,group C,associate's degree,standard,completed,74,75,83,304
305,male,group A,some college,standard,none,69,67,69,305
306,male,group E,some college,standard,completed,99,87,81,306
307,male,group C,some high school,standard,none,51,52,44,307
308,female,group B,associate's degree,free/reduced,none,53,71,67,308
309,female,group D,high school,free/reduced,none,49,57,52,309
310,female,group B,associate's degree,standard,none,73,76,80,310
311,male,group B,bachelor's degree,standard,none,66,60,57,311
312,male,group D,bachelor's degree,standard,completed,67,61,68,312

In [52]:
# create random integer numbers between 1 and 100
int_language_score = np.random.randint(1, 100, size=1000)

In [53]:
# min value is inclusive and high value excusive
min(int_language_score)
max(int_language_score)

99

In [54]:
# adding a new column to dataframe with an array
df_exams['language score'] = int_language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,20
1,female,group C,some college,standard,completed,69,90,88,30
2,female,group B,master's degree,standard,none,90,95,93,15
3,male,group A,associate's degree,free/reduced,none,47,57,44,96
4,male,group C,some college,standard,none,76,78,75,40
5,female,group B,associate's degree,standard,none,71,83,78,8
6,female,group B,some college,standard,completed,88,95,92,94
7,male,group B,some college,free/reduced,none,40,43,39,98
8,male,group D,high school,free/reduced,completed,64,64,67,2
9,female,group B,high school,free/reduced,none,38,60,50,1
10,male,group C,associate's degree,standard,none,58,54,52,8
11,male,group D,associate's degree,standard,none,40,52,43,8
12,female,group B,high school,standard,none,65,81,73,31
13,male,group A,some college,standard,completed,78,72,70,97
14,female,group A,master's degree,standard,none,50,53,58,90
15,female,group C,some high school,standard,none,69,75,78,21
16,male,group C,high school,standard,none,88,89,86,40
17,female,group B,some high school,free/reduced,none,18,32,28,82
18,male,group C,master's degree,free/reduced,completed,46,42,46,40
19,female,group C,associate's degree,free/reduced,none,54,58,61,67
20,male,group D,high school,standard,none,66,69,63,48
21,female,group B,some college,free/reduced,completed,65,75,70,98
22,male,group D,some college,standard,none,44,54,53,23
23,female,group C,some high school,standard,none,69,73,73,5
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80,87
25,male,group A,master's degree,free/reduced,none,73,74,72,74
26,male,group B,some college,standard,none,69,54,55,81
27,female,group C,bachelor's degree,standard,none,67,69,75,94
28,male,group C,high school,standard,none,70,70,65,78
29,female,group D,master's degree,standard,none,62,70,75,31
30,female,group D,some college,standard,none,69,74,74,26
31,female,group B,some college,standard,none,63,65,61,71
32,female,group E,master's degree,free/reduced,none,56,72,65,44
33,male,group D,some college,standard,none,40,42,38,78
34,male,group E,some college,standard,none,97,87,82,12
35,male,group E,associate's degree,standard,completed,81,81,79,89
36,female,group D,associate's degree,standard,none,74,81,83,84
37,female,group D,some high school,free/reduced,none,50,64,59,36
38,female,group D,associate's degree,free/reduced,completed,75,90,88,78
39,male,group B,associate's degree,free/reduced,none,57,56,57,91
40,male,group C,associate's degree,free/reduced,none,55,61,54,45
41,female,group C,associate's degree,standard,none,58,73,68,58
42,female,group B,associate's degree,standard,none,53,58,65,42
43,male,group B,some college,free/reduced,completed,59,65,66,80
44,female,group E,associate's degree,free/reduced,none,50,56,54,96
45,male,group B,associate's degree,standard,none,65,54,57,17
46,female,group A,associate's degree,standard,completed,55,65,62,87
47,female,group C,high school,standard,none,66,71,76,85
48,female,group D,associate's degree,free/reduced,completed,57,74,76,98
49,male,group C,high school,standard,completed,82,84,82,7
50,male,group E,some college,standard,none,53,55,48,98
51,male,group E,associate's degree,free/reduced,completed,77,69,68,72
52,male,group C,some college,standard,none,53,44,42,71
53,male,group D,high school,standard,none,88,78,75,83
54,female,group C,some high school,free/reduced,completed,71,84,87,17
55,female,group C,high school,free/reduced,none,33,41,43,18
56,female,group E,associate's degree,standard,completed,82,85,86,35
57,male,group D,associate's degree,standard,none,52,55,49,19
58,male,group D,some college,standard,completed,58,59,58,87
59,female,group C,some high school,free/reduced,none,0,17,10,28
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72,52
61,male,group A,some high school,free/reduced,none,39,39,34,10
62,male,group A,associate's degree,free/reduced,none,62,61,55,21
63,female,group C,associate's degree,standard,none,69,80,71,73
64,female,group D,some high school,standard,none,59,58,59,43
65,male,group B,some high school,standard,none,67,64,61,84
66,male,group D,some high school,free/reduced,none,45,37,37,93
67,female,group C,some college,standard,none,60,72,74,7
68,male,group B,associate's degree,free/reduced,none,61,58,56,23
69,female,group C,associate's degree,standard,none,39,64,57,24
70,female,group D,some college,free/reduced,completed,58,63,73,91
71,male,group D,some college,standard,completed,63,55,63,68
72,female,group A,associate's degree,free/reduced,none,41,51,48,14
73,male,group C,some high school,free/reduced,none,61,57,56,47
74,male,group C,some high school,standard,none,49,49,41,43
75,male,group B,associate's degree,free/reduced,none,44,41,38,82
76,male,group E,some high school,standard,none,30,26,22,71
77,male,group A,bachelor's degree,standard,completed,80,78,81,66
78,female,group D,some high school,standard,completed,61,74,72,72
79,female,group E,master's degree,standard,none,62,68,68,98
80,female,group B,associate's degree,standard,none,47,49,50,17
81,male,group B,high school,free/reduced,none,49,45,45,68
82,male,group A,some college,free/reduced,completed,50,47,54,64
83,male,group E,associate's degree,standard,none,72,64,63,61
84,male,group D,high school,free/reduced,none,42,39,34,81
85,female,group C,some college,standard,none,73,80,82,15
86,female,group C,some college,free/reduced,none,76,83,88,34
87,female,group D,associate's degree,standard,none,71,71,74,64
88,female,group A,some college,standard,none,58,70,67,80
89,female,group D,some high school,standard,none,73,86,82,27
90,female,group C,bachelor's degree,standard,none,65,72,74,64
91,male,group C,high school,free/reduced,none,27,34,36,70
92,male,group C,high school,standard,none,71,79,71,33
93,male,group C,associate's degree,free/reduced,completed,43,45,50,9
94,female,group B,some college,standard,none,79,86,92,49
95,male,group C,associate's degree,free/reduced,completed,78,81,82,51
96,male,group B,some high school,standard,completed,65,66,62,27
97,female,group E,some college,standard,completed,63,72,70,69
98,female,group D,some college,free/reduced,none,58,67,62,95
99,female,group D,bachelor's degree,standard,none,65,67,62,30
100,male,group B,some college,standard,none,79,67,67,50
101,male,group D,bachelor's degree,standard,completed,68,74,74,25
102,female,group D,associate's degree,standard,none,85,91,89,85
103,male,group B,high school,standard,completed,60,44,47,69
104,male,group C,some college,standard,completed,98,86,90,34
105,female,group C,some college,standard,none,58,67,72,38
106,female,group D,master's degree,standard,none,87,100,100,12
107,male,group E,associate's degree,standard,completed,66,63,64,25
108,female,group B,associate's degree,free/reduced,none,52,76,70,36
109,female,group B,some high school,standard,none,70,64,72,82
110,female,group D,associate's degree,free/reduced,completed,77,89,98,69
111,male,group C,high school,standard,none,62,55,49,87
112,male,group A,associate's degree,standard,none,54,53,47,30
113,female,group D,some college,standard,none,51,58,54,6
114,female,group E,bachelor's degree,standard,completed,99,100,100,7
115,male,group C,high school,standard,none,84,77,74,57
116,female,group B,bachelor's degree,free/reduced,none,75,85,82,63
117,female,group D,bachelor's degree,standard,none,78,82,79,51
118,female,group D,some high school,standard,none,51,63,61,88
119,female,group C,some college,standard,none,55,69,65,47
120,female,group C,bachelor's degree,standard,completed,79,92,89,69
121,male,group B,associate's degree,standard,completed,91,89,92,91
122,female,group C,some college,standard,completed,88,93,93,79
123,male,group D,high school,free/reduced,none,63,57,56,23
124,male,group E,some college,standard,none,83,80,73,32
125,female,group B,high school,standard,none,87,95,86,10
126,male,group B,some high school,standard,none,72,68,67,84
127,male,group D,some college,standard,completed,65,77,74,81
128,male,group D,master's degree,standard,none,82,82,74,73
129,female,group A,bachelor's degree,standard,none,51,49,51,78
130,male,group D,master's degree,standard,none,89,84,82,53
131,male,group C,some high school,free/reduced,completed,53,37,40,97
132,male,group E,some college,free/reduced,completed,87,74,70,16
133,female,group C,some college,standard,completed,75,81,84,55
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75,38
135,male,group C,bachelor's degree,standard,none,58,55,48,22
136,male,group B,some high school,standard,completed,51,54,41,46
137,male,group E,high school,standard,none,70,55,56,52
138,female,group C,associate's degree,standard,none,59,66,67,14
139,male,group D,some college,standard,completed,71,61,69,58
140,female,group D,some high school,standard,none,76,72,71,13
141,female,group C,some college,free/reduced,none,59,62,64,48
142,female,group E,some college,free/reduced,completed,42,55,54,26
143,male,group A,high school,standard,none,57,43,47,47
144,male,group D,some college,standard,none,88,73,78,91
145,female,group C,some college,free/reduced,none,22,39,33,63
146,male,group B,some high school,standard,none,88,84,75,26
147,male,group C,associate's degree,free/reduced,none,73,68,66,17
148,female,group D,bachelor's degree,standard,completed,68,75,81,71
149,male,group E,associate's degree,free/reduced,completed,100,100,93,63
150,male,group A,some high school,standard,completed,62,67,69,77
151,male,group A,bachelor's degree,standard,none,77,67,68,74
152,female,group B,associate's degree,standard,completed,59,70,66,13
153,male,group D,bachelor's degree,standard,none,54,49,47,98
154,male,group D,some high school,standard,none,62,67,61,32
155,female,group C,some college,standard,completed,70,89,88,54
156,female,group E,high school,free/reduced,completed,66,74,78,25
157,male,group B,some college,free/reduced,none,60,60,60,88
158,female,group B,associate's degree,standard,completed,61,86,87,97
159,male,group D,associate's degree,free/reduced,none,66,62,64,19
160,male,group B,associate's degree,free/reduced,completed,82,78,74,53
161,female,group E,some college,free/reduced,completed,75,88,85,91
162,male,group B,master's degree,free/reduced,none,49,53,52,58
163,male,group C,high school,standard,none,52,53,49,20
164,female,group E,master's degree,standard,none,81,92,91,53
165,female,group C,bachelor's degree,standard,completed,96,100,100,72
166,male,group C,high school,free/reduced,completed,53,51,51,83
167,female,group B,master's degree,free/reduced,completed,58,76,78,99
168,female,group B,high school,standard,completed,68,83,78,39
169,female,group C,some college,free/reduced,completed,67,75,70,20
170,male,group A,high school,standard,completed,72,73,74,32
171,male,group E,some high school,standard,none,94,88,78,3
172,female,group D,some college,standard,none,79,86,81,7
173,female,group C,associate's degree,standard,none,63,67,70,19
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54,6
175,female,group C,master's degree,standard,completed,81,91,87,50
176,female,group B,high school,free/reduced,completed,46,54,58,97
177,female,group C,associate's degree,standard,completed,71,77,77,33
178,female,group B,master's degree,free/reduced,completed,52,70,62,82
179,female,group D,some high school,standard,completed,97,100,100,63
180,male,group C,master's degree,free/reduced,completed,62,68,75,48
181,female,group C,some college,free/reduced,none,46,64,66,72
182,female,group E,high school,standard,none,50,50,47,90
183,female,group D,associate's degree,standard,none,65,69,70,47
184,male,group C,some high school,free/reduced,completed,45,52,49,67
185,male,group C,associate's degree,free/reduced,completed,65,67,65,21
186,male,group E,high school,standard,none,80,76,65,93
187,male,group D,some high school,standard,completed,62,66,68,98
188,male,group B,some high school,free/reduced,none,48,52,45,1
189,female,group C,bachelor's degree,standard,none,77,88,87,26
190,female,group E,associate's degree,standard,none,66,65,69,14
191,male,group D,some college,standard,completed,76,83,79,25
192,female,group B,some high school,standard,none,62,64,66,2
193,male,group D,some college,standard,completed,77,62,62,51
194,female,group C,master's degree,standard,completed,69,84,85,99
195,male,group D,associate's degree,standard,none,61,55,52,39
196,male,group C,some high school,free/reduced,completed,59,69,65,38
197,male,group E,high school,free/reduced,none,55,56,51,33
198,female,group B,some college,free/reduced,none,45,53,55,42
199,female,group B,bachelor's degree,free/reduced,none,78,79,76,24
200,female,group C,associate's degree,standard,completed,67,84,86,74
201,female,group D,some college,free/reduced,none,65,81,77,86
202,male,group C,associate's degree,standard,none,69,77,69,15
203,female,group B,associate's degree,standard,none,57,69,68,88
204,male,group C,some college,standard,none,59,41,42,45
205,male,group D,some high school,standard,completed,74,71,78,35
206,male,group E,bachelor's degree,standard,none,82,62,62,39
207,male,group E,high school,standard,completed,81,80,76,26
208,female,group B,some college,free/reduced,none,74,81,76,45
209,female,group B,some college,free/reduced,none,58,61,66,11
210,male,group D,some high school,free/reduced,completed,80,79,79,79
211,male,group C,some college,free/reduced,none,35,28,27,12
212,female,group C,high school,free/reduced,none,42,62,60,25
213,male,group C,associate's degree,free/reduced,completed,60,51,56,29
214,male,group E,high school,standard,completed,87,91,81,94
215,male,group B,some high school,standard,completed,84,83,75,51
216,female,group E,associate's degree,free/reduced,completed,83,86,88,24
217,female,group C,high school,free/reduced,none,34,42,39,71
218,male,group B,high school,free/reduced,none,66,77,70,42
219,male,group B,some high school,standard,completed,61,56,56,14
220,female,group D,high school,standard,completed,56,68,74,14
221,male,group B,associate's degree,standard,none,87,85,73,12
222,female,group C,some high school,free/reduced,none,55,65,62,15
223,male,group D,some high school,standard,none,86,80,75,38
224,female,group B,associate's degree,standard,completed,52,66,73,3
225,female,group E,master's degree,free/reduced,none,45,56,54,39
226,female,group C,some college,standard,none,72,72,71,59
227,male,group D,high school,standard,none,57,50,54,73
228,male,group A,some high school,free/reduced,none,68,72,64,49
229,female,group C,some college,standard,completed,88,95,94,1
230,male,group D,some college,standard,none,76,64,66,61
231,male,group C,associate's degree,standard,none,46,43,42,28
232,female,group B,bachelor's degree,standard,none,67,86,83,71
233,male,group E,some high school,standard,none,92,87,78,37
234,male,group C,bachelor's degree,standard,completed,83,82,84,58
235,male,group D,associate's degree,standard,none,80,75,77,47
236,male,group D,bachelor's degree,free/reduced,none,63,66,67,84
237,female,group D,some high school,standard,completed,64,60,74,73
238,male,group B,some college,standard,none,54,52,51,10
239,male,group C,associate's degree,standard,none,84,80,80,30
240,male,group D,high school,free/reduced,completed,73,68,66,53
241,female,group E,bachelor's degree,standard,none,80,83,83,83
242,female,group D,high school,standard,none,56,52,55,9
243,male,group E,some college,standard,none,59,51,43,67
244,male,group D,some high school,standard,none,75,74,69,2
245,male,group C,associate's degree,standard,none,85,76,71,52
246,male,group E,associate's degree,standard,none,89,76,74,86
247,female,group B,high school,standard,completed,58,70,68,51
248,female,group B,high school,standard,none,65,64,62,15
249,male,group C,high school,standard,none,68,60,53,4
250,male,group A,some high school,standard,completed,47,49,49,26
251,female,group D,some college,free/reduced,none,71,83,83,97
252,female,group B,some high school,standard,completed,60,70,70,35
253,male,group D,master's degree,standard,none,80,80,72,7
254,male,group D,high school,standard,none,54,52,52,88
255,female,group E,some college,standard,none,62,73,70,96
256,female,group C,associate's degree,free/reduced,none,64,73,68,98
257,male,group C,associate's degree,standard,completed,78,77,77,58
258,female,group B,some college,standard,none,70,75,78,44
259,female,group C,master's degree,free/reduced,completed,65,81,81,43
260,female,group C,some high school,free/reduced,completed,64,79,77,35
261,male,group C,some college,standard,completed,79,79,78,96
262,female,group C,some high school,free/reduced,none,44,50,51,27
263,female,group E,high school,standard,none,99,93,90,91
264,male,group D,high school,standard,none,76,73,68,15
265,male,group D,some high school,free/reduced,none,59,42,41,86
266,female,group C,bachelor's degree,standard,none,63,75,81,12
267,female,group D,high school,standard,none,69,72,77,38
268,female,group D,associate's degree,standard,completed,88,92,95,71
269,female,group E,some college,free/reduced,none,71,76,70,75
270,male,group C,bachelor's degree,standard,none,69,63,61,10
271,male,group C,some college,standard,none,58,49,42,96
272,female,group D,associate's degree,free/reduced,none,47,53,58,66
273,female,group D,some college,standard,none,65,70,71,81
274,male,group B,some college,standard,completed,88,85,76,67
275,male,group C,bachelor's degree,standard,none,83,78,73,99
276,female,group C,some high school,standard,completed,85,92,93,53
277,female,group E,high school,standard,completed,59,63,75,67
278,female,group C,some high school,free/reduced,none,65,86,80,99
279,male,group B,bachelor's degree,free/reduced,none,73,56,57,36
280,male,group D,high school,standard,none,53,52,42,40
281,male,group D,high school,standard,none,45,48,46,56
282,female,group D,bachelor's degree,free/reduced,none,73,79,84,20
283,female,group D,some college,free/reduced,completed,70,78,78,7
284,female,group B,some high school,standard,none,37,46,46,8
285,male,group B,associate's degree,standard,completed,81,82,82,62
286,male,group E,associate's degree,standard,completed,97,82,88,45
287,female,group B,some high school,standard,none,67,89,82,62
288,male,group B,bachelor's degree,free/reduced,none,88,75,76,92
289,male,group E,some high school,standard,completed,77,76,77,27
290,male,group C,associate's degree,standard,none,76,70,68,77
291,male,group D,some high school,standard,none,86,73,70,91
292,male,group C,some high school,standard,completed,63,60,57,16
293,female,group E,bachelor's degree,standard,none,65,73,75,56
294,male,group D,high school,free/reduced,completed,78,77,80,61
295,male,group B,associate's degree,free/reduced,none,67,62,60,56
296,male,group A,some high school,standard,completed,46,41,43,68
297,male,group E,associate's degree,standard,completed,71,74,68,64
298,male,group C,high school,free/reduced,completed,40,46,50,4
299,male,group D,associate's degree,free/reduced,none,90,87,75,38
300,male,group A,some college,free/reduced,completed,81,78,81,70
301,male,group D,some high school,free/reduced,none,56,54,52,91
302,female,group C,associate's degree,standard,completed,67,84,81,24
303,male,group B,associate's degree,standard,none,80,76,64,72
304,female,group C,associate's degree,standard,completed,74,75,83,19
305,male,group A,some college,standard,none,69,67,69,68
306,male,group E,some college,standard,completed,99,87,81,46
307,male,group C,some high school,standard,none,51,52,44,64
308,female,group B,associate's degree,free/reduced,none,53,71,67,5
309,female,group D,high school,free/reduced,none,49,57,52,85
310,female,group B,associate's degree,standard,none,73,76,80,55
311,male,group B,bachelor's degree,standard,none,66,60,57,11
312,male,group D,bachelor's degree,standard,completed,67,61,68,66
313,female,group C,associate's degree,free/reduced,completed,68,67,69,45
314,female,group C,bachelor's degree,standard,completed,59,64,75,57
315,male,group C,high school,standard,none,71,66,65,71
316,female,group D,master's degree,standard,completed,77,82,91,57

In [55]:
# create random float numbers between 1 and 100
np.random.uniform(1,100, size = 100)

array([38.2531107 , 35.73668668,  9.96825917, 15.86361616, 83.41260694,
       96.26648659,  8.87381907, 87.2904004 , 49.91538882, 56.65017906,
       64.69507994, 81.65322039, 38.18955836, 34.00677066, 94.92218675,
       71.72475233, 92.14271945, 82.41346208, 67.76136322, 43.65575441,
       44.52875748, 62.60841302, 62.54061225, 31.62994924,  8.48003068,
       67.36995098, 55.25083881, 19.94384346, 61.38032846, 14.50565107,
       86.22168631, 60.11258578, 55.12881793, 89.14686127, 27.24299232,
       89.89423094, 73.68307183, 16.06820274, 87.70375551, 59.66642759,
       26.3360289 , 38.2374506 , 94.89767334, 15.38289778, 87.22869037,
        3.79228404, 24.33710358, 48.38884326, 82.41515535, 97.17987881,
       62.21257998, 45.93784993, 81.72789869, 17.51017421, 37.838068  ,
       13.63688855, 42.4697047 , 89.23989997, 62.23557559, 83.02441138,
        1.97092022, 64.61277825, 22.32970524, 18.01959945, 69.75748603,
       59.29837358, 63.39753707, 53.63932061, 83.59075531, 63.18784022,
       49.31340492, 59.86202772, 17.77354648, 52.74661053, 27.54709138,
        2.28170281, 61.91736048, 47.26068271,  4.55124517, 34.68164124,
       63.59852387, 86.56662014, 60.04429519, 20.16742501, 70.51817241,
       77.65111806, 68.39583885, 60.69181066, 84.79081684, 73.43788064,
       13.62383606, 40.07491454,  9.50609094, 78.32310988, 57.23138245,
       89.62520177, 42.34539251, 85.18470136, 17.58620308, 23.25590237])

# 3.Adding a new column

## 3.2 assign()

### When to use assign?
- Add multiple columns in a single line of code
- When you need to overwrite the values of an existing columns(best practice)

### It returns a new object (a copy) with all the original columns in additional to the new ones

In [56]:
import numpy as np

In [57]:
# Create random numbers for our new score columns
score1 = np.random.randint(1, 100, size=1000)
score2 = np.random.randint(1, 100, size=1000)

In [58]:
score1

array([95, 15, 62, 80, 62, 86, 32, 94, 56, 92,  9, 36, 10, 93,  4, 33, 67,
       31, 89, 31, 69, 30,  1, 85, 90, 31, 99, 68, 71, 25, 44, 45, 13, 39,
       89,  6,  8, 24, 63, 90,  5, 23, 17, 27,  6, 80, 53, 72, 16, 34, 66,
       60, 31, 48, 58, 50, 81, 75, 88, 79, 57, 75,  8, 92,  7, 88, 58, 71,
       85, 30, 32, 83, 37, 78, 69, 42, 20, 35, 71, 70, 18, 70, 10, 20, 89,
       22, 50, 33, 39,  5, 91, 13, 25, 36, 25, 72, 84, 11, 89, 61, 18, 10,
       22, 66, 78, 51, 71, 67, 45, 43, 30, 14, 78, 27, 68, 57, 18, 80, 88,
       68, 48, 98, 20, 24, 21, 30,  2, 57, 15, 98, 99,  4, 67, 80, 51, 36,
       33, 59, 58, 60, 11, 49, 62,  3, 16, 58, 13, 57, 70,  2, 74, 75, 78,
       90, 40, 44, 42, 89, 39, 97, 41, 62, 11, 46, 52, 85, 13, 21,  4, 63,
       61, 54, 10, 51, 40,  1, 28, 39, 76, 10, 62, 24, 86, 68, 39, 62, 64,
       89, 41, 76, 41, 35, 70, 78, 23, 17, 82, 20, 59, 68, 18, 83, 20, 52,
       73, 21, 77, 65, 43, 32, 74, 81, 45, 93, 28, 50, 71, 39, 97, 78, 81,
       76, 95, 50, 35, 29, 31, 54,  1, 91, 64, 60, 93, 63, 85,  7, 67, 25,
        2, 73, 41, 10, 30, 71, 13, 21, 77, 99, 96, 22, 97, 37, 24,  5, 14,
       67, 30, 59, 35, 24, 81, 74, 62,  2, 18, 92, 93, 18, 30,  4, 75, 72,
       32, 75, 39, 75, 92, 36, 14, 65, 25, 42, 31, 44, 49, 58, 13, 57, 15,
       47, 94, 10, 67, 47,  9, 57, 64, 46, 59, 10, 26, 88, 54, 38,  3, 19,
       27, 85, 11, 76,  9, 60, 15, 41, 90, 24, 41, 91,  8, 29, 10, 91, 11,
       30, 30, 20,  4, 18, 51, 30, 82, 69, 11, 58, 66, 87, 86, 39, 55, 42,
       78, 84, 81, 56, 45, 81, 71, 38,  4, 94, 17, 40, 81, 99, 81, 20, 74,
       26, 31,  7, 65, 18,  5, 48, 91, 43, 44, 95, 90, 10, 84, 26, 18, 48,
       88, 10,  7, 25, 42, 97, 15, 17, 67, 85, 55,  1, 89, 88, 49, 38, 72,
       91, 33, 18, 78, 99, 84, 43, 34, 99, 13, 58, 66, 77, 76, 51, 70,  4,
       83, 64, 22, 13, 59, 82, 83, 21,  7, 36, 82, 47,  9, 82, 66, 80, 52,
       87, 50, 59, 83, 81, 14, 17, 37, 48, 21, 70, 62, 78, 82, 49, 33, 11,
       71, 23, 19, 89, 96, 94, 81, 48, 14,  6,  4, 73, 18, 79, 73, 77, 30,
       93, 39, 17, 74, 36, 83, 90, 71, 78, 29, 89, 62, 28, 58, 95, 11, 56,
       42, 96, 89, 34, 38, 11,  2, 84, 17, 95, 99, 23, 41, 67,  7, 74, 59,
       91, 40, 61, 11, 26, 39, 34, 97, 94, 40, 39, 66, 50, 52, 58, 87, 12,
       21, 46, 56, 53, 36, 34, 63, 60, 86, 83, 26, 86, 93, 87, 29, 93, 82,
       73, 89, 25, 66, 58, 73, 64, 39, 17, 71,  3,  9,  2, 82, 72, 17, 47,
       59, 68, 68, 52, 95, 77, 97, 40, 71, 35, 16, 77, 95, 33, 99,  7, 21,
       44, 22, 12, 33, 73, 66, 17, 33, 94, 75,  9, 23, 24, 91, 30, 12, 23,
       91, 27, 89, 10, 99, 93, 94,  8,  4, 87,  1, 90, 62, 46, 82,  1,  5,
       96, 23, 31, 19, 37, 57, 36, 29, 82, 92, 21, 17,  5, 74, 38, 43, 16,
       60, 26, 10, 73, 69, 15,  8, 19, 20, 37, 20, 84, 24, 48, 11, 43,  7,
       59, 38, 37,  7, 61, 19, 67, 46, 70,  9, 23, 71, 96, 30, 95, 93, 15,
        2, 23, 50, 25, 26, 12, 20, 38, 45, 33, 97, 88, 32, 82, 71, 65,  5,
       18, 36, 43, 32, 11, 68, 65, 64, 21, 52, 77, 57, 38, 65, 89, 91, 46,
        7, 82,  4, 41,  9, 84, 42, 30, 52, 58, 34, 81,  9, 87, 35, 87, 57,
       13, 96, 26, 57, 23, 40, 84, 58, 77, 15, 31, 12, 14, 95, 95, 90, 70,
       34, 86, 95, 87, 79, 89, 78, 32, 95, 20, 61, 77, 96,  4, 22, 12, 39,
       88, 16, 52, 25, 92, 43, 43, 55, 74, 19, 16, 34, 27, 47, 42, 26, 38,
       90, 51, 28, 91, 39, 56, 63, 52, 22, 79, 72,  8, 84,  5, 85, 75, 36,
       41, 40, 60, 67, 62, 25, 19, 45,  6, 11, 87, 82, 45, 93, 85, 75, 84,
       94, 90, 35, 83, 33, 90, 35, 55, 34, 50, 98, 73, 10, 10, 49, 73, 76,
       34,  6,  9, 31, 90, 66, 89, 27, 56,  9,  1, 66, 31, 10, 62, 82, 40,
       17,  1, 95, 62, 66, 15, 90,  6, 50, 65, 28, 31, 13, 57, 84, 46, 44,
       17, 84, 78, 73,  6, 13, 47, 56,  9, 61,  4, 10, 81, 19,  5, 61, 55,
       12, 62, 68, 22, 66, 50, 92, 94, 59, 45, 42, 80, 91, 42, 89, 14, 69,
       27,  3, 77, 47, 46, 89, 14, 58, 51, 31, 51, 97, 20, 13, 18, 94, 27,
       52, 63, 99, 73,  9, 44, 14, 26, 54, 71, 80, 15, 99, 21, 57,  1, 57,
       46, 81,  9, 33, 85, 10, 87, 35, 32, 96, 33, 41, 84, 16, 13, 12, 87,
       28, 80, 51, 16, 66, 16,  8, 69, 53, 15, 13, 75, 25, 29, 82, 41,  2,
        4, 80, 47, 99, 43, 52, 22, 73,  1, 49, 86,  8,  6, 40, 99, 69, 61,
       69, 14, 34, 49, 18, 27, 89, 43, 40, 86, 49,  7, 22, 99, 19, 50, 95,
       61, 60,  1, 54, 60, 30, 69, 82, 51, 66, 99, 23, 44, 59, 80, 60, 96,
       61, 47, 95, 27, 86, 63, 10,  2, 77,  8, 66, 71, 83, 82])

In [59]:
# Create a series using the random numbers
series1 = pd.Series(score1, index=np.arange(0, 1000))
series2 = pd.Series(score2, index=np.arange(0, 1000))

In [60]:
series1

0      95
1      15
2      62
3      80
4      62
5      86
6      32
7      94
8      56
9      92
10      9
11     36
12     10
13     93
14      4
15     33
16     67
17     31
18     89
19     31
20     69
21     30
22      1
23     85
24     90
25     31
26     99
27     68
28     71
29     25
30     44
31     45
32     13
33     39
34     89
35      6
36      8
37     24
38     63
39     90
40      5
41     23
42     17
43     27
44      6
45     80
46     53
47     72
48     16
49     34
50     66
51     60
52     31
53     48
54     58
55     50
56     81
57     75
58     88
59     79
60     57
61     75
62      8
63     92
64      7
65     88
66     58
67     71
68     85
69     30
70     32
71     83
72     37
73     78
74     69
75     42
76     20
77     35
78     71
79     70
80     18
81     70
82     10
83     20
84     89
85     22
86     50
87     33
88     39
89      5
90     91
91     13
92     25
93     36
94     25
95     72
96     84
97     11
98     89
99     61
100    18
101    10
102    22
103    66
104    78
105    51
106    71
107    67
108    45
109    43
110    30
111    14
112    78
113    27
114    68
115    57
116    18
117    80
118    88
119    68
120    48
121    98
122    20
123    24
124    21
125    30
126     2
127    57
128    15
129    98
130    99
131     4
132    67
133    80
134    51
135    36
136    33
137    59
138    58
139    60
140    11
141    49
142    62
143     3
144    16
145    58
146    13
147    57
148    70
149     2
150    74
151    75
152    78
153    90
154    40
155    44
156    42
157    89
158    39
159    97
160    41
161    62
162    11
163    46
164    52
165    85
166    13
167    21
168     4
169    63
170    61
171    54
172    10
173    51
174    40
175     1
176    28
177    39
178    76
179    10
180    62
181    24
182    86
183    68
184    39
185    62
186    64
187    89
188    41
189    76
190    41
191    35
192    70
193    78
194    23
195    17
196    82
197    20
198    59
199    68
200    18
201    83
202    20
203    52
204    73
205    21
206    77
207    65
208    43
209    32
210    74
211    81
212    45
213    93
214    28
215    50
216    71
217    39
218    97
219    78
220    81
221    76
222    95
223    50
224    35
225    29
226    31
227    54
228     1
229    91
230    64
231    60
232    93
233    63
234    85
235     7
236    67
237    25
238     2
239    73
240    41
241    10
242    30
243    71
244    13
245    21
246    77
247    99
248    96
249    22
250    97
251    37
252    24
253     5
254    14
255    67
256    30
257    59
258    35
259    24
260    81
261    74
262    62
263     2
264    18
265    92
266    93
267    18
268    30
269     4
270    75
271    72
272    32
273    75
274    39
275    75
276    92
277    36
278    14
279    65
280    25
281    42
282    31
283    44
284    49
285    58
286    13
287    57
288    15
289    47
290    94
291    10
292    67
293    47
294     9
295    57
296    64
297    46
298    59
299    10
300    26
301    88
302    54
303    38
304     3
305    19
306    27
307    85
308    11
309    76
310     9
311    60
312    15
313    41
314    90
315    24
316    41
317    91
318     8
319    29
320    10
321    91
322    11
323    30
324    30
325    20
326     4
327    18
328    51
329    30
330    82
331    69
332    11
333    58
334    66
335    87
336    86
337    39
338    55
339    42
340    78
341    84
342    81
343    56
344    45
345    81
346    71
347    38
348     4
349    94
350    17
351    40
352    81
353    99
354    81
355    20
356    74
357    26
358    31
359     7
360    65
361    18
362     5
363    48
364    91
365    43
366    44
367    95
368    90
369    10
370    84
371    26
372    18
373    48
374    88
375    10
376     7
377    25
378    42
379    97
380    15
381    17
382    67
383    85
384    55
385     1
386    89
387    88
388    49
389    38
390    72
391    91
392    33
393    18
394    78
395    99
396    84
397    43
398    34
399    99
400    13
401    58
402    66
403    77
404    76
405    51
406    70
407     4
408    83
409    64
410    22
411    13
412    59
413    82
414    83
415    21
416     7
417    36
418    82
419    47
420     9
421    82
422    66
423    80
424    52
425    87
426    50
427    59
428    83
429    81
430    14
431    17
432    37
433    48
434    21
435    70
436    62
437    78
438    82
439    49
440    33
441    11
442    71
443    23
444    19
445    89
446    96
447    94
448    81
449    48
450    14
451     6
452     4
453    73
454    18
455    79
456    73
457    77
458    30
459    93
460    39
461    17
462    74
463    36
464    83
465    90
466    71
467    78
468    29
469    89
470    62
471    28
472    58
473    95
474    11
475    56
476    42
477    96
478    89
479    34
480    38
481    11
482     2
483    84
484    17
485    95
486    99
487    23
488    41
489    67
490     7
491    74
492    59
493    91
494    40
495    61
496    11
497    26
498    39
499    34
500    97
501    94
502    40
503    39
504    66
505    50
506    52
507    58
508    87
509    12
510    21
511    46
512    56
513    53
514    36
515    34
516    63
517    60
518    86
519    83
520    26
521    86
522    93
523    87
524    29
525    93
526    82
527    73
528    89
529    25
530    66
531    58
532    73
533    64
534    39
535    17
536    71
537     3
538     9
539     2
540    82
541    72
542    17
543    47
544    59
545    68
546    68
547    52
548    95
549    77
550    97
551    40
552    71
553    35
554    16
555    77
556    95
557    33
558    99
559     7
560    21
561    44
562    22
563    12
564    33
565    73
566    66
567    17
568    33
569    94
570    75
571     9
572    23
573    24
574    91
575    30
576    12
577    23
578    91
579    27
580    89
581    10
582    99
583    93
584    94
585     8
586     4
587    87
588     1
589    90
590    62
591    46
592    82
593     1
594     5
595    96
596    23
597    31
598    19
599    37
600    57
601    36
602    29
603    82
604    92
605    21
606    17
607     5
608    74
609    38
610    43
611    16
612    60
613    26
614    10
615    73
616    69
617    15
618     8
619    19
620    20
621    37
622    20
623    84
624    24
625    48
626    11
627    43
628     7
629    59
630    38
631    37
632     7
633    61
634    19
635    67
636    46
637    70
638     9
639    23
640    71
641    96
642    30
643    95
644    93
645    15
646     2
647    23
648    50
649    25
650    26
651    12
652    20
653    38
654    45
655    33
656    97
657    88
658    32
659    82
660    71
661    65
662     5
663    18
664    36
665    43
666    32
667    11
668    68
669    65
670    64
671    21
672    52
673    77
674    57
675    38
676    65
677    89
678    91
679    46
680     7
681    82
682     4
683    41
684     9
685    84
686    42
687    30
688    52
689    58
690    34
691    81
692     9
693    87
694    35
695    87
696    57
697    13
698    96
699    26
700    57
701    23
702    40
703    84
704    58
705    77
706    15
707    31
708    12
709    14
710    95
711    95
712    90
713    70
714    34
715    86
716    95
717    87
718    79
719    89
720    78
721    32
722    95
723    20
724    61
725    77
726    96
727     4
728    22
729    12
730    39
731    88
732    16
733    52
734    25
735    92
736    43
737    43
738    55
739    74
740    19
741    16
742    34
743    27
744    47
745    42
746    26
747    38
748    90
749    51
750    28
751    91
752    39
753    56
754    63
755    52
756    22
757    79
758    72
759     8
760    84
761     5
762    85
763    75
764    36
765    41
766    40
767    60
768    67
769    62
770    25
771    19
772    45
773     6
774    11
775    87
776    82
777    45
778    93
779    85
780    75
781    84
782    94
783    90
784    35
785    83
786    33
787    90
788    35
789    55
790    34
791    50
792    98
793    73
794    10
795    10
796    49
797    73
798    76
799    34
800     6
801     9
802    31
803    90
804    66
805    89
806    27
807    56
808     9
809     1
810    66
811    31
812    10
813    62
814    82
815    40
816    17
817     1
818    95
819    62
820    66
821    15
822    90
823     6
824    50
825    65
826    28
827    31
828    13
829    57
830    84
831    46
832    44
833    17
834    84
835    78
836    73
837     6
838    13
839    47
840    56
841     9
842    61
843     4
844    10
845    81
846    19
847     5
848    61
849    55
850    12
851    62
852    68
853    22
854    66
855    50
856    92
857    94
858    59
859    45
860    42
861    80
862    91
863    42
864    89
865    14
866    69
867    27
868     3
869    77
870    47
871    46
872    89
873    14
874    58
875    51
876    31
877    51
878    97
879    20
880    13
881    18
882    94
883    27
884    52
885    63
886    99
887    73
888     9
889    44
890    14
891    26
892    54
893    71
894    80
895    15
896    99
897    21
898    57
899     1
900    57
901    46
902    81
903     9
904    33
905    85
906    10
907    87
908    35
909    32
910    96
911    33
912    41
913    84
914    16
915    13
916    12
917    87
918    28
919    80
920    51
921    16
922    66
923    16
924     8
925    69
926    53
927    15
928    13
929    75
930    25
931    29
932    82
933    41
934     2
935     4
936    80
937    47
938    99
939    43
940    52
941    22
942    73
943     1
944    49
945    86
946     8
947     6
948    40
949    99
950    69
951    61
952    69
953    14
954    34
955    49
956    18
957    27
958    89
959    43
960    40
961    86
962    49
963     7
964    22
965    99
966    19
967    50
968    95
969    61
970    60
971     1
972    54
973    60
974    30
975    69
976    82
977    51
978    66
979    99
980    23
981    44
982    59
983    80
984    60
985    96
986    61
987    47
988    95
989    27
990    86
991    63
992    10
993     2
994    77
995     8
996    66
997    71
998    83
999    82
dtype: int32

In [61]:
# Using assign() to add multiple columns
df_exams = df_exams.assign(HR_score=series1, logistics=series2)

In [62]:
# show dataframe
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,HR_score,logistics
0,female,group B,bachelor's degree,standard,none,72,72,74,20,95,30
1,female,group C,some college,standard,completed,69,90,88,30,15,48
2,female,group B,master's degree,standard,none,90,95,93,15,62,98
3,male,group A,associate's degree,free/reduced,none,47,57,44,96,80,77
4,male,group C,some college,standard,none,76,78,75,40,62,94
5,female,group B,associate's degree,standard,none,71,83,78,8,86,45
6,female,group B,some college,standard,completed,88,95,92,94,32,68
7,male,group B,some college,free/reduced,none,40,43,39,98,94,22
8,male,group D,high school,free/reduced,completed,64,64,67,2,56,55
9,female,group B,high school,free/reduced,none,38,60,50,1,92,97
10,male,group C,associate's degree,standard,none,58,54,52,8,9,97
11,male,group D,associate's degree,standard,none,40,52,43,8,36,90
12,female,group B,high school,standard,none,65,81,73,31,10,66
13,male,group A,some college,standard,completed,78,72,70,97,93,44
14,female,group A,master's degree,standard,none,50,53,58,90,4,7
15,female,group C,some high school,standard,none,69,75,78,21,33,14
16,male,group C,high school,standard,none,88,89,86,40,67,33
17,female,group B,some high school,free/reduced,none,18,32,28,82,31,54
18,male,group C,master's degree,free/reduced,completed,46,42,46,40,89,36
19,female,group C,associate's degree,free/reduced,none,54,58,61,67,31,27
20,male,group D,high school,standard,none,66,69,63,48,69,6
21,female,group B,some college,free/reduced,completed,65,75,70,98,30,51
22,male,group D,some college,standard,none,44,54,53,23,1,1
23,female,group C,some high school,standard,none,69,73,73,5,85,18
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80,87,90,68
25,male,group A,master's degree,free/reduced,none,73,74,72,74,31,10
26,male,group B,some college,standard,none,69,54,55,81,99,42
27,female,group C,bachelor's degree,standard,none,67,69,75,94,68,42
28,male,group C,high school,standard,none,70,70,65,78,71,49
29,female,group D,master's degree,standard,none,62,70,75,31,25,73
30,female,group D,some college,standard,none,69,74,74,26,44,92
31,female,group B,some college,standard,none,63,65,61,71,45,58
32,female,group E,master's degree,free/reduced,none,56,72,65,44,13,30
33,male,group D,some college,standard,none,40,42,38,78,39,16
34,male,group E,some college,standard,none,97,87,82,12,89,22
35,male,group E,associate's degree,standard,completed,81,81,79,89,6,26
36,female,group D,associate's degree,standard,none,74,81,83,84,8,15
37,female,group D,some high school,free/reduced,none,50,64,59,36,24,35
38,female,group D,associate's degree,free/reduced,completed,75,90,88,78,63,79
39,male,group B,associate's degree,free/reduced,none,57,56,57,91,90,92
40,male,group C,associate's degree,free/reduced,none,55,61,54,45,5,32
41,female,group C,associate's degree,standard,none,58,73,68,58,23,77
42,female,group B,associate's degree,standard,none,53,58,65,42,17,26
43,male,group B,some college,free/reduced,completed,59,65,66,80,27,73
44,female,group E,associate's degree,free/reduced,none,50,56,54,96,6,63
45,male,group B,associate's degree,standard,none,65,54,57,17,80,38
46,female,group A,associate's degree,standard,completed,55,65,62,87,53,30
47,female,group C,high school,standard,none,66,71,76,85,72,25
48,female,group D,associate's degree,free/reduced,completed,57,74,76,98,16,2
49,male,group C,high school,standard,completed,82,84,82,7,34,66
50,male,group E,some college,standard,none,53,55,48,98,66,86
51,male,group E,associate's degree,free/reduced,completed,77,69,68,72,60,99
52,male,group C,some college,standard,none,53,44,42,71,31,44
53,male,group D,high school,standard,none,88,78,75,83,48,58
54,female,group C,some high school,free/reduced,completed,71,84,87,17,58,67
55,female,group C,high school,free/reduced,none,33,41,43,18,50,62
56,female,group E,associate's degree,standard,completed,82,85,86,35,81,40
57,male,group D,associate's degree,standard,none,52,55,49,19,75,64
58,male,group D,some college,standard,completed,58,59,58,87,88,67
59,female,group C,some high school,free/reduced,none,0,17,10,28,79,73
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72,52,57,50
61,male,group A,some high school,free/reduced,none,39,39,34,10,75,64
62,male,group A,associate's degree,free/reduced,none,62,61,55,21,8,61
63,female,group C,associate's degree,standard,none,69,80,71,73,92,81
64,female,group D,some high school,standard,none,59,58,59,43,7,45
65,male,group B,some high school,standard,none,67,64,61,84,88,28
66,male,group D,some high school,free/reduced,none,45,37,37,93,58,55
67,female,group C,some college,standard,none,60,72,74,7,71,60
68,male,group B,associate's degree,free/reduced,none,61,58,56,23,85,30
69,female,group C,associate's degree,standard,none,39,64,57,24,30,45
70,female,group D,some college,free/reduced,completed,58,63,73,91,32,17
71,male,group D,some college,standard,completed,63,55,63,68,83,52
72,female,group A,associate's degree,free/reduced,none,41,51,48,14,37,20
73,male,group C,some high school,free/reduced,none,61,57,56,47,78,1
74,male,group C,some high school,standard,none,49,49,41,43,69,26
75,male,group B,associate's degree,free/reduced,none,44,41,38,82,42,81
76,male,group E,some high school,standard,none,30,26,22,71,20,52
77,male,group A,bachelor's degree,standard,completed,80,78,81,66,35,45
78,female,group D,some high school,standard,completed,61,74,72,72,71,35
79,female,group E,master's degree,standard,none,62,68,68,98,70,67
80,female,group B,associate's degree,standard,none,47,49,50,17,18,64
81,male,group B,high school,free/reduced,none,49,45,45,68,70,1
82,male,group A,some college,free/reduced,completed,50,47,54,64,10,61
83,male,group E,associate's degree,standard,none,72,64,63,61,20,36
84,male,group D,high school,free/reduced,none,42,39,34,81,89,96
85,female,group C,some college,standard,none,73,80,82,15,22,97
86,female,group C,some college,free/reduced,none,76,83,88,34,50,95
87,female,group D,associate's degree,standard,none,71,71,74,64,33,5
88,female,group A,some college,standard,none,58,70,67,80,39,47
89,female,group D,some high school,standard,none,73,86,82,27,5,65
90,female,group C,bachelor's degree,standard,none,65,72,74,64,91,57
91,male,group C,high school,free/reduced,none,27,34,36,70,13,97
92,male,group C,high school,standard,none,71,79,71,33,25,90
93,male,group C,associate's degree,free/reduced,completed,43,45,50,9,36,42
94,female,group B,some college,standard,none,79,86,92,49,25,9
95,male,group C,associate's degree,free/reduced,completed,78,81,82,51,72,75
96,male,group B,some high school,standard,completed,65,66,62,27,84,11
97,female,group E,some college,standard,completed,63,72,70,69,11,35
98,female,group D,some college,free/reduced,none,58,67,62,95,89,91
99,female,group D,bachelor's degree,standard,none,65,67,62,30,61,45
100,male,group B,some college,standard,none,79,67,67,50,18,70
101,male,group D,bachelor's degree,standard,completed,68,74,74,25,10,34
102,female,group D,associate's degree,standard,none,85,91,89,85,22,95
103,male,group B,high school,standard,completed,60,44,47,69,66,7
104,male,group C,some college,standard,completed,98,86,90,34,78,99
105,female,group C,some college,standard,none,58,67,72,38,51,34
106,female,group D,master's degree,standard,none,87,100,100,12,71,50
107,male,group E,associate's degree,standard,completed,66,63,64,25,67,69
108,female,group B,associate's degree,free/reduced,none,52,76,70,36,45,80
109,female,group B,some high school,standard,none,70,64,72,82,43,87
110,female,group D,associate's degree,free/reduced,completed,77,89,98,69,30,91
111,male,group C,high school,standard,none,62,55,49,87,14,47
112,male,group A,associate's degree,standard,none,54,53,47,30,78,62
113,female,group D,some college,standard,none,51,58,54,6,27,45
114,female,group E,bachelor's degree,standard,completed,99,100,100,7,68,18
115,male,group C,high school,standard,none,84,77,74,57,57,33
116,female,group B,bachelor's degree,free/reduced,none,75,85,82,63,18,4
117,female,group D,bachelor's degree,standard,none,78,82,79,51,80,77
118,female,group D,some high school,standard,none,51,63,61,88,88,25
119,female,group C,some college,standard,none,55,69,65,47,68,45
120,female,group C,bachelor's degree,standard,completed,79,92,89,69,48,10
121,male,group B,associate's degree,standard,completed,91,89,92,91,98,75
122,female,group C,some college,standard,completed,88,93,93,79,20,95
123,male,group D,high school,free/reduced,none,63,57,56,23,24,11
124,male,group E,some college,standard,none,83,80,73,32,21,4
125,female,group B,high school,standard,none,87,95,86,10,30,65
126,male,group B,some high school,standard,none,72,68,67,84,2,65
127,male,group D,some college,standard,completed,65,77,74,81,57,68
128,male,group D,master's degree,standard,none,82,82,74,73,15,52
129,female,group A,bachelor's degree,standard,none,51,49,51,78,98,87
130,male,group D,master's degree,standard,none,89,84,82,53,99,24
131,male,group C,some high school,free/reduced,completed,53,37,40,97,4,40
132,male,group E,some college,free/reduced,completed,87,74,70,16,67,61
133,female,group C,some college,standard,completed,75,81,84,55,80,42
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75,38,51,59
135,male,group C,bachelor's degree,standard,none,58,55,48,22,36,48
136,male,group B,some high school,standard,completed,51,54,41,46,33,27
137,male,group E,high school,standard,none,70,55,56,52,59,86
138,female,group C,associate's degree,standard,none,59,66,67,14,58,19
139,male,group D,some college,standard,completed,71,61,69,58,60,10
140,female,group D,some high school,standard,none,76,72,71,13,11,67
141,female,group C,some college,free/reduced,none,59,62,64,48,49,80
142,female,group E,some college,free/reduced,completed,42,55,54,26,62,71
143,male,group A,high school,standard,none,57,43,47,47,3,2
144,male,group D,some college,standard,none,88,73,78,91,16,47
145,female,group C,some college,free/reduced,none,22,39,33,63,58,2
146,male,group B,some high school,standard,none,88,84,75,26,13,88
147,male,group C,associate's degree,free/reduced,none,73,68,66,17,57,93
148,female,group D,bachelor's degree,standard,completed,68,75,81,71,70,25
149,male,group E,associate's degree,free/reduced,completed,100,100,93,63,2,78
150,male,group A,some high school,standard,completed,62,67,69,77,74,57
151,male,group A,bachelor's degree,standard,none,77,67,68,74,75,84
152,female,group B,associate's degree,standard,completed,59,70,66,13,78,50
153,male,group D,bachelor's degree,standard,none,54,49,47,98,90,22
154,male,group D,some high school,standard,none,62,67,61,32,40,99
155,female,group C,some college,standard,completed,70,89,88,54,44,87
156,female,group E,high school,free/reduced,completed,66,74,78,25,42,25
157,male,group B,some college,free/reduced,none,60,60,60,88,89,36
158,female,group B,associate's degree,standard,completed,61,86,87,97,39,46
159,male,group D,associate's degree,free/reduced,none,66,62,64,19,97,46
160,male,group B,associate's degree,free/reduced,completed,82,78,74,53,41,54
161,female,group E,some college,free/reduced,completed,75,88,85,91,62,48
162,male,group B,master's degree,free/reduced,none,49,53,52,58,11,61
163,male,group C,high school,standard,none,52,53,49,20,46,97
164,female,group E,master's degree,standard,none,81,92,91,53,52,63
165,female,group C,bachelor's degree,standard,completed,96,100,100,72,85,82
166,male,group C,high school,free/reduced,completed,53,51,51,83,13,13
167,female,group B,master's degree,free/reduced,completed,58,76,78,99,21,35
168,female,group B,high school,standard,completed,68,83,78,39,4,79
169,female,group C,some college,free/reduced,completed,67,75,70,20,63,55
170,male,group A,high school,standard,completed,72,73,74,32,61,93
171,male,group E,some high school,standard,none,94,88,78,3,54,30
172,female,group D,some college,standard,none,79,86,81,7,10,60
173,female,group C,associate's degree,standard,none,63,67,70,19,51,42
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54,6,40,37
175,female,group C,master's degree,standard,completed,81,91,87,50,1,17
176,female,group B,high school,free/reduced,completed,46,54,58,97,28,98
177,female,group C,associate's degree,standard,completed,71,77,77,33,39,31
178,female,group B,master's degree,free/reduced,completed,52,70,62,82,76,25
179,female,group D,some high school,standard,completed,97,100,100,63,10,22
180,male,group C,master's degree,free/reduced,completed,62,68,75,48,62,57
181,female,group C,some college,free/reduced,none,46,64,66,72,24,46
182,female,group E,high school,standard,none,50,50,47,90,86,6
183,female,group D,associate's degree,standard,none,65,69,70,47,68,86
184,male,group C,some high school,free/reduced,completed,45,52,49,67,39,8
185,male,group C,associate's degree,free/reduced,completed,65,67,65,21,62,51
186,male,group E,high school,standard,none,80,76,65,93,64,99
187,male,group D,some high school,standard,completed,62,66,68,98,89,35
188,male,group B,some high school,free/reduced,none,48,52,45,1,41,20
189,female,group C,bachelor's degree,standard,none,77,88,87,26,76,4
190,female,group E,associate's degree,standard,none,66,65,69,14,41,43
191,male,group D,some college,standard,completed,76,83,79,25,35,30
192,female,group B,some high school,standard,none,62,64,66,2,70,61
193,male,group D,some college,standard,completed,77,62,62,51,78,22
194,female,group C,master's degree,standard,completed,69,84,85,99,23,98
195,male,group D,associate's degree,standard,none,61,55,52,39,17,79
196,male,group C,some high school,free/reduced,completed,59,69,65,38,82,88
197,male,group E,high school,free/reduced,none,55,56,51,33,20,21
198,female,group B,some college,free/reduced,none,45,53,55,42,59,30
199,female,group B,bachelor's degree,free/reduced,none,78,79,76,24,68,97
200,female,group C,associate's degree,standard,completed,67,84,86,74,18,46
201,female,group D,some college,free/reduced,none,65,81,77,86,83,96
202,male,group C,associate's degree,standard,none,69,77,69,15,20,83
203,female,group B,associate's degree,standard,none,57,69,68,88,52,67
204,male,group C,some college,standard,none,59,41,42,45,73,45
205,male,group D,some high school,standard,completed,74,71,78,35,21,86
206,male,group E,bachelor's degree,standard,none,82,62,62,39,77,87
207,male,group E,high school,standard,completed,81,80,76,26,65,26
208,female,group B,some college,free/reduced,none,74,81,76,45,43,82
209,female,group B,some college,free/reduced,none,58,61,66,11,32,91
210,male,group D,some high school,free/reduced,completed,80,79,79,79,74,18
211,male,group C,some college,free/reduced,none,35,28,27,12,81,14
212,female,group C,high school,free/reduced,none,42,62,60,25,45,99
213,male,group C,associate's degree,free/reduced,completed,60,51,56,29,93,42
214,male,group E,high school,standard,completed,87,91,81,94,28,8
215,male,group B,some high school,standard,completed,84,83,75,51,50,45
216,female,group E,associate's degree,free/reduced,completed,83,86,88,24,71,12
217,female,group C,high school,free/reduced,none,34,42,39,71,39,16
218,male,group B,high school,free/reduced,none,66,77,70,42,97,49
219,male,group B,some high school,standard,completed,61,56,56,14,78,61
220,female,group D,high school,standard,completed,56,68,74,14,81,48
221,male,group B,associate's degree,standard,none,87,85,73,12,76,42
222,female,group C,some high school,free/reduced,none,55,65,62,15,95,56
223,male,group D,some high school,standard,none,86,80,75,38,50,29
224,female,group B,associate's degree,standard,completed,52,66,73,3,35,80
225,female,group E,master's degree,free/reduced,none,45,56,54,39,29,46
226,female,group C,some college,standard,none,72,72,71,59,31,5
227,male,group D,high school,standard,none,57,50,54,73,54,90
228,male,group A,some high school,free/reduced,none,68,72,64,49,1,81
229,female,group C,some college,standard,completed,88,95,94,1,91,89
230,male,group D,some college,standard,none,76,64,66,61,64,41
231,male,group C,associate's degree,standard,none,46,43,42,28,60,6
232,female,group B,bachelor's degree,standard,none,67,86,83,71,93,69
233,male,group E,some high school,standard,none,92,87,78,37,63,51
234,male,group C,bachelor's degree,standard,completed,83,82,84,58,85,57
235,male,group D,associate's degree,standard,none,80,75,77,47,7,6
236,male,group D,bachelor's degree,free/reduced,none,63,66,67,84,67,12
237,female,group D,some high school,standard,completed,64,60,74,73,25,99
238,male,group B,some college,standard,none,54,52,51,10,2,85
239,male,group C,associate's degree,standard,none,84,80,80,30,73,71
240,male,group D,high school,free/reduced,completed,73,68,66,53,41,6
241,female,group E,bachelor's degree,standard,none,80,83,83,83,10,96
242,female,group D,high school,standard,none,56,52,55,9,30,31
243,male,group E,some college,standard,none,59,51,43,67,71,70
244,male,group D,some high school,standard,none,75,74,69,2,13,71
245,male,group C,associate's degree,standard,none,85,76,71,52,21,53
246,male,group E,associate's degree,standard,none,89,76,74,86,77,6
247,female,group B,high school,standard,completed,58,70,68,51,99,15
248,female,group B,high school,standard,none,65,64,62,15,96,21
249,male,group C,high school,standard,none,68,60,53,4,22,46
250,male,group A,some high school,standard,completed,47,49,49,26,97,30
251,female,group D,some college,free/reduced,none,71,83,83,97,37,93
252,female,group B,some high school,standard,completed,60,70,70,35,24,15
253,male,group D,master's degree,standard,none,80,80,72,7,5,7
254,male,group D,high school,standard,none,54,52,52,88,14,86
255,female,group E,some college,standard,none,62,73,70,96,67,5
256,female,group C,associate's degree,free/reduced,none,64,73,68,98,30,96
257,male,group C,associate's degree,standard,completed,78,77,77,58,59,53
258,female,group B,some college,standard,none,70,75,78,44,35,33
259,female,group C,master's degree,free/reduced,completed,65,81,81,43,24,55
260,female,group C,some high school,free/reduced,completed,64,79,77,35,81,22
261,male,group C,some college,standard,completed,79,79,78,96,74,71
262,female,group C,some high school,free/reduced,none,44,50,51,27,62,98
263,female,group E,high school,standard,none,99,93,90,91,2,24
264,male,group D,high school,standard,none,76,73,68,15,18,57
265,male,group D,some high school,free/reduced,none,59,42,41,86,92,78
266,female,group C,bachelor's degree,standard,none,63,75,81,12,93,99
267,female,group D,high school,standard,none,69,72,77,38,18,84
268,female,group D,associate's degree,standard,completed,88,92,95,71,30,1
269,female,group E,some college,free/reduced,none,71,76,70,75,4,53
270,male,group C,bachelor's degree,standard,none,69,63,61,10,75,71
271,male,group C,some college,standard,none,58,49,42,96,72,31
272,female,group D,associate's degree,free/reduced,none,47,53,58,66,32,22
273,female,group D,some college,standard,none,65,70,71,81,75,48
274,male,group B,some college,standard,completed,88,85,76,67,39,12
275,male,group C,bachelor's degree,standard,none,83,78,73,99,75,44
276,female,group C,some high school,standard,completed,85,92,93,53,92,37
277,female,group E,high school,standard,completed,59,63,75,67,36,67
278,female,group C,some high school,free/reduced,none,65,86,80,99,14,32
279,male,group B,bachelor's degree,free/reduced,none,73,56,57,36,65,36
280,male,group D,high school,standard,none,53,52,42,40,25,34
281,male,group D,high school,standard,none,45,48,46,56,42,93
282,female,group D,bachelor's degree,free/reduced,none,73,79,84,20,31,4
283,female,group D,some college,free/reduced,completed,70,78,78,7,44,65
284,female,group B,some high school,standard,none,37,46,46,8,49,86
285,male,group B,associate's degree,standard,completed,81,82,82,62,58,3
286,male,group E,associate's degree,standard,completed,97,82,88,45,13,67
287,female,group B,some high school,standard,none,67,89,82,62,57,47
288,male,group B,bachelor's degree,free/reduced,none,88,75,76,92,15,44
289,male,group E,some high school,standard,completed,77,76,77,27,47,44

# 3.2 insert()
### Insert a new column at a special position or index.

In [63]:
# using index() to add  a column at a specific position
df_exams.insert(1, 'test', series1)

# 1 Math Operation
### 1.1 Operation in columns

In [64]:
# select a column and calculate total sum
df_exams['math score'].sum()

66089

In [69]:
# count, mean, std, max, and min
df_exams['math score'].count()
df_exams['math score'].mean()
df_exams['math score'].std()
df_exams['math score'].max()
df_exams['math score'].min()

0

In [70]:
# easier calculation with .describe()
df_exams['math score'].describe()

count    1000.00000
mean       66.08900
std        15.16308
min         0.00000
25%        57.00000
50%        66.00000
75%        77.00000
max       100.00000
Name: math score, dtype: float64

### 1.2 Operations in rows

In [71]:
# calculate the sum in a row
df_exams['math score'] + df_exams['reading score'] + df_exams['writing score']

0      218
1      247
2      278
3      148
4      229
5      232
6      275
7      122
8      195
9      148
10     164
11     135
12     219
13     220
14     161
15     222
16     263
17      78
18     134
19     173
20     198
21     210
22     151
23     215
24     225
25     219
26     178
27     211
28     205
29     207
30     217
31     189
32     193
33     120
34     266
35     241
36     238
37     173
38     253
39     170
40     170
41     199
42     176
43     190
44     160
45     176
46     182
47     213
48     207
49     248
50     156
51     214
52     139
53     241
54     242
55     117
56     253
57     156
58     175
59      27
60     225
61     112
62     178
63     220
64     176
65     192
66     119
67     206
68     175
69     160
70     194
71     181
72     140
73     174
74     139
75     123
76      78
77     239
78     207
79     198
80     146
81     139
82     151
83     199
84     115
85     235
86     247
87     216
88     195
89     241
90     211
91      97
92     221
93     138
94     257
95     241
96     193
97     205
98     187
99     194
100    213
101    216
102    265
103    151
104    274
105    197
106    287
107    193
108    198
109    206
110    264
111    166
112    154
113    163
114    299
115    235
116    242
117    239
118    175
119    189
120    260
121    272
122    274
123    176
124    236
125    268
126    207
127    216
128    238
129    151
130    255
131    130
132    231
133    240
134    228
135    161
136    146
137    181
138    192
139    201
140    219
141    185
142    151
143    147
144    239
145     94
146    247
147    207
148    224
149    293
150    198
151    212
152    195
153    150
154    190
155    247
156    218
157    180
158    234
159    192
160    234
161    248
162    154
163    154
164    264
165    296
166    155
167    212
168    229
169    212
170    219
171    260
172    246
173    200
174    148
175    259
176    158
177    225
178    184
179    297
180    205
181    176
182    147
183    204
184    146
185    197
186    221
187    196
188    145
189    252
190    200
191    238
192    192
193    201
194    238
195    168
196    193
197    162
198    153
199    233
200    237
201    223
202    215
203    194
204    142
205    223
206    206
207    237
208    231
209    185
210    238
211     90
212    164
213    167
214    259
215    242
216    257
217    115
218    213
219    173
220    198
221    245
222    182
223    241
224    191
225    155
226    215
227    161
228    204
229    277
230    206
231    131
232    236
233    257
234    249
235    232
236    196
237    198
238    157
239    244
240    207
241    246
242    163
243    153
244    218
245    232
246    239
247    196
248    191
249    181
250    145
251    237
252    200
253    232
254    158
255    205
256    205
257    232
258    223
259    227
260    220
261    236
262    145
263    282
264    217
265    142
266    219
267    218
268    275
269    217
270    193
271    149
272    158
273    206
274    249
275    234
276    270
277    197
278    231
279    186
280    147
281    139
282    236
283    226
284    129
285    245
286    267
287    238
288    239
289    230
290    214
291    229
292    180
293    213
294    235
295    189
296    130
297    213
298    136
299    252
300    240
301    162
302    232
303    220
304    232
305    205
306    267
307    147
308    191
309    158
310    229
311    183
312    196
313    204
314    198
315    202
316    250
317    233
318    203
319    184
320    230
321    240
322    232
323    149
324    130
325    266
326    184
327     70
328    234
329    147
330    192
331    119
332    171
333    249
334    271
335    195
336    215
337    143
338     89
339    150
340    171
341    197
342    219
343    206
344    219
345    227
346    180
347    266
348    215
349    237
350    186
351    175
352    221
353    161
354    200
355    203
356    185
357    177
358    182
359    259
360    179
361    247
362    168
363     93
364    177
365    167
366    180
367    188
368    166
369    242
370    232
371    188
372    220
373    275
374    202
375    130
376    252
377    280
378    231
379    192
380    249
381    282
382    231
383    132
384    124
385    218
386    207
387    202
388    190
389    218
390    199
391    222
392    210
393    167
394    216
395    134
396    180
397    269
398    194
399    173
400    180
401    139
402    169
403    287
404    175
405    204
406    193
407    239
408    165
409    256
410    215
411    245
412    197
413    197
414    202
415    226
416    213
417    214
418    189
419    167
420    268
421    179
422    172
423    224
424    114
425    191
426    255
427    205
428    177
429    185
430    189
431    203
432    172
433    156
434    205
435    151
436    207
437    214
438    177
439    259
440    227
441    239
442    201
443    232
444    234
445    218
446    195
447    247
448    135
449    226
450    234
451    289
452    216
453    172
454    176
455    140
456    257
457    155
458    300
459    205
460    166
461    153
462    217
463    258
464    195
465    262
466     95
467    204
468    250
469    241
470    258
471    206
472    238
473    187
474    271
475    230
476    204
477    220
478    189
479    214
480    212
481    167
482    197
483    157
484    155
485    215
486    164
487    209
488    174
489    243
490    226
491    198
492    256
493    259
494    186
495    198
496    154
497    213
498    203
499    219
500    235
501    273
502    178
503    276
504    153
505    244
506    204
507    168
508    234
509    265
510    220
511    157
512    163
513    177
514    268
515    248
516    247
517    213
518    222
519    224
520    172
521    261
522    184
523    163
524    154
525    187
526    177
527    132
528    117
529    206
530    208
531    154
532    181
533    261
534    210
535    232
536    169
537    179
538    222
539    275
540    212
541    241
542    237
543    266
544    193
545    241
546    289
547    203
548    193
549    220
550    220
551    265
552    138
553    203
554    138
555    104
556    206
557    194
558    193
559    201
560    228
561    211
562    278
563    223
564    145
565    136
566    292
567    210
568    158
569    203
570    216
571    279
572    171
573    180
574    226
575    148
576    164
577    261
578    162
579    182
580    274
581    236
582    214
583    228
584    223
585    217
586    201
587    169
588    183
589    179
590    169
591    183
592    200
593    223
594    291
595    207
596     69
597    155
598    219
599    228
600    177
601     88
602    234
603    168
604    263
605    209
606    251
607    152
608    187
609    186
610    192
611    183
612    275
613    216
614    268
615    200
616    120
617    249
618    260
619    206
620    150
621    181
622    161
623    282
624    181
625    296
626    202
627    155
628    152
629    150
630    201
631    204
632    221
633    248
634    248
635    209
636    228
637    260
638    236
639    223
640    144
641    252
642    232
643    233
644    195
645    227
646    194
647    194
648    158
649    229
650    160
651    224
652    269
653    209
654    231
655    196
656    208
657    196
658    161
659    262
660    224
661    202
662    195
663    201
664    206
665    170
666    207
667    249
668    208
669    230
670    210
671    159
672    223
673    233
674    224
675    180
676    227
677    228
678    234
679    184
680    213
681    188
682    171
683    113
684    196
685    293
686    228
687    228
688    155
689    266
690    155
691    227
692    221
693    227
694    168
695    254
696    247
697    201
698    214
699    191
700    242
701    196
702    258
703    194
704    186
705    199
706    116
707    177
708    255
709    161
710    267
711    250
712    297
713    246
714    204
715    257
716    223
717    291
718    226
719    244
720    204
721    173
722    252
723    140
724    131
725    226
726    217
727    176
728    249
729    129
730    225
731    144
732    270
733    146
734    168
735    183
736    255
737    192
738    225
739    176
740    225
741    150
742    247
743    204
744    157
745    225
746    215
747    201
748    169
749    257
750    208
751    205
752    231
753    252
754    166
755    271
756    165
757    210
758    176
759    223
760    189
761    160
762    245
763    187
764    182
765    218
766    210
767    198
768    214
769    175
770    149
771    222
772    191
773    219
774    191
775    162
776    208
777    122
778    233
779    261
780    159
781    251
782    243
783    173
784    251
785    127
786    228
787     89
788    194
789    178
790    170
791    196
792    209
793    250
794    145
795    198
796    210
797    235
798    183
799    164
800    208
801    229
802    276
803    254
804    227
805    230
806    213
807    126
808    234
809    164
810    118
811    141
812    185
813    247
814    235
815    267
816    168
817    207
818    200
819    256
820    267
821    261
822    152
823    240
824    158
825    187
826    194
827    210
828    236
829    175
830    178
831    249
832    182
833    248
834    153
835    198
836    194
837    236
838    168
839    216
840    137
841    173
842    103
843    227
844    169
845    259
846    261
847    168
848    199
849    224
850    205
851    192
852    265
853    210
854    181
855    290
856    208
857    225
858    147
859    232
860    168
861    254
862    119
863    222
864    281
865    252
866    164
867    144
868    224
869    151
870    164
871    218
872    244
873    262
874    166
875    210
876    247
877    172
878    211
879    214
880    193
881    211
882    208
883    145
884    156
885    218
886    288
887    185
888    208
889    143
890    262
891    262
892    190
893    237
894    190
895    104
896     92
897    220
898    184
899    225
900    258
901    225
902    123
903    293
904    235
905    242
906    156
907    254
908    214
909    204
910    140
911    235
912    179
913    175
914    162
915    204
916    300
917    157
918    214
919    278
920    206
921    134
922    204
923    184
924    213
925    198
926    172
927    197
928    133
929    155
930    211
931    181
932    205
933    219
934    275
935    191
936    177
937    172
938    251
939    214
940    210
941    265
942    211
943    184
944    187
945    173
946    244
947    167
948    151
949    205
950    238
951    235
952    220
953    164
954    200
955    191
956    252
957    292
958    167
959    227
960    178
961    155
962    300
963    216
964    187
965    204
966    198
967    186
968    211
969    239
970    289
971    219
972    163
973    175
974    184
975    223
976    182
977    185
978    144
979    280
980     55
981    237
982    250
983    256
984    231
985    162
986    150
987    232
988    134
989    236
990    242
991    225
992    207
993    208
994    188
995    282
996    172
997    195
998    223
999    249
dtype: int64

In [72]:
# calculate the avarage score and assigning the result to new column
df_exams['average'] = (df_exams['math score'] + df_exams['reading score'] + df_exams['writing score'])/3

In [74]:
df_exams.round(2)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,HR_score,logistics,average
0,female,95,group B,bachelor's degree,standard,none,72,72,74,20,95,30,72.67
1,female,15,group C,some college,standard,completed,69,90,88,30,15,48,82.33
2,female,62,group B,master's degree,standard,none,90,95,93,15,62,98,92.67
3,male,80,group A,associate's degree,free/reduced,none,47,57,44,96,80,77,49.33
4,male,62,group C,some college,standard,none,76,78,75,40,62,94,76.33
5,female,86,group B,associate's degree,standard,none,71,83,78,8,86,45,77.33
6,female,32,group B,some college,standard,completed,88,95,92,94,32,68,91.67
7,male,94,group B,some college,free/reduced,none,40,43,39,98,94,22,40.67
8,male,56,group D,high school,free/reduced,completed,64,64,67,2,56,55,65.00
9,female,92,group B,high school,free/reduced,none,38,60,50,1,92,97,49.33
10,male,9,group C,associate's degree,standard,none,58,54,52,8,9,97,54.67
11,male,36,group D,associate's degree,standard,none,40,52,43,8,36,90,45.00
12,female,10,group B,high school,standard,none,65,81,73,31,10,66,73.00
13,male,93,group A,some college,standard,completed,78,72,70,97,93,44,73.33
14,female,4,group A,master's degree,standard,none,50,53,58,90,4,7,53.67
15,female,33,group C,some high school,standard,none,69,75,78,21,33,14,74.00
16,male,67,group C,high school,standard,none,88,89,86,40,67,33,87.67
17,female,31,group B,some high school,free/reduced,none,18,32,28,82,31,54,26.00
18,male,89,group C,master's degree,free/reduced,completed,46,42,46,40,89,36,44.67
19,female,31,group C,associate's degree,free/reduced,none,54,58,61,67,31,27,57.67
20,male,69,group D,high school,standard,none,66,69,63,48,69,6,66.00
21,female,30,group B,some college,free/reduced,completed,65,75,70,98,30,51,70.00
22,male,1,group D,some college,standard,none,44,54,53,23,1,1,50.33
23,female,85,group C,some high school,standard,none,69,73,73,5,85,18,71.67
24,male,90,group D,bachelor's degree,free/reduced,completed,74,71,80,87,90,68,75.00
25,male,31,group A,master's degree,free/reduced,none,73,74,72,74,31,10,73.00
26,male,99,group B,some college,standard,none,69,54,55,81,99,42,59.33
27,female,68,group C,bachelor's degree,standard,none,67,69,75,94,68,42,70.33
28,male,71,group C,high school,standard,none,70,70,65,78,71,49,68.33
29,female,25,group D,master's degree,standard,none,62,70,75,31,25,73,69.00
30,female,44,group D,some college,standard,none,69,74,74,26,44,92,72.33
31,female,45,group B,some college,standard,none,63,65,61,71,45,58,63.00
32,female,13,group E,master's degree,free/reduced,none,56,72,65,44,13,30,64.33
33,male,39,group D,some college,standard,none,40,42,38,78,39,16,40.00
34,male,89,group E,some college,standard,none,97,87,82,12,89,22,88.67
35,male,6,group E,associate's degree,standard,completed,81,81,79,89,6,26,80.33
36,female,8,group D,associate's degree,standard,none,74,81,83,84,8,15,79.33
37,female,24,group D,some high school,free/reduced,none,50,64,59,36,24,35,57.67
38,female,63,group D,associate's degree,free/reduced,completed,75,90,88,78,63,79,84.33
39,male,90,group B,associate's degree,free/reduced,none,57,56,57,91,90,92,56.67
40,male,5,group C,associate's degree,free/reduced,none,55,61,54,45,5,32,56.67
41,female,23,group C,associate's degree,standard,none,58,73,68,58,23,77,66.33
42,female,17,group B,associate's degree,standard,none,53,58,65,42,17,26,58.67
43,male,27,group B,some college,free/reduced,completed,59,65,66,80,27,73,63.33
44,female,6,group E,associate's degree,free/reduced,none,50,56,54,96,6,63,53.33
45,male,80,group B,associate's degree,standard,none,65,54,57,17,80,38,58.67
46,female,53,group A,associate's degree,standard,completed,55,65,62,87,53,30,60.67
47,female,72,group C,high school,standard,none,66,71,76,85,72,25,71.00
48,female,16,group D,associate's degree,free/reduced,completed,57,74,76,98,16,2,69.00
49,male,34,group C,high school,standard,completed,82,84,82,7,34,66,82.67
50,male,66,group E,some college,standard,none,53,55,48,98,66,86,52.00
51,male,60,group E,associate's degree,free/reduced,completed,77,69,68,72,60,99,71.33
52,male,31,group C,some college,standard,none,53,44,42,71,31,44,46.33
53,male,48,group D,high school,standard,none,88,78,75,83,48,58,80.33
54,female,58,group C,some high school,free/reduced,completed,71,84,87,17,58,67,80.67
55,female,50,group C,high school,free/reduced,none,33,41,43,18,50,62,39.00
56,female,81,group E,associate's degree,standard,completed,82,85,86,35,81,40,84.33
57,male,75,group D,associate's degree,standard,none,52,55,49,19,75,64,52.00
58,male,88,group D,some college,standard,completed,58,59,58,87,88,67,58.33
59,female,79,group C,some high school,free/reduced,none,0,17,10,28,79,73,9.00
60,male,57,group E,bachelor's degree,free/reduced,completed,79,74,72,52,57,50,75.00
61,male,75,group A,some high school,free/reduced,none,39,39,34,10,75,64,37.33
62,male,8,group A,associate's degree,free/reduced,none,62,61,55,21,8,61,59.33
63,female,92,group C,associate's degree,standard,none,69,80,71,73,92,81,73.33
64,female,7,group D,some high school,standard,none,59,58,59,43,7,45,58.67
65,male,88,group B,some high school,standard,none,67,64,61,84,88,28,64.00
66,male,58,group D,some high school,free/reduced,none,45,37,37,93,58,55,39.67
67,female,71,group C,some college,standard,none,60,72,74,7,71,60,68.67
68,male,85,group B,associate's degree,free/reduced,none,61,58,56,23,85,30,58.33
69,female,30,group C,associate's degree,standard,none,39,64,57,24,30,45,53.33
70,female,32,group D,some college,free/reduced,completed,58,63,73,91,32,17,64.67
71,male,83,group D,some college,standard,completed,63,55,63,68,83,52,60.33
72,female,37,group A,associate's degree,free/reduced,none,41,51,48,14,37,20,46.67
73,male,78,group C,some high school,free/reduced,none,61,57,56,47,78,1,58.00
74,male,69,group C,some high school,standard,none,49,49,41,43,69,26,46.33
75,male,42,group B,associate's degree,free/reduced,none,44,41,38,82,42,81,41.00
76,male,20,group E,some high school,standard,none,30,26,22,71,20,52,26.00
77,male,35,group A,bachelor's degree,standard,completed,80,78,81,66,35,45,79.67
78,female,71,group D,some high school,standard,completed,61,74,72,72,71,35,69.00
79,female,70,group E,master's degree,standard,none,62,68,68,98,70,67,66.00
80,female,18,group B,associate's degree,standard,none,47,49,50,17,18,64,48.67
81,male,70,group B,high school,free/reduced,none,49,45,45,68,70,1,46.33
82,male,10,group A,some college,free/reduced,completed,50,47,54,64,10,61,50.33
83,male,20,group E,associate's degree,standard,none,72,64,63,61,20,36,66.33
84,male,89,group D,high school,free/reduced,none,42,39,34,81,89,96,38.33
85,female,22,group C,some college,standard,none,73,80,82,15,22,97,78.33
86,female,50,group C,some college,free/reduced,none,76,83,88,34,50,95,82.33
87,female,33,group D,associate's degree,standard,none,71,71,74,64,33,5,72.00
88,female,39,group A,some college,standard,none,58,70,67,80,39,47,65.00
89,female,5,group D,some high school,standard,none,73,86,82,27,5,65,80.33
90,female,91,group C,bachelor's degree,standard,none,65,72,74,64,91,57,70.33
91,male,13,group C,high school,free/reduced,none,27,34,36,70,13,97,32.33
92,male,25,group C,high school,standard,none,71,79,71,33,25,90,73.67
93,male,36,group C,associate's degree,free/reduced,completed,43,45,50,9,36,42,46.00
94,female,25,group B,some college,standard,none,79,86,92,49,25,9,85.67
95,male,72,group C,associate's degree,free/reduced,completed,78,81,82,51,72,75,80.33
96,male,84,group B,some high school,standard,completed,65,66,62,27,84,11,64.33
97,female,11,group E,some college,standard,completed,63,72,70,69,11,35,68.33
98,female,89,group D,some college,free/reduced,none,58,67,62,95,89,91,62.33
99,female,61,group D,bachelor's degree,standard,none,65,67,62,30,61,45,64.67
100,male,18,group B,some college,standard,none,79,67,67,50,18,70,71.00
101,male,10,group D,bachelor's degree,standard,completed,68,74,74,25,10,34,72.00
102,female,22,group D,associate's degree,standard,none,85,91,89,85,22,95,88.33
103,male,66,group B,high school,standard,completed,60,44,47,69,66,7,50.33
104,male,78,group C,some college,standard,completed,98,86,90,34,78,99,91.33
105,female,51,group C,some college,standard,none,58,67,72,38,51,34,65.67
106,female,71,group D,master's degree,standard,none,87,100,100,12,71,50,95.67
107,male,67,group E,associate's degree,standard,completed,66,63,64,25,67,69,64.33
108,female,45,group B,associate's degree,free/reduced,none,52,76,70,36,45,80,66.00
109,female,43,group B,some high school,standard,none,70,64,72,82,43,87,68.67
110,female,30,group D,associate's degree,free/reduced,completed,77,89,98,69,30,91,88.00
111,male,14,group C,high school,standard,none,62,55,49,87,14,47,55.33
112,male,78,group A,associate's degree,standard,none,54,53,47,30,78,62,51.33
113,female,27,group D,some college,standard,none,51,58,54,6,27,45,54.33
114,female,68,group E,bachelor's degree,standard,completed,99,100,100,7,68,18,99.67
115,male,57,group C,high school,standard,none,84,77,74,57,57,33,78.33
116,female,18,group B,bachelor's degree,free/reduced,none,75,85,82,63,18,4,80.67
117,female,80,group D,bachelor's degree,standard,none,78,82,79,51,80,77,79.67
118,female,88,group D,some high school,standard,none,51,63,61,88,88,25,58.33
119,female,68,group C,some college,standard,none,55,69,65,47,68,45,63.00
120,female,48,group C,bachelor's degree,standard,completed,79,92,89,69,48,10,86.67
121,male,98,group B,associate's degree,standard,completed,91,89,92,91,98,75,90.67
122,female,20,group C,some college,standard,completed,88,93,93,79,20,95,91.33
123,male,24,group D,high school,free/reduced,none,63,57,56,23,24,11,58.67
124,male,21,group E,some college,standard,none,83,80,73,32,21,4,78.67
125,female,30,group B,high school,standard,none,87,95,86,10,30,65,89.33
126,male,2,group B,some high school,standard,none,72,68,67,84,2,65,69.00
127,male,57,group D,some college,standard,completed,65,77,74,81,57,68,72.00
128,male,15,group D,master's degree,standard,none,82,82,74,73,15,52,79.33
129,female,98,group A,bachelor's degree,standard,none,51,49,51,78,98,87,50.33
130,male,99,group D,master's degree,standard,none,89,84,82,53,99,24,85.00
131,male,4,group C,some high school,free/reduced,completed,53,37,40,97,4,40,43.33
132,male,67,group E,some college,free/reduced,completed,87,74,70,16,67,61,77.00
133,female,80,group C,some college,standard,completed,75,81,84,55,80,42,80.00
134,male,51,group D,bachelor's degree,free/reduced,completed,74,79,75,38,51,59,76.00
135,male,36,group C,bachelor's degree,standard,none,58,55,48,22,36,48,53.67
136,male,33,group B,some high school,standard,completed,51,54,41,46,33,27,48.67
137,male,59,group E,high school,standard,none,70,55,56,52,59,86,60.33
138,female,58,group C,associate's degree,standard,none,59,66,67,14,58,19,64.00
139,male,60,group D,some college,standard,completed,71,61,69,58,60,10,67.00
140,female,11,group D,some high school,standard,none,76,72,71,13,11,67,73.00
141,female,49,group C,some college,free/reduced,none,59,62,64,48,49,80,61.67
142,female,62,group E,some college,free/reduced,completed,42,55,54,26,62,71,50.33
143,male,3,group A,high school,standard,none,57,43,47,47,3,2,49.00
144,male,16,group D,some college,standard,none,88,73,78,91,16,47,79.67
145,female,58,group C,some college,free/reduced,none,22,39,33,63,58,2,31.33
146,male,13,group B,some high school,standard,none,88,84,75,26,13,88,82.33
147,male,57,group C,associate's degree,free/reduced,none,73,68,66,17,57,93,69.00
148,female,70,group D,bachelor's degree,standard,completed,68,75,81,71,70,25,74.67
149,male,2,group E,associate's degree,free/reduced,completed,100,100,93,63,2,78,97.67
150,male,74,group A,some high school,standard,completed,62,67,69,77,74,57,66.00
151,male,75,group A,bachelor's degree,standard,none,77,67,68,74,75,84,70.67
152,female,78,group B,associate's degree,standard,completed,59,70,66,13,78,50,65.00
153,male,90,group D,bachelor's degree,standard,none,54,49,47,98,90,22,50.00
154,male,40,group D,some high school,standard,none,62,67,61,32,40,99,63.33
155,female,44,group C,some college,standard,completed,70,89,88,54,44,87,82.33
156,female,42,group E,high school,free/reduced,completed,66,74,78,25,42,25,72.67
157,male,89,group B,some college,free/reduced,none,60,60,60,88,89,36,60.00
158,female,39,group B,associate's degree,standard,completed,61,86,87,97,39,46,78.00
159,male,97,group D,associate's degree,free/reduced,none,66,62,64,19,97,46,64.00
160,male,41,group B,associate's degree,free/reduced,completed,82,78,74,53,41,54,78.00
161,female,62,group E,some college,free/reduced,completed,75,88,85,91,62,48,82.67
162,male,11,group B,master's degree,free/reduced,none,49,53,52,58,11,61,51.33
163,male,46,group C,high school,standard,none,52,53,49,20,46,97,51.33
164,female,52,group E,master's degree,standard,none,81,92,91,53,52,63,88.00
165,female,85,group C,bachelor's degree,standard,completed,96,100,100,72,85,82,98.67
166,male,13,group C,high school,free/reduced,completed,53,51,51,83,13,13,51.67
167,female,21,group B,master's degree,free/reduced,completed,58,76,78,99,21,35,70.67
168,female,4,group B,high school,standard,completed,68,83,78,39,4,79,76.33
169,female,63,group C,some college,free/reduced,completed,67,75,70,20,63,55,70.67
170,male,61,group A,high school,standard,completed,72,73,74,32,61,93,73.00
171,male,54,group E,some high school,standard,none,94,88,78,3,54,30,86.67
172,female,10,group D,some college,standard,none,79,86,81,7,10,60,82.00
173,female,51,group C,associate's degree,standard,none,63,67,70,19,51,42,66.67
174,female,40,group C,bachelor's degree,free/reduced,completed,43,51,54,6,40,37,49.33
175,female,1,group C,master's degree,standard,completed,81,91,87,50,1,17,86.33
176,female,28,group B,high school,free/reduced,completed,46,54,58,97,28,98,52.67
177,female,39,group C,associate's degree,standard,completed,71,77,77,33,39,31,75.00
178,female,76,group B,master's degree,free/reduced,completed,52,70,62,82,76,25,61.33
179,female,10,group D,some high school,standard,completed,97,100,100,63,10,22,99.00
180,male,62,group C,master's degree,free/reduced,completed,62,68,75,48,62,57,68.33
181,female,24,group C,some college,free/reduced,none,46,64,66,72,24,46,58.67
182,female,86,group E,high school,standard,none,50,50,47,90,86,6,49.00
183,female,68,group D,associate's degree,standard,none,65,69,70,47,68,86,68.00
184,male,39,group C,some high school,free/reduced,completed,45,52,49,67,39,8,48.67
185,male,62,group C,associate's degree,free/reduced,completed,65,67,65,21,62,51,65.67
186,male,64,group E,high school,standard,none,80,76,65,93,64,99,73.67
187,male,89,group D,some high school,standard,completed,62,66,68,98,89,35,65.33
188,male,41,group B,some high school,free/reduced,none,48,52,45,1,41,20,48.33
189,female,76,group C,bachelor's degree,standard,none,77,88,87,26,76,4,84.00
190,female,41,group E,associate's degree,standard,none,66,65,69,14,41,43,66.67
191,male,35,group D,some college,standard,completed,76,83,79,25,35,30,79.33
192,female,70,group B,some high school,standard,none,62,64,66,2,70,61,64.00
193,male,78,group D,some college,standard,completed,77,62,62,51,78,22,67.00
194,female,23,group C,master's degree,standard,completed,69,84,85,99,23,98,79.33
195,male,17,group D,associate's degree,standard,none,61,55,52,39,17,79,56.00
196,male,82,group C,some high school,free/reduced,completed,59,69,65,38,82,88,64.33
197,male,20,group E,high school,free/reduced,none,55,56,51,33,20,21,54.00
198,female,59,group B,some college,free/reduced,none,45,53,55,42,59,30,51.00
199,female,68,group B,bachelor's degree,free/reduced,none,78,79,76,24,68,97,77.67
200,female,18,group C,associate's degree,standard,completed,67,84,86,74,18,46,79.00
201,female,83,group D,some college,free/reduced,none,65,81,77,86,83,96,74.33
202,male,20,group C,associate's degree,standard,none,69,77,69,15,20,83,71.67
203,female,52,group B,associate's degree,standard,none,57,69,68,88,52,67,64.67
204,male,73,group C,some college,standard,none,59,41,42,45,73,45,47.33
205,male,21,group D,some high school,standard,completed,74,71,78,35,21,86,74.33
206,male,77,group E,bachelor's degree,standard,none,82,62,62,39,77,87,68.67
207,male,65,group E,high school,standard,completed,81,80,76,26,65,26,79.00
208,female,43,group B,some college,free/reduced,none,74,81,76,45,43,82,77.00
209,female,32,group B,some college,free/reduced,none,58,61,66,11,32,91,61.67
210,male,74,group D,some high school,free/reduced,completed,80,79,79,79,74,18,79.33
211,male,81,group C,some college,free/reduced,none,35,28,27,12,81,14,30.00
212,female,45,group C,high school,free/reduced,none,42,62,60,25,45,99,54.67
213,male,93,group C,associate's degree,free/reduced,completed,60,51,56,29,93,42,55.67
214,male,28,group E,high school,standard,completed,87,91,81,94,28,8,86.33
215,male,50,group B,some high school,standard,completed,84,83,75,51,50,45,80.67
216,female,71,group E,associate's degree,free/reduced,completed,83,86,88,24,71,12,85.67
217,female,39,group C,high school,free/reduced,none,34,42,39,71,39,16,38.33
218,male,97,group B,high school,free/reduced,none,66,77,70,42,97,49,71.00
219,male,78,group B,some high school,standard,completed,61,56,56,14,78,61,57.67
220,female,81,group D,high school,standard,completed,56,68,74,14,81,48,66.00
221,male,76,group B,associate's degree,standard,none,87,85,73,12,76,42,81.67
222,female,95,group C,some high school,free/reduced,none,55,65,62,15,95,56,60.67
223,male,50,group D,some high school,standard,none,86,80,75,38,50,29,80.33
224,female,35,group B,associate's degree,standard,completed,52,66,73,3,35,80,63.67
225,female,29,group E,master's degree,free/reduced,none,45,56,54,39,29,46,51.67
226,female,31,group C,some college,standard,none,72,72,71,59,31,5,71.67
227,male,54,group D,high school,standard,none,57,50,54,73,54,90,53.67
228,male,1,group A,some high school,free/reduced,none,68,72,64,49,1,81,68.00
229,female,91,group C,some college,standard,completed,88,95,94,1,91,89,92.33
230,male,64,group D,some college,standard,none,76,64,66,61,64,41,68.67
231,male,60,group C,associate's degree,standard,none,46,43,42,28,60,6,43.67
232,female,93,group B,bachelor's degree,standard,none,67,86,83,71,93,69,78.67
233,male,63,group E,some high school,standard,none,92,87,78,37,63,51,85.67
234,male,85,group C,bachelor's degree,standard,completed,83,82,84,58,85,57,83.00
235,male,7,group D,associate's degree,standard,none,80,75,77,47,7,6,77.33
236,male,67,group D,bachelor's degree,free/reduced,none,63,66,67,84,67,12,65.33
237,female,25,group D,some high school,standard,completed,64,60,74,73,25,99,66.00
238,male,2,group B,some college,standard,none,54,52,51,10,2,85,52.33
239,male,73,group C,associate's degree,standard,none,84,80,80,30,73,71,81.33
240,male,41,group D,high school,free/reduced,completed,73,68,66,53,41,6,69.00
241,female,10,group E,bachelor's degree,standard,none,80,83,83,83,10,96,82.00
242,female,30,group D,high school,standard,none,56,52,55,9,30,31,54.33
243,male,71,group E,some college,standard,none,59,51,43,67,71,70,51.00
244,male,13,group D,some high school,standard,none,75,74,69,2,13,71,72.67
245,male,21,group C,associate's degree,standard,none,85,76,71,52,21,53,77.33
246,male,77,group E,associate's degree,standard,none,89,76,74,86,77,6,79.67
247,female,99,group B,high school,standard,completed,58,70,68,51,99,15,65.33
248,female,96,group B,high school,standard,none,65,64,62,15,96,21,63.67
249,male,22,group C,high school,standard,none,68,60,53,4,22,46,60.33
250,male,97,group A,some high school,standard,completed,47,49,49,26,97,30,48.33
251,female,37,group D,some college,free/reduced,none,71,83,83,97,37,93,79.00
252,female,24,group B,some high school,standard,completed,60,70,70,35,24,15,66.67
253,male,5,group D,master's degree,standard,none,80,80,72,7,5,7,77.33
254,male,14,group D,high school,standard,none,54,52,52,88,14,86,52.67
255,female,67,group E,some college,standard,none,62,73,70,96,67,5,68.33
256,female,30,group C,associate's degree,free/reduced,none,64,73,68,98,30,96,68.33

# Value Counts

In [76]:
# counting gender elements

# len function
len(df_exams['gender'])
# .count() method
df_exams['gender'].count()

1000

In [77]:
# conting gender elements by category
df_exams['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [78]:
# return the relative frequency (divide all values by the sum of values)
df_exams['gender'].value_counts(normalize=True)

gender
female    0.518
male      0.482
Name: proportion, dtype: float64

In [79]:
# counting "parental level of education" elements by category
df_exams['parental level of education'].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [81]:
# return the relative frequency and round to 2 decimals
df_exams['parental level of education'].value_counts(normalize=True).round(2)

parental level of education
some college          0.23
associate's degree    0.22
high school           0.20
some high school      0.18
bachelor's degree     0.12
master's degree       0.06
Name: proportion, dtype: float64

# 1 Sort a dataframe

In [82]:
# select by one column
df_exams.sort_values(by='math score')

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,HR_score,logistics,average
59,female,79,group C,some high school,free/reduced,none,0,17,10,28,79,73,9.000000
980,female,23,group B,high school,free/reduced,none,8,24,23,98,23,69,18.333333
17,female,31,group B,some high school,free/reduced,none,18,32,28,82,31,54,26.000000
787,female,90,group B,some college,standard,none,19,38,32,18,90,59,29.666667
145,female,58,group C,some college,free/reduced,none,22,39,33,63,58,2,31.333333
842,female,61,group B,high school,free/reduced,completed,23,44,36,71,61,95,34.333333
338,female,55,group B,some high school,free/reduced,none,24,38,27,44,55,77,29.666667
466,female,71,group D,associate's degree,free/reduced,none,26,31,38,50,71,78,31.666667
91,male,13,group C,high school,free/reduced,none,27,34,36,70,13,97,32.333333
363,female,48,group D,some high school,free/reduced,none,27,34,32,88,48,76,31.000000
327,male,18,group A,some college,free/reduced,none,28,23,19,67,18,93,23.333333
528,female,89,group D,bachelor's degree,free/reduced,none,29,41,47,54,89,85,39.000000
601,female,36,group C,high school,standard,none,29,29,30,14,36,47,29.333333
683,female,41,group C,some high school,free/reduced,completed,29,40,44,74,41,83,37.666667
76,male,20,group E,some high school,standard,none,30,26,22,71,20,52,26.000000
596,male,23,group B,high school,free/reduced,none,30,24,15,86,23,66,23.000000
555,female,77,group C,some college,free/reduced,none,32,39,33,6,77,13,34.666667
785,female,83,group B,some high school,standard,completed,32,51,44,61,83,36,42.333333
895,female,15,group E,some high school,free/reduced,none,32,34,38,9,15,39,34.666667
55,female,50,group C,high school,free/reduced,none,33,41,43,18,50,62,39.000000
902,female,81,group A,high school,free/reduced,completed,34,48,41,32,81,37,41.000000
217,female,39,group C,high school,free/reduced,none,34,42,39,71,39,16,38.333333
211,male,81,group C,some college,free/reduced,none,35,28,27,12,81,14,30.000000
620,female,20,group C,high school,free/reduced,none,35,61,54,23,20,27,50.000000
777,female,45,group C,some college,free/reduced,none,35,44,43,74,45,63,40.666667
921,female,16,group C,high school,free/reduced,none,35,53,46,25,16,13,44.666667
339,female,42,group D,some high school,free/reduced,completed,35,55,60,27,42,99,50.000000
527,female,73,group C,high school,free/reduced,none,36,53,43,30,73,69,44.000000
896,male,99,group B,high school,free/reduced,none,36,29,27,75,99,49,30.666667
616,female,69,group E,bachelor's degree,standard,none,37,45,38,80,69,49,40.000000
284,female,49,group B,some high school,standard,none,37,46,46,8,49,86,43.000000
455,male,79,group C,bachelor's degree,free/reduced,none,37,56,47,31,79,63,46.666667
741,female,16,group A,associate's degree,free/reduced,none,37,57,56,36,16,83,50.000000
384,female,55,group A,some high school,free/reduced,none,38,43,43,84,55,62,41.333333
9,female,92,group B,high school,free/reduced,none,38,60,50,1,92,97,49.333333
383,female,85,group E,some high school,free/reduced,none,38,49,45,34,85,22,44.000000
840,female,56,group D,high school,free/reduced,none,39,52,46,7,56,34,45.666667
61,male,75,group A,some high school,free/reduced,none,39,39,34,10,75,64,37.333333
862,male,91,group D,bachelor's degree,free/reduced,completed,39,42,38,92,91,12,39.666667
69,female,30,group C,associate's degree,standard,none,39,64,57,24,30,45,53.333333
552,female,71,group B,associate's degree,standard,none,40,48,50,56,71,62,46.000000
607,female,5,group C,master's degree,free/reduced,none,40,58,54,69,5,30,50.666667
986,female,61,group C,associate's degree,standard,none,40,59,51,61,61,64,50.000000
844,female,10,group D,some high school,free/reduced,completed,40,65,64,86,10,56,56.333333
575,male,30,group A,associate's degree,free/reduced,completed,40,55,53,74,30,26,49.333333
504,female,66,group D,master's degree,free/reduced,none,40,59,54,57,66,8,51.000000
7,male,94,group B,some college,free/reduced,none,40,43,39,98,94,22,40.666667
33,male,39,group D,some college,standard,none,40,42,38,78,39,16,40.000000
298,male,59,group C,high school,free/reduced,completed,40,46,50,4,59,36,45.333333
11,male,36,group D,associate's degree,standard,none,40,52,43,8,36,90,45.000000
72,female,37,group A,associate's degree,free/reduced,none,41,51,48,14,37,20,46.666667
640,male,71,group D,high school,standard,none,41,52,51,72,71,69,48.000000
807,female,56,group E,high school,free/reduced,none,41,45,40,90,56,69,42.000000
329,female,30,group B,some high school,standard,none,41,55,51,95,30,72,49.000000
424,male,52,group B,some college,free/reduced,none,41,39,34,83,52,98,38.000000
324,female,30,group C,high school,free/reduced,none,41,46,43,97,30,35,43.333333
142,female,62,group E,some college,free/reduced,completed,42,55,54,26,62,71,50.333333
212,female,45,group C,high school,free/reduced,none,42,62,60,25,45,99,54.666667
84,male,89,group D,high school,free/reduced,none,42,39,34,81,89,96,38.333333
357,female,26,group C,some college,free/reduced,completed,42,66,69,48,26,33,59.000000
709,female,14,group D,associate's degree,free/reduced,completed,42,61,58,84,14,90,53.666667
794,female,10,group B,high school,standard,none,42,52,51,94,10,57,48.333333
874,female,58,group C,bachelor's degree,free/reduced,none,43,62,61,73,58,52,55.333333
323,female,30,group C,some high school,free/reduced,none,43,53,53,57,30,16,49.666667
658,female,32,group D,associate's degree,free/reduced,none,43,60,58,96,32,18,53.666667
93,male,36,group C,associate's degree,free/reduced,completed,43,45,50,9,36,42,46.000000
174,female,40,group C,bachelor's degree,free/reduced,completed,43,51,54,6,40,37,49.333333
988,female,95,group A,some high school,free/reduced,none,44,45,45,62,95,80,44.666667
587,female,87,group C,bachelor's degree,free/reduced,none,44,63,62,7,87,53,56.333333
262,female,62,group C,some high school,free/reduced,none,44,50,51,27,62,98,48.333333
368,female,90,group A,some high school,free/reduced,none,44,64,58,85,90,92,55.333333
629,female,59,group C,some high school,standard,completed,44,51,55,3,59,48,50.000000
75,male,42,group B,associate's degree,free/reduced,none,44,41,38,82,42,81,41.000000
22,male,1,group D,some college,standard,none,44,54,53,23,1,1,50.333333
889,male,44,group D,high school,free/reduced,none,44,51,48,45,44,21,47.666667
917,female,87,group C,high school,standard,none,44,61,52,52,87,41,52.333333
281,male,42,group D,high school,standard,none,45,48,46,56,42,93,46.333333
184,male,39,group C,some high school,free/reduced,completed,45,52,49,67,39,8,48.666667
198,female,59,group B,some college,free/reduced,none,45,53,55,42,59,30,51.000000
816,female,17,group A,bachelor's degree,standard,none,45,59,64,64,17,36,56.000000
811,male,31,group A,high school,free/reduced,none,45,47,49,54,31,78,47.000000
66,male,58,group D,some high school,free/reduced,none,45,37,37,93,58,55,39.666667
225,female,29,group E,master's degree,free/reduced,none,45,56,54,39,29,46,51.666667
958,female,89,group D,high school,standard,none,45,63,59,36,89,96,55.666667
371,female,26,group C,some college,free/reduced,completed,45,73,70,50,26,71,62.666667
296,male,64,group A,some high school,standard,completed,46,41,43,68,64,25,43.333333
231,male,60,group C,associate's degree,standard,none,46,43,42,28,60,6,43.666667
375,male,10,group E,associate's degree,free/reduced,none,46,43,41,22,10,42,43.333333
914,female,16,group B,associate's degree,free/reduced,none,46,61,55,56,16,65,54.000000
928,male,13,group E,associate's degree,free/reduced,completed,46,43,44,11,13,84,44.333333
353,female,99,group C,associate's degree,standard,none,46,58,57,54,99,10,53.666667
706,male,15,group D,high school,standard,none,46,34,36,37,15,27,38.666667
780,female,75,group D,associate's degree,free/reduced,none,46,56,57,30,75,34,53.000000
181,female,24,group C,some college,free/reduced,none,46,64,66,72,24,46,58.666667
18,male,89,group C,master's degree,free/reduced,completed,46,42,46,40,89,36,44.666667
176,female,28,group B,high school,free/reduced,completed,46,54,58,97,28,98,52.666667
3,male,80,group A,associate's degree,free/reduced,none,47,57,44,96,80,77,49.333333
433,female,48,group A,some high school,free/reduced,none,47,59,50,68,48,43,52.000000
531,female,58,group C,some high school,standard,none,47,54,53,38,58,11,51.333333
913,female,84,group C,bachelor's degree,free/reduced,completed,47,62,66,72,84,94,58.333333
724,male,61,group B,some college,standard,none,47,43,41,74,61,13,43.666667
250,male,97,group A,some high school,standard,completed,47,49,49,26,97,30,48.333333
422,female,66,group D,master's degree,free/reduced,completed,47,58,67,32,66,16,57.333333
331,male,69,group C,associate's degree,standard,none,47,37,35,3,69,60,39.666667
80,female,18,group B,associate's degree,standard,none,47,49,50,17,18,64,48.666667
272,female,32,group D,associate's degree,free/reduced,none,47,53,58,66,32,22,52.666667
448,male,81,group B,high school,standard,none,47,46,42,77,81,90,45.000000
589,female,90,group A,some high school,standard,none,48,66,65,63,90,42,59.666667
961,female,86,group D,some high school,free/reduced,none,48,54,53,8,86,16,51.666667
578,female,91,group B,some college,free/reduced,completed,48,56,58,1,91,94,54.000000
761,female,5,group D,some high school,standard,none,48,58,54,78,5,64,53.333333
395,male,99,group A,high school,free/reduced,none,48,45,41,30,99,40,44.666667
929,female,75,group C,some high school,free/reduced,none,48,56,51,64,75,38,51.666667
790,female,34,group B,high school,standard,none,48,62,60,57,34,88,56.666667
565,male,73,group B,associate's degree,standard,none,48,43,45,68,73,57,45.333333
564,male,33,group B,bachelor's degree,free/reduced,none,48,51,46,38,33,15,48.333333
188,male,41,group B,some high school,free/reduced,none,48,52,45,1,41,20,48.333333
824,female,50,group C,some high school,free/reduced,none,48,58,52,81,50,51,52.666667
309,female,76,group D,high school,free/reduced,none,49,57,52,85,76,96,52.666667
947,female,6,group D,some college,free/reduced,none,49,58,60,80,6,81,55.666667
162,male,11,group B,master's degree,free/reduced,none,49,53,52,58,11,61,51.333333
869,male,77,group C,associate's degree,free/reduced,none,49,51,51,23,77,74,50.333333
694,female,35,group C,some high school,standard,none,49,63,56,37,35,97,56.000000
690,female,34,group C,associate's degree,standard,none,49,53,53,47,34,51,51.666667
822,male,90,group E,some college,free/reduced,completed,49,52,51,5,90,13,50.666667
484,female,17,group B,associate's degree,standard,none,49,52,54,94,17,18,51.666667
337,male,39,group C,associate's degree,standard,none,49,51,43,68,39,45,47.666667
948,male,40,group B,some high school,free/reduced,completed,49,50,52,29,40,69,50.333333
365,male,43,group A,bachelor's degree,free/reduced,completed,49,58,60,39,43,29,55.666667
81,male,70,group B,high school,free/reduced,none,49,45,45,68,70,1,46.333333
74,male,69,group C,some high school,standard,none,49,49,41,43,69,26,46.333333
775,female,87,group B,some high school,free/reduced,none,49,58,55,26,87,82,54.000000
402,female,66,group A,some college,free/reduced,none,49,65,55,70,66,1,56.333333
628,male,7,group D,some college,free/reduced,none,49,57,46,89,7,91,50.666667
973,female,60,group D,some college,free/reduced,none,49,65,61,38,60,82,58.333333
892,female,54,group A,master's degree,free/reduced,none,50,67,73,59,54,46,63.333333
182,female,86,group E,high school,standard,none,50,50,47,90,86,6,49.000000
82,male,10,group A,some college,free/reduced,completed,50,47,54,64,10,61,50.333333
675,female,38,group B,some college,standard,completed,50,64,66,4,38,85,60.000000
44,female,6,group E,associate's degree,free/reduced,none,50,56,54,96,6,63,53.333333
435,male,70,group C,some college,free/reduced,completed,50,48,53,13,70,53,50.333333
37,female,24,group D,some high school,free/reduced,none,50,64,59,36,24,35,57.666667
910,male,96,group D,bachelor's degree,free/reduced,none,50,42,48,40,96,41,46.666667
665,female,43,group C,some high school,free/reduced,completed,50,60,60,11,43,71,56.666667
723,male,20,group C,high school,standard,none,50,48,42,39,20,54,46.666667
396,female,84,group B,high school,free/reduced,none,50,67,63,88,84,89,60.000000
648,female,50,group B,high school,standard,none,50,53,55,42,50,3,52.666667
748,female,90,group C,bachelor's degree,free/reduced,none,50,60,59,37,90,37,56.333333
14,female,4,group A,master's degree,standard,none,50,53,58,90,4,7,53.666667
573,female,24,group C,high school,free/reduced,completed,50,66,64,27,24,74,60.000000
650,male,26,group C,some high school,free/reduced,completed,51,56,53,99,26,25,53.333333
136,male,33,group B,some high school,standard,completed,51,54,41,46,33,27,48.666667
129,female,98,group A,bachelor's degree,standard,none,51,49,51,78,98,87,50.333333
884,female,52,group E,associate's degree,standard,none,51,51,54,19,52,68,52.000000
537,female,3,group D,high school,standard,none,51,66,62,70,3,43,59.666667
414,female,83,group C,bachelor's degree,free/reduced,completed,51,72,79,23,83,7,67.333333
536,male,71,group C,associate's degree,standard,completed,51,60,58,57,71,98,56.333333
307,male,85,group C,some high school,standard,none,51,52,44,64,85,17,49.000000
118,female,88,group D,some high school,standard,none,51,63,61,88,88,25,58.333333
113,female,27,group D,some college,standard,none,51,58,54,6,27,45,54.333333
810,male,66,group A,some high school,standard,none,51,31,36,33,66,39,39.333333
224,female,35,group B,associate's degree,standard,completed,52,66,73,3,35,80,63.666667
481,female,11,group D,associate's degree,free/reduced,none,52,59,56,55,11,34,55.666667
57,male,75,group D,associate's degree,standard,none,52,55,49,19,75,64,52.000000
912,female,41,group C,bachelor's degree,standard,completed,52,61,66,3,41,35,59.666667
671,male,21,group D,associate's degree,free/reduced,none,52,57,50,33,21,4,53.000000
789,female,55,group C,master's degree,free/reduced,none,52,65,61,1,55,35,59.333333
858,male,59,group B,high school,standard,completed,52,49,46,6,59,43,49.000000
772,female,45,group B,some high school,free/reduced,completed,52,67,72,73,45,65,63.666667
178,female,76,group B,master's degree,free/reduced,completed,52,70,62,82,76,25,61.333333
758,female,72,group D,some college,free/reduced,completed,52,59,65,73,72,89,58.666667
770,male,25,group B,high school,standard,none,52,48,49,1,25,90,49.666667
799,female,34,group C,associate's degree,standard,none,52,55,57,72,34,43,54.666667
408,female,83,group D,high school,free/reduced,completed,52,57,56,66,83,27,55.000000
362,female,5,group C,some college,standard,none,52,58,58,37,5,56,56.000000
783,female,90,group C,associate's degree,standard,completed,52,59,62,68,90,26,57.666667
163,male,46,group C,high school,standard,none,52,53,49,20,46,97,51.333333
108,female,45,group B,associate's degree,free/reduced,none,52,76,70,36,45,80,66.000000
350,female,17,group B,bachelor's degree,standard,none,52,65,69,47,17,8,62.000000
166,male,13,group C,high school,free/reduced,completed,53,51,51,83,13,13,51.666667
524,male,29,group C,high school,standard,completed,53,52,49,49,29,95,51.333333
280,male,25,group D,high school,standard,none,53,52,42,40,25,34,49.000000
42,female,17,group B,associate's degree,standard,none,53,58,65,42,17,26,58.666667
457,male,77,group D,associate's degree,free/reduced,none,53,54,48,56,77,1,51.666667
50,male,66,group E,some college,standard,none,53,55,48,98,66,86,52.000000
52,male,31,group C,some college,standard,none,53,44,42,71,31,44,46.333333
308,female,11,group B,associate's degree,free/reduced,none,53,71,67,5,11,53,63.666667
737,female,43,group B,some college,free/reduced,completed,53,66,73,3,43,21,64.000000
454,female,18,group C,associate's degree,free/reduced,none,53,61,62,35,18,24,58.666667
688,male,52,group A,high school,free/reduced,none,53,58,44,34,52,25,51.666667
860,female,42,group C,associate's degree,standard,none,53,62,53,91,42,66,56.000000
401,male,58,group A,some college,standard,none,53,43,43,37,58,55,46.333333
460,male,39,group C,bachelor's degree,free/reduced,none,53,58,55,37,39,21,55.333333
729,male,12,group C,some college,standard,none,53,39,37,63,12,25,43.000000
597,male,31,group A,some high school,standard,none,53,54,48,49,31,40,51.666667
734,female,25,group E,some college,free/reduced,none,53,58,57,99,25,38,56.000000
572,female,23,group C,some college,standard,none,53,62,56,92,23,36,57.000000
131,male,4,group C,some high school,free/reduced,completed,53,37,40,97,4,40,43.333333
760,female,84,group C,high school,free/reduced,none,53,72,64,76,84,45,63.000000
972,female,54,group A,high school,free/reduced,completed,53,50,60,35,54,18,54.333333
558,female,99,group B,associate's degree,free/reduced,none,53,70,70,3,99,77,64.333333
554,male,16,group E,associate's degree,standard,none,53,45,40,36,16,55,46.000000
579,female,27,group D,master's degree,standard,none,53,61,68,9,27,59,60.666667
523,male,87,group C,master's degree,free/reduced,none,54,59,50,97,87,13,54.333333
461,male,17,group B,some college,free/reduced,none,54,54,45,3,17,42,51.000000
513,female,53,group B,some high school,standard,completed,54,61,62,6,53,6,59.000000
153,male,90,group D,bachelor's degree,standard,none,54,49,47,98,90,22,50.000000
112,male,78,group A,associate's degree,standard,none,54,53,47,30,78,62,51.333333
254,male,14,group D,high school,standard,none,54,52,52,88,14,86,52.666667
19,female,31,group C,associate's degree,free/reduced,none,54,58,61,67,31,27,57.666667
494,female,40,group B,high school,standard,none,54,64,68,12,40,50,62.000000
496,female,11,group C,some college,standard,none,54,48,52,48,11,42,51.333333
238,male,2,group B,some college,standard,none,54,52,51,10,2,85,52.333333
923,female,16,group B,associate's degree,free/reduced,none,54,65,65,79,16,12,61.333333
812,female,10,group C,master's degree,standard,completed,54,64,67,91,10,36,61.666667
945,female,86,group C,associate's degree,standard,none,54,61,58,32,86,73,57.666667
974,female,30,group A,some college,standard,none,54,63,67,17,30,14,61.333333
588,female,1,group C,some college,standard,none,54,64,65,69,1,87,61.000000
887,male,73,group C,high school,free/reduced,none,54,72,59,57,73,10,61.666667
600,female,57,group D,master's degree,standard,none,54,60,63,59,57,99,59.000000
404,female,76,group C,high school,standard,none,54,59,62,97,76,11,58.333333
733,male,52,group D,some high school,standard,none,55,47,44,45,52,54,48.666667
197,male,20,group E,high school,free/reduced,none,55,56,51,33,20,21,54.000000
40,male,5,group C,associate's degree,free/reduced,none,55,61,54,45,5,32,56.666667
992,female,10,group D,associate's degree,free/reduced,none,55,76,76,54,10,69,69.000000
883,male,27,group D,bachelor's degree,free/reduced,none,55,46,44,9,27,7,48.333333
731,male,88,group A,some high school,free/reduced,none,55,46,43,96,88,35,48.000000
46,female,53,group A,associate's degree,standard,completed,55,65,62,87,53,30,60.666667
478,female,89,group D,master's degree,standard,none,55,64,70,1,89,35,63.000000
556,female,95,group C,associate's degree,standard,completed,55,72,79,37,95,67,68.666667
744,male,47,group B,some college,free/reduced,none,55,55,47,5,47,72,52.333333
756,male,22,group D,some college,standard,none,55,58,52,65,22,16,55.000000
507,male,58,group B,bachelor's degree,free/reduced,none,55,59,54,81,58,22,56.000000
222,female,95,group C,some high school,free/reduced,none,55,65,62,15,95,56,60.666667
721,male,32,group D,some high school,free/reduced,completed,55,59,59,50,32,7,57.666667
586,female,4,group A,high school,standard,none,55,73,73,98,4,90,67.000000
662,female,5,group D,some college,free/reduced,none,55,71,69,48,5,6,65.000000
119,female,68,group C,some college,standard,none,55,69,65,47,68,45,63.000000
978,male,66,group D,high school,standard,completed,55,41,48,99,66,49,48.000000
319,female,29,group D,associate's degree,free/reduced,none,56,65,63,87,29,61,61.333333
595,female,96,group C,bachelor's degree,standard,completed,56,79,72,87,96,79,69.000000
32,female,13,group E,master's degree,free/reduced,none,56,72,65,44,13,30,64.333333

In [83]:
# sort descending by one column
df_exams.sort_values(by='math score',ascending=False)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,HR_score,logistics,average
962,female,49,group E,associate's degree,standard,none,100,100,100,47,49,99,100.000000
625,male,48,group D,some college,standard,completed,100,97,99,89,48,75,98.666667
458,female,30,group E,bachelor's degree,standard,none,100,100,100,61,30,57,100.000000
623,male,84,group A,some college,standard,completed,100,96,86,16,84,44,94.000000
451,female,6,group E,some college,standard,none,100,92,97,2,6,77,96.333333
149,male,2,group E,associate's degree,free/reduced,completed,100,100,93,63,2,78,97.666667
916,male,12,group E,bachelor's degree,standard,completed,100,100,100,83,12,90,100.000000
263,female,2,group E,high school,standard,none,99,93,90,91,2,24,94.000000
306,male,27,group E,some college,standard,completed,99,87,81,46,27,12,89.000000
114,female,68,group E,bachelor's degree,standard,completed,99,100,100,7,68,18,99.666667
104,male,78,group C,some college,standard,completed,98,86,90,34,78,99,91.333333
934,male,2,group C,associate's degree,standard,completed,98,87,90,48,2,51,91.666667
712,female,90,group D,some college,standard,none,98,100,99,90,90,28,99.000000
539,male,2,group A,associate's degree,standard,completed,97,92,86,87,2,32,91.666667
855,female,50,group B,bachelor's degree,standard,none,97,97,96,10,50,49,96.666667
179,female,10,group D,some high school,standard,completed,97,100,100,63,10,22,99.000000
864,male,89,group C,associate's degree,standard,none,97,93,91,3,89,17,93.666667
286,male,13,group E,associate's degree,standard,completed,97,82,88,45,13,67,89.000000
34,male,89,group E,some college,standard,none,97,87,82,12,89,22,88.666667
562,male,22,group C,bachelor's degree,standard,completed,96,90,92,1,22,4,92.666667
717,female,87,group C,associate's degree,standard,completed,96,96,99,55,87,95,97.000000
165,female,85,group C,bachelor's degree,standard,completed,96,100,100,72,85,82,98.666667
503,female,39,group E,associate's degree,standard,completed,95,89,92,23,39,70,92.000000
618,male,8,group D,master's degree,standard,none,95,81,84,37,8,31,86.666667
612,male,60,group C,bachelor's degree,standard,completed,94,90,91,30,60,68,91.666667
501,female,94,group B,associate's degree,standard,completed,94,87,92,23,94,18,91.000000
779,male,85,group E,associate's degree,standard,completed,94,85,82,76,85,16,87.000000
815,male,40,group B,some high school,standard,completed,94,86,87,98,40,97,89.000000
171,male,54,group E,some high school,standard,none,94,88,78,3,54,30,86.666667
950,male,69,group E,high school,standard,none,94,73,71,24,69,19,79.333333
685,female,84,group E,master's degree,standard,completed,94,99,100,78,84,55,97.666667
689,male,58,group E,some college,free/reduced,none,93,90,83,61,58,63,88.666667
710,male,95,group C,some college,standard,completed,93,84,90,26,95,80,89.000000
903,female,9,group D,bachelor's degree,free/reduced,completed,93,100,100,30,9,28,97.666667
886,female,99,group E,associate's degree,standard,completed,93,100,95,67,99,44,96.000000
546,female,68,group A,some high school,standard,completed,92,100,97,38,68,41,96.333333
566,female,66,group E,bachelor's degree,free/reduced,completed,92,100,100,96,66,51,97.333333
957,female,27,group D,master's degree,standard,none,92,100,100,88,27,43,97.333333
594,female,5,group C,bachelor's degree,standard,completed,92,100,99,2,5,15,97.000000
736,male,43,group C,associate's degree,standard,none,92,79,84,16,43,90,85.000000
233,male,63,group E,some high school,standard,none,92,87,78,37,63,51,85.666667
121,male,98,group B,associate's degree,standard,completed,91,89,92,91,98,75,90.666667
571,male,9,group A,bachelor's degree,standard,none,91,96,92,52,9,11,93.000000
719,male,89,group E,associate's degree,free/reduced,completed,91,73,80,17,89,98,81.333333
784,male,35,group C,bachelor's degree,standard,completed,91,81,79,47,35,85,83.666667
846,male,19,group C,master's degree,standard,completed,91,85,85,72,19,68,87.000000
521,female,86,group C,associate's degree,standard,none,91,86,84,3,86,78,87.000000
469,male,89,group C,some college,standard,none,91,74,76,90,89,27,80.333333
979,female,99,group C,associate's degree,standard,none,91,95,94,40,99,86,93.333333
919,male,80,group B,some college,standard,completed,91,96,91,14,80,78,92.666667
845,male,81,group E,master's degree,standard,none,90,85,84,96,81,17,86.333333
873,male,14,group E,associate's degree,free/reduced,none,90,90,82,32,14,84,87.333333
659,male,82,group D,associate's degree,standard,none,90,87,85,89,82,4,87.333333
808,male,9,group C,high school,standard,none,90,75,69,56,9,38,78.000000
2,female,62,group B,master's degree,standard,none,90,95,93,15,62,98,92.666667
474,female,11,group B,associate's degree,standard,completed,90,90,91,48,11,17,90.333333
333,male,58,group B,associate's degree,standard,none,90,78,81,72,58,49,83.000000
299,male,10,group D,associate's degree,free/reduced,none,90,87,75,38,10,41,84.000000
439,male,49,group D,some high school,standard,completed,89,88,82,74,49,90,86.333333
970,female,60,group D,bachelor's degree,standard,none,89,100,100,4,60,74,96.333333
793,male,73,group E,some high school,standard,completed,89,84,77,73,73,99,83.333333
130,male,99,group D,master's degree,standard,none,89,84,82,53,99,24,85.000000
246,male,77,group E,associate's degree,standard,none,89,76,74,86,77,6,79.666667
708,male,12,group D,high school,standard,none,89,87,79,22,12,90,85.000000
995,female,8,group E,master's degree,standard,completed,88,99,95,35,8,63,94.000000
122,female,20,group C,some college,standard,completed,88,93,93,79,20,95,91.333333
403,female,77,group D,high school,standard,completed,88,99,100,43,77,34,95.666667
288,male,15,group B,bachelor's degree,free/reduced,none,88,75,76,92,15,44,79.666667
617,male,15,group D,bachelor's degree,standard,none,88,78,83,26,15,47,83.000000
146,male,13,group B,some high school,standard,none,88,84,75,26,13,88,82.333333
53,male,48,group D,high school,standard,none,88,78,75,83,48,58,80.333333
893,male,71,group D,some high school,standard,completed,88,74,75,78,71,32,79.000000
268,female,30,group D,associate's degree,standard,completed,88,92,95,71,30,1,91.666667
144,male,16,group D,some college,standard,none,88,73,78,91,16,47,79.666667
905,male,85,group D,some college,standard,none,88,77,77,94,85,6,80.666667
6,female,32,group B,some college,standard,completed,88,95,92,94,32,68,91.666667
274,male,39,group B,some college,standard,completed,88,85,76,67,39,12,83.000000
229,female,91,group C,some college,standard,completed,88,95,94,1,91,89,92.333333
16,male,67,group C,high school,standard,none,88,89,86,40,67,33,87.666667
732,female,16,group C,some college,standard,completed,87,89,94,77,16,94,90.000000
125,female,30,group B,high school,standard,none,87,95,86,10,30,65,89.333333
106,female,71,group D,master's degree,standard,none,87,100,100,12,71,50,95.666667
221,male,76,group B,associate's degree,standard,none,87,85,73,12,76,42,81.666667
749,male,51,group B,some college,standard,completed,87,84,86,78,51,8,85.666667
409,male,64,group D,associate's degree,standard,completed,87,84,85,3,64,5,85.333333
702,male,40,group A,bachelor's degree,standard,completed,87,84,87,6,40,76,86.000000
381,male,17,group C,associate's degree,standard,completed,87,100,95,94,17,37,94.000000
551,male,40,group B,bachelor's degree,free/reduced,completed,87,90,88,77,40,91,88.333333
852,female,68,group E,some college,standard,none,87,85,93,38,68,82,88.333333
349,male,94,group E,associate's degree,standard,none,87,74,76,80,94,80,79.000000
132,male,67,group E,some college,free/reduced,completed,87,74,70,16,67,61,77.000000
813,male,62,group E,some high school,standard,completed,87,84,76,78,62,31,82.333333
859,male,45,group C,associate's degree,free/reduced,none,87,73,72,82,45,32,77.333333
802,female,31,group E,associate's degree,standard,none,87,94,95,13,31,48,92.000000
214,male,28,group E,high school,standard,completed,87,91,81,94,28,8,86.333333
509,female,12,group C,bachelor's degree,standard,none,86,92,87,44,12,42,88.333333
447,male,94,group C,high school,standard,completed,86,81,80,46,94,89,82.333333
291,male,10,group D,some high school,standard,none,86,73,70,91,10,41,76.333333
990,male,86,group E,high school,free/reduced,completed,86,81,75,18,86,51,80.666667
223,male,50,group D,some high school,standard,none,86,80,75,38,50,29,80.333333
426,male,50,group C,bachelor's degree,standard,none,86,83,86,93,50,63,85.000000
638,male,9,group E,some college,standard,none,86,76,74,55,9,35,78.666667
890,female,14,group E,some college,standard,completed,86,85,91,83,14,26,87.333333
397,female,43,group C,associate's degree,standard,none,85,89,95,72,43,62,89.666667
538,male,9,group E,bachelor's degree,standard,completed,85,66,71,85,9,18,74.000000
900,male,57,group D,master's degree,standard,none,85,84,89,20,57,1,86.000000
686,male,42,group E,some college,standard,completed,85,75,68,84,42,96,76.000000
891,female,26,group E,associate's degree,standard,none,85,92,85,77,26,57,87.333333
361,male,18,group B,some high school,standard,completed,85,84,78,38,18,54,82.333333
276,female,92,group C,some high school,standard,completed,85,92,93,53,92,37,90.000000
245,male,21,group C,associate's degree,standard,none,85,76,71,52,21,53,77.333333
377,female,25,group D,master's degree,free/reduced,completed,85,95,100,63,25,65,93.333333
606,female,17,group C,associate's degree,standard,none,85,84,82,72,17,42,83.666667
938,male,99,group D,some college,standard,completed,85,81,85,69,99,35,83.666667
820,female,66,group A,some high school,standard,completed,85,90,92,43,66,97,89.000000
102,female,22,group D,associate's degree,standard,none,85,91,89,85,22,95,88.333333
652,female,20,group D,some college,standard,completed,85,86,98,23,20,9,89.666667
215,male,50,group B,some high school,standard,completed,84,83,75,51,50,45,80.666667
465,female,90,group C,some college,standard,none,84,87,91,80,90,15,87.333333
956,male,18,group C,some college,standard,none,84,87,81,96,18,84,84.000000
634,male,19,group D,some high school,standard,none,84,84,80,4,19,51,82.666667
755,female,52,group E,associate's degree,standard,none,84,95,92,76,52,94,90.333333
239,male,73,group C,associate's degree,standard,none,84,80,80,30,73,71,81.333333
370,male,84,group E,some college,standard,none,84,77,71,37,84,45,77.333333
411,male,13,group E,some college,standard,completed,84,83,78,27,13,69,81.666667
415,male,21,group E,high school,standard,none,84,73,69,72,21,41,75.333333
115,male,57,group C,high school,standard,none,84,77,74,57,57,33,78.333333
604,male,92,group D,master's degree,free/reduced,completed,84,89,90,27,92,55,87.666667
216,female,71,group E,associate's degree,free/reduced,completed,83,86,88,24,71,12,85.666667
470,female,62,group C,associate's degree,standard,completed,83,85,90,46,62,89,86.000000
492,female,59,group C,some college,standard,none,83,83,90,42,59,27,85.333333
317,male,91,group C,associate's degree,standard,none,83,72,78,96,91,54,77.666667
334,female,66,group C,bachelor's degree,standard,none,83,93,95,46,66,81,90.333333
124,male,21,group E,some college,standard,none,83,80,73,32,21,4,78.666667
234,male,85,group C,bachelor's degree,standard,completed,83,82,84,58,85,57,83.000000
275,male,75,group C,bachelor's degree,standard,none,83,78,73,99,75,44,78.000000
56,female,81,group E,associate's degree,standard,completed,82,85,86,35,81,40,84.333333
505,female,50,group B,some high school,standard,none,82,82,80,77,50,68,81.333333
853,male,22,group E,some high school,standard,none,82,67,61,64,22,86,70.000000
128,male,15,group D,master's degree,standard,none,82,82,74,73,15,52,79.333333
614,female,10,group A,associate's degree,standard,none,82,93,93,52,10,2,89.333333
325,female,20,group C,some college,standard,none,82,90,94,28,20,39,88.666667
543,female,47,group D,associate's degree,standard,none,82,95,89,48,47,86,88.666667
160,male,41,group B,associate's degree,free/reduced,completed,82,78,74,53,41,54,78.000000
420,female,9,group C,associate's degree,free/reduced,completed,82,93,93,28,9,45,89.333333
865,male,14,group D,some college,standard,completed,82,82,88,50,14,59,84.000000
373,female,48,group D,some college,standard,completed,82,97,96,29,48,60,91.666667
206,male,77,group E,bachelor's degree,standard,none,82,62,62,39,77,87,68.666667
872,male,89,group B,associate's degree,standard,completed,82,84,78,29,89,47,81.333333
49,male,34,group C,high school,standard,completed,82,84,82,7,34,66,82.666667
803,female,90,group B,some college,standard,none,82,85,87,40,90,30,84.666667
946,male,8,group B,high school,standard,none,82,82,80,53,8,36,81.333333
407,female,4,group B,associate's degree,standard,none,82,80,77,4,4,67,79.666667
328,male,51,group C,associate's degree,standard,completed,82,75,77,82,51,57,78.000000
942,male,73,group C,high school,standard,none,81,66,64,4,73,34,70.333333
580,female,89,group D,some high school,standard,none,81,97,96,2,89,67,91.333333
175,female,1,group C,master's degree,standard,completed,81,91,87,50,1,17,86.333333
449,male,48,group B,associate's degree,standard,none,81,73,72,58,48,39,75.333333
577,female,23,group B,high school,standard,none,81,91,89,96,23,95,87.000000
300,male,26,group A,some college,free/reduced,completed,81,78,81,70,26,31,80.000000
861,female,80,group E,master's degree,free/reduced,none,81,86,87,6,80,61,84.666667
207,male,65,group E,high school,standard,completed,81,80,76,26,65,26,79.000000
876,male,31,group D,some college,standard,none,81,82,84,35,31,14,82.333333
35,male,6,group E,associate's degree,standard,completed,81,81,79,89,6,26,80.333333
285,male,58,group B,associate's degree,standard,completed,81,82,82,62,58,3,81.666667
542,female,17,group C,associate's degree,standard,none,81,77,79,80,17,76,79.000000
164,female,52,group E,master's degree,standard,none,81,92,91,53,52,63,88.000000
669,male,65,group D,associate's degree,standard,completed,81,72,77,77,65,41,76.666667
987,male,47,group E,some high school,standard,completed,81,75,76,62,47,48,77.333333
493,female,91,group C,bachelor's degree,standard,none,81,88,90,21,91,41,86.333333
738,male,55,group D,associate's degree,standard,none,81,71,73,59,55,39,75.000000
725,male,77,group E,some college,standard,completed,81,74,71,50,77,5,75.333333
742,female,34,group C,high school,standard,none,81,84,82,94,34,81,82.333333
981,male,44,group D,some high school,standard,none,81,78,78,45,44,63,79.000000
678,male,91,group D,associate's degree,free/reduced,none,81,75,78,68,91,59,78.000000
713,male,70,group D,master's degree,standard,none,81,81,84,66,70,62,82.000000
477,male,96,group D,associate's degree,standard,none,80,68,72,32,96,22,73.333333
875,male,51,group C,some college,free/reduced,none,80,64,66,39,51,71,70.000000
711,female,95,group E,some high school,standard,completed,80,85,85,29,95,19,83.333333
235,male,7,group D,associate's degree,standard,none,80,75,77,47,7,6,77.333333
186,male,64,group E,high school,standard,none,80,76,65,93,64,99,73.666667
664,male,36,group D,associate's degree,standard,none,80,63,63,36,36,6,68.666667
740,male,19,group D,bachelor's degree,standard,none,80,73,72,88,19,82,75.000000
359,female,7,group D,some college,standard,none,80,90,89,7,7,86,86.333333
376,female,7,group D,some high school,standard,none,80,90,82,89,7,5,84.000000
253,male,5,group D,master's degree,standard,none,80,80,72,7,5,7,77.333333
849,male,55,group D,associate's degree,standard,none,80,75,69,92,55,66,74.666667
210,male,74,group D,some high school,free/reduced,completed,80,79,79,79,74,18,79.333333
303,male,38,group B,associate's degree,standard,none,80,76,64,72,38,19,73.333333
241,female,10,group E,bachelor's degree,standard,none,80,83,83,83,10,96,82.000000
77,male,35,group A,bachelor's degree,standard,completed,80,78,81,66,35,45,79.666667
637,female,70,group D,some high school,standard,completed,80,92,88,50,70,80,86.666667
380,female,15,group B,associate's degree,standard,none,80,86,83,65,15,20,83.000000
533,female,64,group E,associate's degree,standard,completed,79,88,94,86,64,50,87.000000
982,male,59,group B,some high school,standard,completed,79,85,86,58,59,72,83.333333
489,male,67,group A,associate's degree,free/reduced,completed,79,82,82,45,67,42,81.000000
508,male,87,group C,master's degree,standard,none,79,78,77,70,87,96,78.000000
344,male,45,group D,some college,standard,none,79,73,67,61,45,36,73.000000
541,male,72,group D,associate's degree,free/reduced,completed,79,82,80,98,72,11,80.333333
700,female,57,group E,bachelor's degree,standard,completed,79,81,82,56,57,46,80.666667
444,male,19,group A,some high school,free/reduced,none,79,82,73,42,19,57,78.000000
456,female,73,group D,bachelor's degree,standard,none,79,89,89,86,73,75,85.666667
382,male,67,group C,master's degree,free/reduced,none,79,81,71,85,67,41,77.000000
631,male,37,group B,high school,standard,none,79,60,65,85,37,64,68.000000
94,female,25,group B,some college,standard,none,79,86,92,49,25,9,85.666667
172,female,10,group D,some college,standard,none,79,86,81,7,10,60,82.000000
261,male,74,group C,some college,standard,completed,79,79,78,96,74,71,78.666667
60,male,57,group E,bachelor's degree,free/reduced,completed,79,74,72,52,57,50,75.000000
752,male,39,group C,master's degree,free/reduced,completed,79,77,75,42,39,2,77.000000
100,male,18,group B,some college,standard,none,79,67,67,50,18,70,71.000000
120,female,48,group C,bachelor's degree,standard,completed,79,92,89,69,48,10,86.666667
550,male,97,group C,some high school,free/reduced,none,79,76,65,7,97,90,73.333333
695,female,87,group D,some college,free/reduced,none,79,89,86,89,87,93,84.666667
549,male,77,group C,master's degree,standard,none,79,72,69,67,77,47,73.333333
907,female,87,group D,some college,standard,completed,79,84,91,64,87,43,84.666667
762,male,85,group D,some high school,standard,completed,78,81,86,28,85,22,81.666667
95,male,72,group C,associate's degree,free/reduced,completed,78,81,82,51,72,75,80.333333
983,female,80,group A,some college,standard,completed,78,87,91,39,80,97,85.333333
441,female,11,group D,high school,standard,none,78,81,80,69,11,5,79.666667
13,male,93,group A,some college,standard,completed,78,72,70,97,93,44,73.333333
545,male,68,group E,some high school,free/reduced,completed,78,83,80,28,68,57,80.333333
971,male,1,group C,some high school,standard,completed,78,72,69,73,1,42,73.000000
257,male,59,group C,associate's degree,standard,completed,78,77,77,58,59,53,77.333333
199,female,68,group B,bachelor's degree,free/reduced,none,78,79,76,24,68,97,77.666667
941,female,22,group D,master's degree,standard,none,78,91,96,93,22,98,88.333333
821,female,15,group D,bachelor's degree,free/reduced,none,78,90,93,12,15,8,87.000000
294,male,9,group D,high school,free/reduced,completed,78,77,80,61,9,85,78.333333
868,male,3,group E,associate's degree,free/reduced,completed,78,74,72,34,3,86,74.666667
117,female,80,group D,bachelor's degree,standard,none,78,82,79,51,80,77,79.666667
289,male,47,group E,some high school,standard,completed,77,76,77,27,47,44,76.666667
347,female,38,group C,bachelor's degree,standard,completed,77,94,95,73,38,81,88.666667
391,female,91,group D,some college,standard,none,77,68,77,4,91,24,74.000000
463,female,36,group C,some college,free/reduced,none,77,90,91,81,36,71,86.000000
468,female,29,group A,high school,free/reduced,completed,77,88,85,88,29,33,83.333333
999,female,82,group D,some college,free/reduced,none,77,86,86,21,82,31,83.000000
189,female,76,group C,bachelor's degree,standard,none,77,88,87,26,76,4,84.000000
193,male,78,group D,some college,standard,completed,77,62,62,51,78,22,67.000000
656,male,97,group C,associate's degree,free/reduced,none,77,67,64,13,97,7,69.333333
687,male,30,group D,associate's degree,free/reduced,none,77,78,73,44,30,29,76.000000
693,female,87,group D,associate's degree,standard,none,77,77,73,75,87,47,75.666667
316,female,41,group D,master's degree,standard,completed,77,82,91,57,41,87,83.333333
110,female,30,group D,associate's degree,free/reduced,completed,77,89,98,69,30,91,88.000000

In [84]:
# sort desending by multiple columns
df_exams.sort_values(by=['math score', 'reading score'],ascending=False)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,HR_score,logistics,average
149,male,2,group E,associate's degree,free/reduced,completed,100,100,93,63,2,78,97.666667
458,female,30,group E,bachelor's degree,standard,none,100,100,100,61,30,57,100.000000
916,male,12,group E,bachelor's degree,standard,completed,100,100,100,83,12,90,100.000000
962,female,49,group E,associate's degree,standard,none,100,100,100,47,49,99,100.000000
625,male,48,group D,some college,standard,completed,100,97,99,89,48,75,98.666667
623,male,84,group A,some college,standard,completed,100,96,86,16,84,44,94.000000
451,female,6,group E,some college,standard,none,100,92,97,2,6,77,96.333333
114,female,68,group E,bachelor's degree,standard,completed,99,100,100,7,68,18,99.666667
263,female,2,group E,high school,standard,none,99,93,90,91,2,24,94.000000
306,male,27,group E,some college,standard,completed,99,87,81,46,27,12,89.000000
712,female,90,group D,some college,standard,none,98,100,99,90,90,28,99.000000
934,male,2,group C,associate's degree,standard,completed,98,87,90,48,2,51,91.666667
104,male,78,group C,some college,standard,completed,98,86,90,34,78,99,91.333333
179,female,10,group D,some high school,standard,completed,97,100,100,63,10,22,99.000000
855,female,50,group B,bachelor's degree,standard,none,97,97,96,10,50,49,96.666667
864,male,89,group C,associate's degree,standard,none,97,93,91,3,89,17,93.666667
539,male,2,group A,associate's degree,standard,completed,97,92,86,87,2,32,91.666667
34,male,89,group E,some college,standard,none,97,87,82,12,89,22,88.666667
286,male,13,group E,associate's degree,standard,completed,97,82,88,45,13,67,89.000000
165,female,85,group C,bachelor's degree,standard,completed,96,100,100,72,85,82,98.666667
717,female,87,group C,associate's degree,standard,completed,96,96,99,55,87,95,97.000000
562,male,22,group C,bachelor's degree,standard,completed,96,90,92,1,22,4,92.666667
503,female,39,group E,associate's degree,standard,completed,95,89,92,23,39,70,92.000000
618,male,8,group D,master's degree,standard,none,95,81,84,37,8,31,86.666667
685,female,84,group E,master's degree,standard,completed,94,99,100,78,84,55,97.666667
612,male,60,group C,bachelor's degree,standard,completed,94,90,91,30,60,68,91.666667
171,male,54,group E,some high school,standard,none,94,88,78,3,54,30,86.666667
501,female,94,group B,associate's degree,standard,completed,94,87,92,23,94,18,91.000000
815,male,40,group B,some high school,standard,completed,94,86,87,98,40,97,89.000000
779,male,85,group E,associate's degree,standard,completed,94,85,82,76,85,16,87.000000
950,male,69,group E,high school,standard,none,94,73,71,24,69,19,79.333333
886,female,99,group E,associate's degree,standard,completed,93,100,95,67,99,44,96.000000
903,female,9,group D,bachelor's degree,free/reduced,completed,93,100,100,30,9,28,97.666667
689,male,58,group E,some college,free/reduced,none,93,90,83,61,58,63,88.666667
710,male,95,group C,some college,standard,completed,93,84,90,26,95,80,89.000000
546,female,68,group A,some high school,standard,completed,92,100,97,38,68,41,96.333333
566,female,66,group E,bachelor's degree,free/reduced,completed,92,100,100,96,66,51,97.333333
594,female,5,group C,bachelor's degree,standard,completed,92,100,99,2,5,15,97.000000
957,female,27,group D,master's degree,standard,none,92,100,100,88,27,43,97.333333
233,male,63,group E,some high school,standard,none,92,87,78,37,63,51,85.666667
736,male,43,group C,associate's degree,standard,none,92,79,84,16,43,90,85.000000
571,male,9,group A,bachelor's degree,standard,none,91,96,92,52,9,11,93.000000
919,male,80,group B,some college,standard,completed,91,96,91,14,80,78,92.666667
979,female,99,group C,associate's degree,standard,none,91,95,94,40,99,86,93.333333
121,male,98,group B,associate's degree,standard,completed,91,89,92,91,98,75,90.666667
521,female,86,group C,associate's degree,standard,none,91,86,84,3,86,78,87.000000
846,male,19,group C,master's degree,standard,completed,91,85,85,72,19,68,87.000000
784,male,35,group C,bachelor's degree,standard,completed,91,81,79,47,35,85,83.666667
469,male,89,group C,some college,standard,none,91,74,76,90,89,27,80.333333
719,male,89,group E,associate's degree,free/reduced,completed,91,73,80,17,89,98,81.333333
2,female,62,group B,master's degree,standard,none,90,95,93,15,62,98,92.666667
474,female,11,group B,associate's degree,standard,completed,90,90,91,48,11,17,90.333333
873,male,14,group E,associate's degree,free/reduced,none,90,90,82,32,14,84,87.333333
299,male,10,group D,associate's degree,free/reduced,none,90,87,75,38,10,41,84.000000
659,male,82,group D,associate's degree,standard,none,90,87,85,89,82,4,87.333333
845,male,81,group E,master's degree,standard,none,90,85,84,96,81,17,86.333333
333,male,58,group B,associate's degree,standard,none,90,78,81,72,58,49,83.000000
808,male,9,group C,high school,standard,none,90,75,69,56,9,38,78.000000
970,female,60,group D,bachelor's degree,standard,none,89,100,100,4,60,74,96.333333
439,male,49,group D,some high school,standard,completed,89,88,82,74,49,90,86.333333
708,male,12,group D,high school,standard,none,89,87,79,22,12,90,85.000000
130,male,99,group D,master's degree,standard,none,89,84,82,53,99,24,85.000000
793,male,73,group E,some high school,standard,completed,89,84,77,73,73,99,83.333333
246,male,77,group E,associate's degree,standard,none,89,76,74,86,77,6,79.666667
403,female,77,group D,high school,standard,completed,88,99,100,43,77,34,95.666667
995,female,8,group E,master's degree,standard,completed,88,99,95,35,8,63,94.000000
6,female,32,group B,some college,standard,completed,88,95,92,94,32,68,91.666667
229,female,91,group C,some college,standard,completed,88,95,94,1,91,89,92.333333
122,female,20,group C,some college,standard,completed,88,93,93,79,20,95,91.333333
268,female,30,group D,associate's degree,standard,completed,88,92,95,71,30,1,91.666667
16,male,67,group C,high school,standard,none,88,89,86,40,67,33,87.666667
274,male,39,group B,some college,standard,completed,88,85,76,67,39,12,83.000000
146,male,13,group B,some high school,standard,none,88,84,75,26,13,88,82.333333
53,male,48,group D,high school,standard,none,88,78,75,83,48,58,80.333333
617,male,15,group D,bachelor's degree,standard,none,88,78,83,26,15,47,83.000000
905,male,85,group D,some college,standard,none,88,77,77,94,85,6,80.666667
288,male,15,group B,bachelor's degree,free/reduced,none,88,75,76,92,15,44,79.666667
893,male,71,group D,some high school,standard,completed,88,74,75,78,71,32,79.000000
144,male,16,group D,some college,standard,none,88,73,78,91,16,47,79.666667
106,female,71,group D,master's degree,standard,none,87,100,100,12,71,50,95.666667
381,male,17,group C,associate's degree,standard,completed,87,100,95,94,17,37,94.000000
125,female,30,group B,high school,standard,none,87,95,86,10,30,65,89.333333
802,female,31,group E,associate's degree,standard,none,87,94,95,13,31,48,92.000000
214,male,28,group E,high school,standard,completed,87,91,81,94,28,8,86.333333
551,male,40,group B,bachelor's degree,free/reduced,completed,87,90,88,77,40,91,88.333333
732,female,16,group C,some college,standard,completed,87,89,94,77,16,94,90.000000
221,male,76,group B,associate's degree,standard,none,87,85,73,12,76,42,81.666667
852,female,68,group E,some college,standard,none,87,85,93,38,68,82,88.333333
409,male,64,group D,associate's degree,standard,completed,87,84,85,3,64,5,85.333333
702,male,40,group A,bachelor's degree,standard,completed,87,84,87,6,40,76,86.000000
749,male,51,group B,some college,standard,completed,87,84,86,78,51,8,85.666667
813,male,62,group E,some high school,standard,completed,87,84,76,78,62,31,82.333333
132,male,67,group E,some college,free/reduced,completed,87,74,70,16,67,61,77.000000
349,male,94,group E,associate's degree,standard,none,87,74,76,80,94,80,79.000000
859,male,45,group C,associate's degree,free/reduced,none,87,73,72,82,45,32,77.333333
509,female,12,group C,bachelor's degree,standard,none,86,92,87,44,12,42,88.333333
890,female,14,group E,some college,standard,completed,86,85,91,83,14,26,87.333333
426,male,50,group C,bachelor's degree,standard,none,86,83,86,93,50,63,85.000000
447,male,94,group C,high school,standard,completed,86,81,80,46,94,89,82.333333
990,male,86,group E,high school,free/reduced,completed,86,81,75,18,86,51,80.666667
223,male,50,group D,some high school,standard,none,86,80,75,38,50,29,80.333333
638,male,9,group E,some college,standard,none,86,76,74,55,9,35,78.666667
291,male,10,group D,some high school,standard,none,86,73,70,91,10,41,76.333333
377,female,25,group D,master's degree,free/reduced,completed,85,95,100,63,25,65,93.333333
276,female,92,group C,some high school,standard,completed,85,92,93,53,92,37,90.000000
891,female,26,group E,associate's degree,standard,none,85,92,85,77,26,57,87.333333
102,female,22,group D,associate's degree,standard,none,85,91,89,85,22,95,88.333333
820,female,66,group A,some high school,standard,completed,85,90,92,43,66,97,89.000000
397,female,43,group C,associate's degree,standard,none,85,89,95,72,43,62,89.666667
652,female,20,group D,some college,standard,completed,85,86,98,23,20,9,89.666667
361,male,18,group B,some high school,standard,completed,85,84,78,38,18,54,82.333333
606,female,17,group C,associate's degree,standard,none,85,84,82,72,17,42,83.666667
900,male,57,group D,master's degree,standard,none,85,84,89,20,57,1,86.000000
938,male,99,group D,some college,standard,completed,85,81,85,69,99,35,83.666667
245,male,21,group C,associate's degree,standard,none,85,76,71,52,21,53,77.333333
686,male,42,group E,some college,standard,completed,85,75,68,84,42,96,76.000000
538,male,9,group E,bachelor's degree,standard,completed,85,66,71,85,9,18,74.000000
755,female,52,group E,associate's degree,standard,none,84,95,92,76,52,94,90.333333
604,male,92,group D,master's degree,free/reduced,completed,84,89,90,27,92,55,87.666667
465,female,90,group C,some college,standard,none,84,87,91,80,90,15,87.333333
956,male,18,group C,some college,standard,none,84,87,81,96,18,84,84.000000
634,male,19,group D,some high school,standard,none,84,84,80,4,19,51,82.666667
215,male,50,group B,some high school,standard,completed,84,83,75,51,50,45,80.666667
411,male,13,group E,some college,standard,completed,84,83,78,27,13,69,81.666667
239,male,73,group C,associate's degree,standard,none,84,80,80,30,73,71,81.333333
115,male,57,group C,high school,standard,none,84,77,74,57,57,33,78.333333
370,male,84,group E,some college,standard,none,84,77,71,37,84,45,77.333333
415,male,21,group E,high school,standard,none,84,73,69,72,21,41,75.333333
334,female,66,group C,bachelor's degree,standard,none,83,93,95,46,66,81,90.333333
216,female,71,group E,associate's degree,free/reduced,completed,83,86,88,24,71,12,85.666667
470,female,62,group C,associate's degree,standard,completed,83,85,90,46,62,89,86.000000
492,female,59,group C,some college,standard,none,83,83,90,42,59,27,85.333333
234,male,85,group C,bachelor's degree,standard,completed,83,82,84,58,85,57,83.000000
124,male,21,group E,some college,standard,none,83,80,73,32,21,4,78.666667
275,male,75,group C,bachelor's degree,standard,none,83,78,73,99,75,44,78.000000
317,male,91,group C,associate's degree,standard,none,83,72,78,96,91,54,77.666667
373,female,48,group D,some college,standard,completed,82,97,96,29,48,60,91.666667
543,female,47,group D,associate's degree,standard,none,82,95,89,48,47,86,88.666667
420,female,9,group C,associate's degree,free/reduced,completed,82,93,93,28,9,45,89.333333
614,female,10,group A,associate's degree,standard,none,82,93,93,52,10,2,89.333333
325,female,20,group C,some college,standard,none,82,90,94,28,20,39,88.666667
56,female,81,group E,associate's degree,standard,completed,82,85,86,35,81,40,84.333333
803,female,90,group B,some college,standard,none,82,85,87,40,90,30,84.666667
49,male,34,group C,high school,standard,completed,82,84,82,7,34,66,82.666667
872,male,89,group B,associate's degree,standard,completed,82,84,78,29,89,47,81.333333
128,male,15,group D,master's degree,standard,none,82,82,74,73,15,52,79.333333
505,female,50,group B,some high school,standard,none,82,82,80,77,50,68,81.333333
865,male,14,group D,some college,standard,completed,82,82,88,50,14,59,84.000000
946,male,8,group B,high school,standard,none,82,82,80,53,8,36,81.333333
407,female,4,group B,associate's degree,standard,none,82,80,77,4,4,67,79.666667
160,male,41,group B,associate's degree,free/reduced,completed,82,78,74,53,41,54,78.000000
328,male,51,group C,associate's degree,standard,completed,82,75,77,82,51,57,78.000000
853,male,22,group E,some high school,standard,none,82,67,61,64,22,86,70.000000
206,male,77,group E,bachelor's degree,standard,none,82,62,62,39,77,87,68.666667
580,female,89,group D,some high school,standard,none,81,97,96,2,89,67,91.333333
164,female,52,group E,master's degree,standard,none,81,92,91,53,52,63,88.000000
175,female,1,group C,master's degree,standard,completed,81,91,87,50,1,17,86.333333
577,female,23,group B,high school,standard,none,81,91,89,96,23,95,87.000000
493,female,91,group C,bachelor's degree,standard,none,81,88,90,21,91,41,86.333333
861,female,80,group E,master's degree,free/reduced,none,81,86,87,6,80,61,84.666667
742,female,34,group C,high school,standard,none,81,84,82,94,34,81,82.333333
285,male,58,group B,associate's degree,standard,completed,81,82,82,62,58,3,81.666667
876,male,31,group D,some college,standard,none,81,82,84,35,31,14,82.333333
35,male,6,group E,associate's degree,standard,completed,81,81,79,89,6,26,80.333333
713,male,70,group D,master's degree,standard,none,81,81,84,66,70,62,82.000000
207,male,65,group E,high school,standard,completed,81,80,76,26,65,26,79.000000
300,male,26,group A,some college,free/reduced,completed,81,78,81,70,26,31,80.000000
981,male,44,group D,some high school,standard,none,81,78,78,45,44,63,79.000000
542,female,17,group C,associate's degree,standard,none,81,77,79,80,17,76,79.000000
678,male,91,group D,associate's degree,free/reduced,none,81,75,78,68,91,59,78.000000
987,male,47,group E,some high school,standard,completed,81,75,76,62,47,48,77.333333
725,male,77,group E,some college,standard,completed,81,74,71,50,77,5,75.333333
449,male,48,group B,associate's degree,standard,none,81,73,72,58,48,39,75.333333
669,male,65,group D,associate's degree,standard,completed,81,72,77,77,65,41,76.666667
738,male,55,group D,associate's degree,standard,none,81,71,73,59,55,39,75.000000
942,male,73,group C,high school,standard,none,81,66,64,4,73,34,70.333333
637,female,70,group D,some high school,standard,completed,80,92,88,50,70,80,86.666667
359,female,7,group D,some college,standard,none,80,90,89,7,7,86,86.333333
376,female,7,group D,some high school,standard,none,80,90,82,89,7,5,84.000000
380,female,15,group B,associate's degree,standard,none,80,86,83,65,15,20,83.000000
711,female,95,group E,some high school,standard,completed,80,85,85,29,95,19,83.333333
241,female,10,group E,bachelor's degree,standard,none,80,83,83,83,10,96,82.000000
253,male,5,group D,master's degree,standard,none,80,80,72,7,5,7,77.333333
210,male,74,group D,some high school,free/reduced,completed,80,79,79,79,74,18,79.333333
77,male,35,group A,bachelor's degree,standard,completed,80,78,81,66,35,45,79.666667
186,male,64,group E,high school,standard,none,80,76,65,93,64,99,73.666667
303,male,38,group B,associate's degree,standard,none,80,76,64,72,38,19,73.333333
235,male,7,group D,associate's degree,standard,none,80,75,77,47,7,6,77.333333
849,male,55,group D,associate's degree,standard,none,80,75,69,92,55,66,74.666667
740,male,19,group D,bachelor's degree,standard,none,80,73,72,88,19,82,75.000000
477,male,96,group D,associate's degree,standard,none,80,68,72,32,96,22,73.333333
875,male,51,group C,some college,free/reduced,none,80,64,66,39,51,71,70.000000
664,male,36,group D,associate's degree,standard,none,80,63,63,36,36,6,68.666667
120,female,48,group C,bachelor's degree,standard,completed,79,92,89,69,48,10,86.666667
456,female,73,group D,bachelor's degree,standard,none,79,89,89,86,73,75,85.666667
695,female,87,group D,some college,free/reduced,none,79,89,86,89,87,93,84.666667
533,female,64,group E,associate's degree,standard,completed,79,88,94,86,64,50,87.000000
94,female,25,group B,some college,standard,none,79,86,92,49,25,9,85.666667
172,female,10,group D,some college,standard,none,79,86,81,7,10,60,82.000000
982,male,59,group B,some high school,standard,completed,79,85,86,58,59,72,83.333333
907,female,87,group D,some college,standard,completed,79,84,91,64,87,43,84.666667
444,male,19,group A,some high school,free/reduced,none,79,82,73,42,19,57,78.000000
489,male,67,group A,associate's degree,free/reduced,completed,79,82,82,45,67,42,81.000000
541,male,72,group D,associate's degree,free/reduced,completed,79,82,80,98,72,11,80.333333
382,male,67,group C,master's degree,free/reduced,none,79,81,71,85,67,41,77.000000
700,female,57,group E,bachelor's degree,standard,completed,79,81,82,56,57,46,80.666667
261,male,74,group C,some college,standard,completed,79,79,78,96,74,71,78.666667
508,male,87,group C,master's degree,standard,none,79,78,77,70,87,96,78.000000
752,male,39,group C,master's degree,free/reduced,completed,79,77,75,42,39,2,77.000000
550,male,97,group C,some high school,free/reduced,none,79,76,65,7,97,90,73.333333
60,male,57,group E,bachelor's degree,free/reduced,completed,79,74,72,52,57,50,75.000000
344,male,45,group D,some college,standard,none,79,73,67,61,45,36,73.000000
549,male,77,group C,master's degree,standard,none,79,72,69,67,77,47,73.333333
100,male,18,group B,some college,standard,none,79,67,67,50,18,70,71.000000
631,male,37,group B,high school,standard,none,79,60,65,85,37,64,68.000000
941,female,22,group D,master's degree,standard,none,78,91,96,93,22,98,88.333333
821,female,15,group D,bachelor's degree,free/reduced,none,78,90,93,12,15,8,87.000000
983,female,80,group A,some college,standard,completed,78,87,91,39,80,97,85.333333
545,male,68,group E,some high school,free/reduced,completed,78,83,80,28,68,57,80.333333
117,female,80,group D,bachelor's degree,standard,none,78,82,79,51,80,77,79.666667
95,male,72,group C,associate's degree,free/reduced,completed,78,81,82,51,72,75,80.333333
441,female,11,group D,high school,standard,none,78,81,80,69,11,5,79.666667
762,male,85,group D,some high school,standard,completed,78,81,86,28,85,22,81.666667
199,female,68,group B,bachelor's degree,free/reduced,none,78,79,76,24,68,97,77.666667
257,male,59,group C,associate's degree,standard,completed,78,77,77,58,59,53,77.333333
294,male,9,group D,high school,free/reduced,completed,78,77,80,61,9,85,78.333333
868,male,3,group E,associate's degree,free/reduced,completed,78,74,72,34,3,86,74.666667
13,male,93,group A,some college,standard,completed,78,72,70,97,93,44,73.333333
971,male,1,group C,some high school,standard,completed,78,72,69,73,1,42,73.000000
514,female,36,group B,master's degree,free/reduced,completed,77,97,94,55,36,11,89.333333
347,female,38,group C,bachelor's degree,standard,completed,77,94,95,73,38,81,88.666667
819,female,62,group C,some high school,standard,none,77,91,88,61,62,75,85.333333
463,female,36,group C,some college,free/reduced,none,77,90,91,81,36,71,86.000000
753,female,56,group C,some high school,standard,completed,77,90,85,51,56,26,84.000000
781,female,84,group B,master's degree,standard,none,77,90,84,29,84,20,83.666667
110,female,30,group D,associate's degree,free/reduced,completed,77,89,98,69,30,91,88.000000
189,female,76,group C,bachelor's degree,standard,none,77,88,87,26,76,4,84.000000
468,female,29,group A,high school,free/reduced,completed,77,88,85,88,29,33,83.333333
999,female,82,group D,some college,free/reduced,none,77,86,86,21,82,31,83.000000
667,female,11,group B,bachelor's degree,free/reduced,none,77,85,87,39,11,22,83.000000
316,female,41,group D,master's degree,standard,completed,77,82,91,57,41,87,83.333333
833,female,17,group B,high school,standard,completed,77,82,89,42,17,41,82.666667

In [86]:
# sort descending by multiple columns and update dataframe
df_exams.sort_values(by=['math score', 'reading score'],ascending=False,
                    inplace=True)

In [87]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,HR_score,logistics,average
149,male,2,group E,associate's degree,free/reduced,completed,100,100,93,63,2,78,97.666667
458,female,30,group E,bachelor's degree,standard,none,100,100,100,61,30,57,100.000000
916,male,12,group E,bachelor's degree,standard,completed,100,100,100,83,12,90,100.000000
962,female,49,group E,associate's degree,standard,none,100,100,100,47,49,99,100.000000
625,male,48,group D,some college,standard,completed,100,97,99,89,48,75,98.666667
623,male,84,group A,some college,standard,completed,100,96,86,16,84,44,94.000000
451,female,6,group E,some college,standard,none,100,92,97,2,6,77,96.333333
114,female,68,group E,bachelor's degree,standard,completed,99,100,100,7,68,18,99.666667
263,female,2,group E,high school,standard,none,99,93,90,91,2,24,94.000000
306,male,27,group E,some college,standard,completed,99,87,81,46,27,12,89.000000
712,female,90,group D,some college,standard,none,98,100,99,90,90,28,99.000000
934,male,2,group C,associate's degree,standard,completed,98,87,90,48,2,51,91.666667
104,male,78,group C,some college,standard,completed,98,86,90,34,78,99,91.333333
179,female,10,group D,some high school,standard,completed,97,100,100,63,10,22,99.000000
855,female,50,group B,bachelor's degree,standard,none,97,97,96,10,50,49,96.666667
864,male,89,group C,associate's degree,standard,none,97,93,91,3,89,17,93.666667
539,male,2,group A,associate's degree,standard,completed,97,92,86,87,2,32,91.666667
34,male,89,group E,some college,standard,none,97,87,82,12,89,22,88.666667
286,male,13,group E,associate's degree,standard,completed,97,82,88,45,13,67,89.000000
165,female,85,group C,bachelor's degree,standard,completed,96,100,100,72,85,82,98.666667
717,female,87,group C,associate's degree,standard,completed,96,96,99,55,87,95,97.000000
562,male,22,group C,bachelor's degree,standard,completed,96,90,92,1,22,4,92.666667
503,female,39,group E,associate's degree,standard,completed,95,89,92,23,39,70,92.000000
618,male,8,group D,master's degree,standard,none,95,81,84,37,8,31,86.666667
685,female,84,group E,master's degree,standard,completed,94,99,100,78,84,55,97.666667
612,male,60,group C,bachelor's degree,standard,completed,94,90,91,30,60,68,91.666667
171,male,54,group E,some high school,standard,none,94,88,78,3,54,30,86.666667
501,female,94,group B,associate's degree,standard,completed,94,87,92,23,94,18,91.000000
815,male,40,group B,some high school,standard,completed,94,86,87,98,40,97,89.000000
779,male,85,group E,associate's degree,standard,completed,94,85,82,76,85,16,87.000000
950,male,69,group E,high school,standard,none,94,73,71,24,69,19,79.333333
886,female,99,group E,associate's degree,standard,completed,93,100,95,67,99,44,96.000000
903,female,9,group D,bachelor's degree,free/reduced,completed,93,100,100,30,9,28,97.666667
689,male,58,group E,some college,free/reduced,none,93,90,83,61,58,63,88.666667
710,male,95,group C,some college,standard,completed,93,84,90,26,95,80,89.000000
546,female,68,group A,some high school,standard,completed,92,100,97,38,68,41,96.333333
566,female,66,group E,bachelor's degree,free/reduced,completed,92,100,100,96,66,51,97.333333
594,female,5,group C,bachelor's degree,standard,completed,92,100,99,2,5,15,97.000000
957,female,27,group D,master's degree,standard,none,92,100,100,88,27,43,97.333333
233,male,63,group E,some high school,standard,none,92,87,78,37,63,51,85.666667
736,male,43,group C,associate's degree,standard,none,92,79,84,16,43,90,85.000000
571,male,9,group A,bachelor's degree,standard,none,91,96,92,52,9,11,93.000000
919,male,80,group B,some college,standard,completed,91,96,91,14,80,78,92.666667
979,female,99,group C,associate's degree,standard,none,91,95,94,40,99,86,93.333333
121,male,98,group B,associate's degree,standard,completed,91,89,92,91,98,75,90.666667
521,female,86,group C,associate's degree,standard,none,91,86,84,3,86,78,87.000000
846,male,19,group C,master's degree,standard,completed,91,85,85,72,19,68,87.000000
784,male,35,group C,bachelor's degree,standard,completed,91,81,79,47,35,85,83.666667
469,male,89,group C,some college,standard,none,91,74,76,90,89,27,80.333333
719,male,89,group E,associate's degree,free/reduced,completed,91,73,80,17,89,98,81.333333
2,female,62,group B,master's degree,standard,none,90,95,93,15,62,98,92.666667
474,female,11,group B,associate's degree,standard,completed,90,90,91,48,11,17,90.333333
873,male,14,group E,associate's degree,free/reduced,none,90,90,82,32,14,84,87.333333
299,male,10,group D,associate's degree,free/reduced,none,90,87,75,38,10,41,84.000000
659,male,82,group D,associate's degree,standard,none,90,87,85,89,82,4,87.333333
845,male,81,group E,master's degree,standard,none,90,85,84,96,81,17,86.333333
333,male,58,group B,associate's degree,standard,none,90,78,81,72,58,49,83.000000
808,male,9,group C,high school,standard,none,90,75,69,56,9,38,78.000000
970,female,60,group D,bachelor's degree,standard,none,89,100,100,4,60,74,96.333333
439,male,49,group D,some high school,standard,completed,89,88,82,74,49,90,86.333333
708,male,12,group D,high school,standard,none,89,87,79,22,12,90,85.000000
130,male,99,group D,master's degree,standard,none,89,84,82,53,99,24,85.000000
793,male,73,group E,some high school,standard,completed,89,84,77,73,73,99,83.333333
246,male,77,group E,associate's degree,standard,none,89,76,74,86,77,6,79.666667
403,female,77,group D,high school,standard,completed,88,99,100,43,77,34,95.666667
995,female,8,group E,master's degree,standard,completed,88,99,95,35,8,63,94.000000
6,female,32,group B,some college,standard,completed,88,95,92,94,32,68,91.666667
229,female,91,group C,some college,standard,completed,88,95,94,1,91,89,92.333333
122,female,20,group C,some college,standard,completed,88,93,93,79,20,95,91.333333
268,female,30,group D,associate's degree,standard,completed,88,92,95,71,30,1,91.666667
16,male,67,group C,high school,standard,none,88,89,86,40,67,33,87.666667
274,male,39,group B,some college,standard,completed,88,85,76,67,39,12,83.000000
146,male,13,group B,some high school,standard,none,88,84,75,26,13,88,82.333333
53,male,48,group D,high school,standard,none,88,78,75,83,48,58,80.333333
617,male,15,group D,bachelor's degree,standard,none,88,78,83,26,15,47,83.000000
905,male,85,group D,some college,standard,none,88,77,77,94,85,6,80.666667
288,male,15,group B,bachelor's degree,free/reduced,none,88,75,76,92,15,44,79.666667
893,male,71,group D,some high school,standard,completed,88,74,75,78,71,32,79.000000
144,male,16,group D,some college,standard,none,88,73,78,91,16,47,79.666667
106,female,71,group D,master's degree,standard,none,87,100,100,12,71,50,95.666667
381,male,17,group C,associate's degree,standard,completed,87,100,95,94,17,37,94.000000
125,female,30,group B,high school,standard,none,87,95,86,10,30,65,89.333333
802,female,31,group E,associate's degree,standard,none,87,94,95,13,31,48,92.000000
214,male,28,group E,high school,standard,completed,87,91,81,94,28,8,86.333333
551,male,40,group B,bachelor's degree,free/reduced,completed,87,90,88,77,40,91,88.333333
732,female,16,group C,some college,standard,completed,87,89,94,77,16,94,90.000000
221,male,76,group B,associate's degree,standard,none,87,85,73,12,76,42,81.666667
852,female,68,group E,some college,standard,none,87,85,93,38,68,82,88.333333
409,male,64,group D,associate's degree,standard,completed,87,84,85,3,64,5,85.333333
702,male,40,group A,bachelor's degree,standard,completed,87,84,87,6,40,76,86.000000
749,male,51,group B,some college,standard,completed,87,84,86,78,51,8,85.666667
813,male,62,group E,some high school,standard,completed,87,84,76,78,62,31,82.333333
132,male,67,group E,some college,free/reduced,completed,87,74,70,16,67,61,77.000000
349,male,94,group E,associate's degree,standard,none,87,74,76,80,94,80,79.000000
859,male,45,group C,associate's degree,free/reduced,none,87,73,72,82,45,32,77.333333
509,female,12,group C,bachelor's degree,standard,none,86,92,87,44,12,42,88.333333
890,female,14,group E,some college,standard,completed,86,85,91,83,14,26,87.333333
426,male,50,group C,bachelor's degree,standard,none,86,83,86,93,50,63,85.000000
447,male,94,group C,high school,standard,completed,86,81,80,46,94,89,82.333333
990,male,86,group E,high school,free/reduced,completed,86,81,75,18,86,51,80.666667
223,male,50,group D,some high school,standard,none,86,80,75,38,50,29,80.333333
638,male,9,group E,some college,standard,none,86,76,74,55,9,35,78.666667
291,male,10,group D,some high school,standard,none,86,73,70,91,10,41,76.333333
377,female,25,group D,master's degree,free/reduced,completed,85,95,100,63,25,65,93.333333
276,female,92,group C,some high school,standard,completed,85,92,93,53,92,37,90.000000
891,female,26,group E,associate's degree,standard,none,85,92,85,77,26,57,87.333333
102,female,22,group D,associate's degree,standard,none,85,91,89,85,22,95,88.333333
820,female,66,group A,some high school,standard,completed,85,90,92,43,66,97,89.000000
397,female,43,group C,associate's degree,standard,none,85,89,95,72,43,62,89.666667
652,female,20,group D,some college,standard,completed,85,86,98,23,20,9,89.666667
361,male,18,group B,some high school,standard,completed,85,84,78,38,18,54,82.333333
606,female,17,group C,associate's degree,standard,none,85,84,82,72,17,42,83.666667
900,male,57,group D,master's degree,standard,none,85,84,89,20,57,1,86.000000
938,male,99,group D,some college,standard,completed,85,81,85,69,99,35,83.666667
245,male,21,group C,associate's degree,standard,none,85,76,71,52,21,53,77.333333
686,male,42,group E,some college,standard,completed,85,75,68,84,42,96,76.000000
538,male,9,group E,bachelor's degree,standard,completed,85,66,71,85,9,18,74.000000
755,female,52,group E,associate's degree,standard,none,84,95,92,76,52,94,90.333333
604,male,92,group D,master's degree,free/reduced,completed,84,89,90,27,92,55,87.666667
465,female,90,group C,some college,standard,none,84,87,91,80,90,15,87.333333
956,male,18,group C,some college,standard,none,84,87,81,96,18,84,84.000000
634,male,19,group D,some high school,standard,none,84,84,80,4,19,51,82.666667
215,male,50,group B,some high school,standard,completed,84,83,75,51,50,45,80.666667
411,male,13,group E,some college,standard,completed,84,83,78,27,13,69,81.666667
239,male,73,group C,associate's degree,standard,none,84,80,80,30,73,71,81.333333
115,male,57,group C,high school,standard,none,84,77,74,57,57,33,78.333333
370,male,84,group E,some college,standard,none,84,77,71,37,84,45,77.333333
415,male,21,group E,high school,standard,none,84,73,69,72,21,41,75.333333
334,female,66,group C,bachelor's degree,standard,none,83,93,95,46,66,81,90.333333
216,female,71,group E,associate's degree,free/reduced,completed,83,86,88,24,71,12,85.666667
470,female,62,group C,associate's degree,standard,completed,83,85,90,46,62,89,86.000000
492,female,59,group C,some college,standard,none,83,83,90,42,59,27,85.333333
234,male,85,group C,bachelor's degree,standard,completed,83,82,84,58,85,57,83.000000
124,male,21,group E,some college,standard,none,83,80,73,32,21,4,78.666667
275,male,75,group C,bachelor's degree,standard,none,83,78,73,99,75,44,78.000000
317,male,91,group C,associate's degree,standard,none,83,72,78,96,91,54,77.666667
373,female,48,group D,some college,standard,completed,82,97,96,29,48,60,91.666667
543,female,47,group D,associate's degree,standard,none,82,95,89,48,47,86,88.666667
420,female,9,group C,associate's degree,free/reduced,completed,82,93,93,28,9,45,89.333333
614,female,10,group A,associate's degree,standard,none,82,93,93,52,10,2,89.333333
325,female,20,group C,some college,standard,none,82,90,94,28,20,39,88.666667
56,female,81,group E,associate's degree,standard,completed,82,85,86,35,81,40,84.333333
803,female,90,group B,some college,standard,none,82,85,87,40,90,30,84.666667
49,male,34,group C,high school,standard,completed,82,84,82,7,34,66,82.666667
872,male,89,group B,associate's degree,standard,completed,82,84,78,29,89,47,81.333333
128,male,15,group D,master's degree,standard,none,82,82,74,73,15,52,79.333333
505,female,50,group B,some high school,standard,none,82,82,80,77,50,68,81.333333
865,male,14,group D,some college,standard,completed,82,82,88,50,14,59,84.000000
946,male,8,group B,high school,standard,none,82,82,80,53,8,36,81.333333
407,female,4,group B,associate's degree,standard,none,82,80,77,4,4,67,79.666667
160,male,41,group B,associate's degree,free/reduced,completed,82,78,74,53,41,54,78.000000
328,male,51,group C,associate's degree,standard,completed,82,75,77,82,51,57,78.000000
853,male,22,group E,some high school,standard,none,82,67,61,64,22,86,70.000000
206,male,77,group E,bachelor's degree,standard,none,82,62,62,39,77,87,68.666667
580,female,89,group D,some high school,standard,none,81,97,96,2,89,67,91.333333
164,female,52,group E,master's degree,standard,none,81,92,91,53,52,63,88.000000
175,female,1,group C,master's degree,standard,completed,81,91,87,50,1,17,86.333333
577,female,23,group B,high school,standard,none,81,91,89,96,23,95,87.000000
493,female,91,group C,bachelor's degree,standard,none,81,88,90,21,91,41,86.333333
861,female,80,group E,master's degree,free/reduced,none,81,86,87,6,80,61,84.666667
742,female,34,group C,high school,standard,none,81,84,82,94,34,81,82.333333
285,male,58,group B,associate's degree,standard,completed,81,82,82,62,58,3,81.666667
876,male,31,group D,some college,standard,none,81,82,84,35,31,14,82.333333
35,male,6,group E,associate's degree,standard,completed,81,81,79,89,6,26,80.333333
713,male,70,group D,master's degree,standard,none,81,81,84,66,70,62,82.000000
207,male,65,group E,high school,standard,completed,81,80,76,26,65,26,79.000000
300,male,26,group A,some college,free/reduced,completed,81,78,81,70,26,31,80.000000
981,male,44,group D,some high school,standard,none,81,78,78,45,44,63,79.000000
542,female,17,group C,associate's degree,standard,none,81,77,79,80,17,76,79.000000
678,male,91,group D,associate's degree,free/reduced,none,81,75,78,68,91,59,78.000000
987,male,47,group E,some high school,standard,completed,81,75,76,62,47,48,77.333333
725,male,77,group E,some college,standard,completed,81,74,71,50,77,5,75.333333
449,male,48,group B,associate's degree,standard,none,81,73,72,58,48,39,75.333333
669,male,65,group D,associate's degree,standard,completed,81,72,77,77,65,41,76.666667
738,male,55,group D,associate's degree,standard,none,81,71,73,59,55,39,75.000000
942,male,73,group C,high school,standard,none,81,66,64,4,73,34,70.333333
637,female,70,group D,some high school,standard,completed,80,92,88,50,70,80,86.666667
359,female,7,group D,some college,standard,none,80,90,89,7,7,86,86.333333
376,female,7,group D,some high school,standard,none,80,90,82,89,7,5,84.000000
380,female,15,group B,associate's degree,standard,none,80,86,83,65,15,20,83.000000
711,female,95,group E,some high school,standard,completed,80,85,85,29,95,19,83.333333
241,female,10,group E,bachelor's degree,standard,none,80,83,83,83,10,96,82.000000
253,male,5,group D,master's degree,standard,none,80,80,72,7,5,7,77.333333
210,male,74,group D,some high school,free/reduced,completed,80,79,79,79,74,18,79.333333
77,male,35,group A,bachelor's degree,standard,completed,80,78,81,66,35,45,79.666667
186,male,64,group E,high school,standard,none,80,76,65,93,64,99,73.666667
303,male,38,group B,associate's degree,standard,none,80,76,64,72,38,19,73.333333
235,male,7,group D,associate's degree,standard,none,80,75,77,47,7,6,77.333333
849,male,55,group D,associate's degree,standard,none,80,75,69,92,55,66,74.666667
740,male,19,group D,bachelor's degree,standard,none,80,73,72,88,19,82,75.000000
477,male,96,group D,associate's degree,standard,none,80,68,72,32,96,22,73.333333
875,male,51,group C,some college,free/reduced,none,80,64,66,39,51,71,70.000000
664,male,36,group D,associate's degree,standard,none,80,63,63,36,36,6,68.666667
120,female,48,group C,bachelor's degree,standard,completed,79,92,89,69,48,10,86.666667
456,female,73,group D,bachelor's degree,standard,none,79,89,89,86,73,75,85.666667
695,female,87,group D,some college,free/reduced,none,79,89,86,89,87,93,84.666667
533,female,64,group E,associate's degree,standard,completed,79,88,94,86,64,50,87.000000
94,female,25,group B,some college,standard,none,79,86,92,49,25,9,85.666667
172,female,10,group D,some college,standard,none,79,86,81,7,10,60,82.000000
982,male,59,group B,some high school,standard,completed,79,85,86,58,59,72,83.333333
907,female,87,group D,some college,standard,completed,79,84,91,64,87,43,84.666667
444,male,19,group A,some high school,free/reduced,none,79,82,73,42,19,57,78.000000
489,male,67,group A,associate's degree,free/reduced,completed,79,82,82,45,67,42,81.000000
541,male,72,group D,associate's degree,free/reduced,completed,79,82,80,98,72,11,80.333333
382,male,67,group C,master's degree,free/reduced,none,79,81,71,85,67,41,77.000000
700,female,57,group E,bachelor's degree,standard,completed,79,81,82,56,57,46,80.666667
261,male,74,group C,some college,standard,completed,79,79,78,96,74,71,78.666667
508,male,87,group C,master's degree,standard,none,79,78,77,70,87,96,78.000000
752,male,39,group C,master's degree,free/reduced,completed,79,77,75,42,39,2,77.000000
550,male,97,group C,some high school,free/reduced,none,79,76,65,7,97,90,73.333333
60,male,57,group E,bachelor's degree,free/reduced,completed,79,74,72,52,57,50,75.000000
344,male,45,group D,some college,standard,none,79,73,67,61,45,36,73.000000
549,male,77,group C,master's degree,standard,none,79,72,69,67,77,47,73.333333
100,male,18,group B,some college,standard,none,79,67,67,50,18,70,71.000000
631,male,37,group B,high school,standard,none,79,60,65,85,37,64,68.000000
941,female,22,group D,master's degree,standard,none,78,91,96,93,22,98,88.333333
821,female,15,group D,bachelor's degree,free/reduced,none,78,90,93,12,15,8,87.000000
983,female,80,group A,some college,standard,completed,78,87,91,39,80,97,85.333333
545,male,68,group E,some high school,free/reduced,completed,78,83,80,28,68,57,80.333333
117,female,80,group D,bachelor's degree,standard,none,78,82,79,51,80,77,79.666667
95,male,72,group C,associate's degree,free/reduced,completed,78,81,82,51,72,75,80.333333
441,female,11,group D,high school,standard,none,78,81,80,69,11,5,79.666667
762,male,85,group D,some high school,standard,completed,78,81,86,28,85,22,81.666667
199,female,68,group B,bachelor's degree,free/reduced,none,78,79,76,24,68,97,77.666667
257,male,59,group C,associate's degree,standard,completed,78,77,77,58,59,53,77.333333
294,male,9,group D,high school,free/reduced,completed,78,77,80,61,9,85,78.333333
868,male,3,group E,associate's degree,free/reduced,completed,78,74,72,34,3,86,74.666667
13,male,93,group A,some college,standard,completed,78,72,70,97,93,44,73.333333
971,male,1,group C,some high school,standard,completed,78,72,69,73,1,42,73.000000
514,female,36,group B,master's degree,free/reduced,completed,77,97,94,55,36,11,89.333333
347,female,38,group C,bachelor's degree,standard,completed,77,94,95,73,38,81,88.666667
819,female,62,group C,some high school,standard,none,77,91,88,61,62,75,85.333333
463,female,36,group C,some college,free/reduced,none,77,90,91,81,36,71,86.000000
753,female,56,group C,some high school,standard,completed,77,90,85,51,56,26,84.000000
781,female,84,group B,master's degree,standard,none,77,90,84,29,84,20,83.666667
110,female,30,group D,associate's degree,free/reduced,completed,77,89,98,69,30,91,88.000000
189,female,76,group C,bachelor's degree,standard,none,77,88,87,26,76,4,84.000000
468,female,29,group A,high school,free/reduced,completed,77,88,85,88,29,33,83.333333
999,female,82,group D,some college,free/reduced,none,77,86,86,21,82,31,83.000000
667,female,11,group B,bachelor's degree,free/reduced,none,77,85,87,39,11,22,83.000000
316,female,41,group D,master's degree,standard,completed,77,82,91,57,41,87,83.333333
833,female,17,group B,high school,standard,completed,77,82,89,42,17,41,82.666667

In [89]:
# sort descending with a key function
df_exams.sort_values('race/ethnicity', ascending=True,
                    key=lambda col:col.str.lower())

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,HR_score,logistics,average
741,female,16,group A,associate's degree,free/reduced,none,37,57,56,36,16,83,50.000000
151,male,75,group A,bachelor's degree,standard,none,77,67,68,74,75,84,70.666667
811,male,31,group A,high school,free/reduced,none,45,47,49,54,31,78,47.000000
112,male,78,group A,associate's degree,standard,none,54,53,47,30,78,62,51.333333
25,male,31,group A,master's degree,free/reduced,none,73,74,72,74,31,10,73.000000
851,female,62,group A,high school,standard,none,61,68,63,12,62,73,64.000000
653,female,38,group A,associate's degree,standard,completed,65,70,74,94,38,86,69.666667
3,male,80,group A,associate's degree,free/reduced,none,47,57,44,96,80,77,49.333333
575,male,30,group A,associate's degree,free/reduced,completed,40,55,53,74,30,26,49.333333
468,female,29,group A,high school,free/reduced,completed,77,88,85,88,29,33,83.333333
778,female,93,group A,some college,standard,completed,72,79,82,78,93,52,77.666667
428,male,83,group A,some high school,free/reduced,none,65,59,53,80,83,25,59.000000
170,male,61,group A,high school,standard,completed,72,73,74,32,61,93,73.000000
943,male,1,group A,some high school,free/reduced,completed,61,62,61,50,1,36,61.333333
467,male,78,group A,high school,free/reduced,completed,72,67,65,34,78,98,68.000000
688,male,52,group A,high school,free/reduced,none,53,58,44,34,52,25,51.666667
837,female,6,group A,high school,standard,completed,75,82,79,11,6,12,78.666667
597,male,31,group A,some high school,standard,none,53,54,48,49,31,40,51.666667
816,female,17,group A,bachelor's degree,standard,none,45,59,64,64,17,36,56.000000
972,female,54,group A,high school,free/reduced,completed,53,50,60,35,54,18,54.333333
13,male,93,group A,some college,standard,completed,78,72,70,97,93,44,73.333333
401,male,58,group A,some college,standard,none,53,43,43,37,58,55,46.333333
378,female,42,group A,some high school,standard,none,71,83,77,66,42,30,77.000000
769,male,62,group A,some college,free/reduced,none,58,60,57,61,62,47,58.333333
490,female,7,group A,associate's degree,free/reduced,none,65,85,76,18,7,47,75.333333
702,male,40,group A,bachelor's degree,standard,completed,87,84,87,6,40,76,86.000000
368,female,90,group A,some high school,free/reduced,none,44,64,58,85,90,92,55.333333
985,male,96,group A,high school,standard,none,57,51,54,28,96,91,54.000000
805,male,89,group A,some college,free/reduced,none,75,81,74,21,89,76,76.666667
143,male,3,group A,high school,standard,none,57,43,47,47,3,2,49.000000
356,male,74,group A,associate's degree,standard,none,63,61,61,37,74,85,61.666667
994,male,77,group A,high school,standard,none,63,63,62,90,77,59,62.666667
705,male,77,group A,bachelor's degree,free/reduced,none,62,72,65,40,77,77,66.333333
960,female,40,group A,some college,standard,none,56,58,64,97,40,13,59.333333
61,male,75,group A,some high school,free/reduced,none,39,39,34,10,75,64,37.333333
586,female,4,group A,high school,standard,none,55,73,73,98,4,90,67.000000
988,female,95,group A,some high school,free/reduced,none,44,45,45,62,95,80,44.666667
433,female,48,group A,some high school,free/reduced,none,47,59,50,68,48,43,52.000000
464,male,83,group A,bachelor's degree,standard,completed,75,58,62,46,83,59,65.000000
395,male,99,group A,high school,free/reduced,none,48,45,41,30,99,40,44.666667
820,female,66,group A,some high school,standard,completed,85,90,92,43,66,97,89.000000
150,male,74,group A,some high school,standard,completed,62,67,69,77,74,57,66.000000
731,male,88,group A,some high school,free/reduced,none,55,46,43,96,88,35,48.000000
511,male,46,group A,some high school,standard,none,64,50,43,76,46,92,52.333333
384,female,55,group A,some high school,free/reduced,none,38,43,43,84,55,62,41.333333
832,male,44,group A,bachelor's degree,standard,none,64,60,58,40,44,97,60.666667
614,female,10,group A,associate's degree,standard,none,82,93,93,52,10,2,89.333333
974,female,30,group A,some college,standard,none,54,63,67,17,30,14,61.333333
62,male,8,group A,associate's degree,free/reduced,none,62,61,55,21,8,61,59.333333
46,female,53,group A,associate's degree,standard,completed,55,65,62,87,53,30,60.666667
902,female,81,group A,high school,free/reduced,completed,34,48,41,32,81,37,41.000000
830,female,84,group A,some college,free/reduced,none,61,60,57,67,84,53,59.333333
576,male,12,group A,some college,standard,completed,61,51,52,73,12,4,54.666667
72,female,37,group A,associate's degree,free/reduced,none,41,51,48,14,37,20,46.666667
129,female,98,group A,bachelor's degree,standard,none,51,49,51,78,98,87,50.333333
810,male,66,group A,some high school,standard,none,51,31,36,33,66,39,39.333333
892,female,54,group A,master's degree,free/reduced,none,50,67,73,59,54,46,63.333333
327,male,18,group A,some college,free/reduced,none,28,23,19,67,18,93,23.333333
77,male,35,group A,bachelor's degree,standard,completed,80,78,81,66,35,45,79.666667
539,male,2,group A,associate's degree,standard,completed,97,92,86,87,2,32,91.666667
423,female,80,group A,some high school,standard,completed,59,85,80,6,80,98,74.666667
442,female,71,group A,some high school,free/reduced,none,59,73,69,57,71,65,67.000000
489,male,67,group A,associate's degree,free/reduced,completed,79,82,82,45,67,42,81.000000
14,female,4,group A,master's degree,standard,none,50,53,58,90,4,7,53.666667
305,male,19,group A,some college,standard,none,69,67,69,68,19,7,68.333333
444,male,19,group A,some high school,free/reduced,none,79,82,73,42,19,57,78.000000
506,male,52,group A,high school,standard,none,68,70,66,57,52,83,68.000000
82,male,10,group A,some college,free/reduced,completed,50,47,54,64,10,61,50.333333
365,male,43,group A,bachelor's degree,free/reduced,completed,49,58,60,39,43,29,55.666667
228,male,1,group A,some high school,free/reduced,none,68,72,64,49,1,81,68.000000
623,male,84,group A,some college,standard,completed,100,96,86,16,84,44,94.000000
402,female,66,group A,some college,free/reduced,none,49,65,55,70,66,1,56.333333
697,female,13,group A,bachelor's degree,standard,none,59,72,70,81,13,32,67.000000
651,female,12,group A,high school,standard,completed,68,80,76,95,12,63,74.666667
483,male,84,group A,high school,standard,none,59,52,46,84,84,75,52.333333
589,female,90,group A,some high school,standard,none,48,66,65,63,90,42,59.666667
911,female,33,group A,some college,standard,none,69,84,82,60,33,49,78.333333
296,male,64,group A,some high school,standard,completed,46,41,43,68,64,25,43.333333
250,male,97,group A,some high school,standard,completed,47,49,49,26,97,30,48.333333
591,male,46,group A,some high school,standard,none,71,62,50,95,46,34,61.000000
571,male,9,group A,bachelor's degree,standard,none,91,96,92,52,9,11,93.000000
546,female,68,group A,some high school,standard,completed,92,100,97,38,68,41,96.333333
88,female,39,group A,some college,standard,none,58,70,67,80,39,47,65.000000
936,male,80,group A,associate's degree,standard,none,67,57,53,57,80,16,59.000000
966,male,19,group A,some high school,standard,completed,66,68,64,72,19,22,66.000000
983,female,80,group A,some college,standard,completed,78,87,91,39,80,97,85.333333
379,male,97,group A,bachelor's degree,standard,none,66,64,62,18,97,79,64.000000
635,male,67,group A,high school,standard,none,71,74,64,56,67,82,69.666667
300,male,26,group A,some college,free/reduced,completed,81,78,81,70,26,31,80.000000
514,female,36,group B,master's degree,free/reduced,completed,77,97,94,55,36,11,89.333333
684,male,9,group B,some college,standard,completed,62,66,68,97,9,85,65.333333
655,female,33,group B,some college,standard,none,62,67,67,26,33,42,65.333333
564,male,33,group B,bachelor's degree,free/reduced,none,48,51,46,38,33,15,48.333333
781,female,84,group B,master's degree,standard,none,77,90,84,29,84,20,83.666667
188,male,41,group B,some high school,free/reduced,none,48,52,45,1,41,20,48.333333
982,male,59,group B,some high school,standard,completed,79,85,86,58,59,72,83.333333
75,male,42,group B,associate's degree,free/reduced,none,44,41,38,82,42,81,41.000000
26,male,99,group B,some college,standard,none,69,54,55,81,99,42,59.333333
219,male,78,group B,some high school,standard,completed,61,56,56,14,78,61,57.666667
68,male,85,group B,associate's degree,free/reduced,none,61,58,56,23,85,30,58.333333
867,male,27,group B,associate's degree,standard,none,61,42,41,50,27,37,48.000000
767,male,60,group B,high school,standard,completed,76,62,60,63,60,90,66.000000
833,female,17,group B,high school,standard,completed,77,82,89,42,17,41,82.666667
192,female,70,group B,some high school,standard,none,62,64,66,2,70,61,64.000000
621,male,37,group B,bachelor's degree,free/reduced,none,62,63,56,48,37,30,60.333333
714,female,34,group B,some high school,standard,completed,60,70,74,31,34,37,68.000000
335,female,87,group B,some college,free/reduced,none,61,68,66,11,87,84,65.000000
631,male,37,group B,high school,standard,none,79,60,65,85,37,64,68.000000
355,female,20,group B,bachelor's degree,standard,none,61,72,70,23,20,21,67.666667
100,male,18,group B,some college,standard,none,79,67,67,50,18,70,71.000000
158,female,39,group B,associate's degree,standard,completed,61,86,87,97,39,46,78.000000
681,male,82,group B,high school,standard,none,60,68,60,10,82,2,62.666667
976,male,82,group B,some college,free/reduced,completed,60,62,60,39,82,38,60.666667
667,female,11,group B,bachelor's degree,free/reduced,none,77,85,87,39,11,22,83.000000
818,female,95,group B,high school,free/reduced,none,60,72,68,55,95,23,66.666667
682,male,4,group B,high school,standard,none,62,55,54,45,4,69,57.000000
199,female,68,group B,bachelor's degree,free/reduced,none,78,79,76,24,68,97,77.666667
346,male,71,group B,some college,standard,none,62,61,57,77,71,46,60.000000
157,male,89,group B,some college,free/reduced,none,60,60,60,88,89,36,60.000000
782,female,94,group B,high school,free/reduced,completed,76,85,82,21,94,87,81.000000
252,female,24,group B,some high school,standard,completed,60,70,70,35,24,15,66.666667
103,male,66,group B,high school,standard,completed,60,44,47,69,66,7,50.333333
763,female,75,group B,high school,standard,none,62,62,63,3,75,54,62.333333
578,female,91,group B,some college,free/reduced,completed,48,56,58,1,91,94,54.000000
794,female,10,group B,high school,standard,none,42,52,51,94,10,57,48.333333
715,female,86,group B,associate's degree,free/reduced,completed,76,94,87,34,86,14,85.666667
116,female,18,group B,bachelor's degree,free/reduced,none,75,85,82,63,18,4,80.666667
775,female,87,group B,some high school,free/reduced,none,49,58,55,26,87,82,54.000000
568,male,33,group B,high school,free/reduced,none,63,48,47,92,33,14,52.666667
991,female,63,group B,some high school,standard,completed,65,82,78,16,63,80,75.000000
5,female,86,group B,associate's degree,standard,none,71,83,78,8,86,45,77.333333
311,male,60,group B,bachelor's degree,standard,none,66,60,57,11,60,39,61.000000
570,male,75,group B,some college,standard,completed,71,75,70,84,75,61,72.000000
774,male,11,group B,some college,standard,none,66,65,60,89,11,94,63.666667
80,female,18,group B,associate's degree,standard,none,47,49,50,17,18,64,48.666667
498,female,39,group B,some high school,standard,none,66,69,68,97,39,98,67.666667
776,female,82,group B,high school,standard,none,66,72,70,10,82,42,69.333333
632,female,7,group B,bachelor's degree,standard,completed,66,74,81,74,7,19,73.666667
980,female,23,group B,high school,free/reduced,none,8,24,23,98,23,69,18.333333
218,male,97,group B,high school,free/reduced,none,66,77,70,42,97,49,71.000000
258,female,35,group B,some college,standard,none,70,75,78,44,35,33,74.333333
295,male,57,group B,associate's degree,free/reduced,none,67,62,60,56,57,54,63.000000
65,male,88,group B,some high school,standard,none,67,64,61,84,88,28,64.000000
644,male,93,group B,high school,standard,none,70,65,60,51,93,94,65.000000
109,female,43,group B,some high school,standard,none,70,64,72,82,43,87,68.666667
448,male,81,group B,high school,standard,none,47,46,42,77,81,90,45.000000
519,female,83,group B,high school,free/reduced,completed,67,78,79,5,83,81,74.666667
636,female,46,group B,high school,free/reduced,completed,67,80,81,54,46,35,76.000000
232,female,93,group B,bachelor's degree,standard,none,67,86,83,71,93,69,78.666667
287,female,57,group B,some high school,standard,none,67,89,82,62,57,47,79.333333
724,male,61,group B,some college,standard,none,47,43,41,74,61,13,43.666667
829,male,57,group B,some high school,standard,none,68,54,53,32,57,4,58.333333
759,male,8,group B,some college,standard,completed,69,77,77,52,8,90,74.333333
342,female,81,group B,high school,standard,completed,69,76,74,42,81,34,73.000000
626,male,11,group B,associate's degree,free/reduced,completed,69,70,63,65,11,63,67.333333
914,female,16,group B,associate's degree,free/reduced,none,46,61,55,56,16,65,54.000000
176,female,28,group B,high school,free/reduced,completed,46,54,58,97,28,98,52.666667
730,female,39,group B,associate's degree,free/reduced,completed,68,77,80,68,39,89,75.000000
823,female,6,group B,high school,free/reduced,none,71,87,82,40,6,12,80.000000
969,female,61,group B,bachelor's degree,standard,none,75,84,80,58,61,73,79.666667
12,female,10,group B,high school,standard,none,65,81,73,31,10,66,73.000000
645,female,15,group B,bachelor's degree,standard,completed,65,81,81,41,15,76,75.666667
31,female,45,group B,some college,standard,none,63,65,61,71,45,58,63.000000
856,male,92,group B,some college,free/reduced,none,75,68,65,77,92,35,69.333333
413,male,82,group B,some high school,standard,completed,63,67,67,95,82,36,65.666667
722,female,95,group B,some high school,free/reduced,completed,74,90,88,54,95,18,84.000000
318,male,8,group B,bachelor's degree,standard,none,63,71,69,92,8,93,67.666667
208,female,43,group B,some college,free/reduced,none,74,81,76,45,43,82,77.000000
897,female,21,group B,some high school,free/reduced,completed,63,78,79,35,21,40,73.333333
843,male,4,group B,some college,free/reduced,completed,74,77,76,1,4,5,75.666667
488,male,41,group B,some high school,standard,completed,64,53,57,16,41,32,58.000000
565,male,73,group B,associate's degree,standard,none,48,43,45,68,73,57,45.333333
765,female,41,group B,high school,standard,none,74,72,72,16,41,11,72.666667
94,female,25,group B,some college,standard,none,79,86,92,49,25,9,85.666667
882,female,94,group B,high school,free/reduced,none,64,73,71,41,94,18,69.333333
398,male,34,group B,some high school,standard,none,74,63,57,57,34,27,64.666667
443,female,23,group B,associate's degree,standard,none,73,83,76,63,23,82,77.333333
654,female,45,group B,some high school,standard,none,73,79,79,94,45,24,77.000000
45,male,80,group B,associate's degree,standard,none,65,54,57,17,80,38,58.666667
310,female,9,group B,associate's degree,standard,none,73,76,80,55,9,93,76.333333
248,female,96,group B,high school,standard,none,65,64,62,15,96,21,63.666667
406,male,70,group B,associate's degree,standard,completed,65,65,63,48,70,85,64.333333
96,male,84,group B,some high school,standard,completed,65,66,62,27,84,11,64.333333
480,male,38,group B,high school,standard,completed,73,71,68,69,38,50,70.666667
534,male,39,group B,high school,standard,completed,73,69,68,13,39,73,70.000000
279,male,65,group B,bachelor's degree,free/reduced,none,73,56,57,36,65,36,62.000000
642,female,30,group B,some high school,free/reduced,none,72,81,79,94,30,90,77.333333
21,female,30,group B,some college,free/reduced,completed,65,75,70,98,30,51,70.000000
198,female,59,group B,some college,free/reduced,none,45,53,55,42,59,30,51.000000
0,female,95,group B,bachelor's degree,standard,none,72,72,74,20,95,30,72.666667
126,male,2,group B,some high school,standard,none,72,68,67,84,2,65,69.000000
459,male,93,group B,high school,standard,completed,72,65,68,19,93,77,68.333333
152,female,78,group B,associate's degree,standard,completed,59,70,66,13,78,50,65.000000
168,female,4,group B,high school,standard,completed,68,83,78,39,4,79,76.333333
513,female,53,group B,some high school,standard,completed,54,61,62,6,53,6,59.000000
288,male,15,group B,bachelor's degree,free/reduced,none,88,75,76,92,15,44,79.666667
203,female,52,group B,associate's degree,standard,none,57,69,68,88,52,67,64.666667
494,female,40,group B,high school,standard,none,54,64,68,12,40,50,62.000000
858,male,59,group B,high school,standard,completed,52,49,46,6,59,43,49.000000
81,male,70,group B,high school,free/reduced,none,49,45,45,68,70,1,46.333333
770,male,25,group B,high school,standard,none,52,48,49,1,25,90,49.666667
484,female,17,group B,associate's degree,standard,none,49,52,54,94,17,18,51.666667
834,male,84,group B,some college,standard,none,58,50,45,27,84,61,51.000000
803,female,90,group B,some college,standard,none,82,85,87,40,90,30,84.666667
596,male,23,group B,high school,free/reduced,none,30,24,15,86,23,66,23.000000
872,male,89,group B,associate's degree,standard,completed,82,84,78,29,89,47,81.333333
6,female,32,group B,some college,standard,completed,88,95,92,94,32,68,91.666667
284,female,49,group B,some high school,standard,none,37,46,46,8,49,86,43.000000
505,female,50,group B,some high school,standard,none,82,82,80,77,50,68,81.333333
815,male,40,group B,some high school,standard,completed,94,86,87,98,40,97,89.000000
501,female,94,group B,associate's degree,standard,completed,94,87,92,23,94,18,91.000000
474,female,11,group B,associate's degree,standard,completed,90,90,91,48,11,17,90.333333
407,female,4,group B,associate's degree,standard,none,82,80,77,4,4,67,79.666667
160,male,41,group B,associate's degree,free/reduced,completed,82,78,74,53,41,54,78.000000
552,female,71,group B,associate's degree,standard,none,40,48,50,56,71,62,46.000000
136,male,33,group B,some high school,standard,completed,51,54,41,46,33,27,48.666667
785,female,83,group B,some high school,standard,completed,32,51,44,61,83,36,42.333333
701,female,23,group B,some high school,standard,none,57,67,72,23,23,15,65.333333
361,male,18,group B,some high school,standard,completed,85,84,78,38,18,54,82.333333
2,female,62,group B,master's degree,standard,none,90,95,93,15,62,98,92.666667
108,female,45,group B,associate's degree,free/reduced,none,52,76,70,36,45,80,66.000000
178,female,76,group B,master's degree,free/reduced,completed,52,70,62,82,76,25,61.333333
772,female,45,group B,some high school,free/reduced,completed,52,67,72,73,45,65,63.666667
224,female,35,group B,associate's degree,standard,completed,52,66,73,3,35,80,63.666667
507,male,58,group B,bachelor's degree,free/reduced,none,55,59,54,81,58,22,56.000000
350,female,17,group B,bachelor's degree,standard,none,52,65,69,47,17,8,62.000000
121,male,98,group B,associate's degree,standard,completed,91,89,92,91,98,75,90.666667
215,male,50,group B,some high school,standard,completed,84,83,75,51,50,45,80.666667
906,male,10,group B,high school,standard,none,57,48,51,40,10,88,52.000000
919,male,80,group B,some college,standard,completed,91,96,91,14,80,78,92.666667
333,male,58,group B,associate's degree,standard,none,90,78,81,72,58,49,83.000000
9,female,92,group B,high school,free/reduced,none,38,60,50,1,92,97,49.333333
7,male,94,group B,some college,free/reduced,none,40,43,39,98,94,22,40.666667
744,male,47,group B,some college,free/reduced,none,55,55,47,5,47,72,52.333333
39,male,90,group B,associate's degree,free/reduced,none,57,56,57,91,90,92,56.666667
948,male,40,group B,some high school,free/reduced,completed,49,50,52,29,40,69,50.333333
162,male,11,group B,master's degree,free/reduced,none,49,53,52,58,11,61,51.333333
923,female,16,group B,associate's degree,free/reduced,none,54,65,65,79,16,12,61.333333
42,female,17,group B,associate's degree,standard,none,53,58,65,42,17,26,58.666667
946,male,8,group B,high school,standard,none,82,82,80,53,8,36,81.333333
749,male,51,group B,some college,standard,completed,87,84,86,78,51,8,85.666667
838,male,13,group B,associate's degree,free/reduced,completed,58,57,53,30,13,26,56.000000
167,female,21,group B,master's degree,free/reduced,completed,58,76,78,99,21,35,70.666667

# 1 Create Index

In [90]:
import numpy as np
import random

In [92]:
# creating non repetitive values for the index
new_index = np.arange(0, 1000)

In [93]:
# shuffling the indexes
random.shuffle(new_index)

In [94]:
# create a new column with new index
df_exams['new_index'] = new_index

# 2 Set Index

In [96]:
# set new_index column as index
df_exams.set_index('new_index', inplace=True)

# 3 Sort Index

In [97]:
# sort dataframe by new index
df_exams.sort_index()

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,HR_score,logistics,average
new_index,,,,,,,,,,,,,
0,female,40,group C,high school,standard,completed,58,75,77,56,40,80,70.000000
1,male,26,group D,high school,standard,none,69,75,71,38,26,12,71.666667
2,male,89,group B,some college,free/reduced,none,60,60,60,88,89,36,60.000000
3,female,33,group C,some college,standard,completed,67,81,79,99,33,96,75.666667
4,female,46,group C,some college,standard,completed,70,72,76,19,46,16,72.666667
5,female,4,group B,associate's degree,standard,none,82,80,77,4,4,67,79.666667
6,female,56,group E,high school,free/reduced,none,41,45,40,90,56,69,42.000000
7,female,5,group D,some high school,standard,none,48,58,54,78,5,64,53.333333
8,male,15,group D,bachelor's degree,standard,completed,67,61,68,66,15,77,65.333333
9,male,66,group D,high school,standard,completed,55,41,48,99,66,49,48.000000
10,female,89,group D,master's degree,standard,none,55,64,70,1,89,35,63.000000
11,female,86,group D,some high school,standard,completed,66,78,78,13,86,23,74.000000
12,female,49,group B,some high school,standard,none,37,46,46,8,49,86,43.000000
13,male,50,group C,bachelor's degree,standard,none,86,83,86,93,50,63,85.000000
14,male,39,group B,high school,standard,completed,73,69,68,13,39,73,70.000000
15,female,6,group E,some college,standard,none,100,92,97,2,6,77,96.333333
16,female,58,group C,some high school,free/reduced,completed,71,84,87,17,58,67,80.666667
17,male,65,group B,bachelor's degree,free/reduced,none,73,56,57,36,65,36,62.000000
18,female,13,group E,some college,standard,none,68,70,66,20,13,83,68.000000
19,female,45,group C,some college,free/reduced,none,35,44,43,74,45,63,40.666667
20,female,50,group C,high school,free/reduced,none,33,41,43,18,50,62,39.000000
21,male,88,group A,some high school,free/reduced,none,55,46,43,96,88,35,48.000000
22,male,62,group A,some college,free/reduced,none,58,60,57,61,62,47,58.333333
23,female,27,group C,associate's degree,standard,completed,59,73,72,33,27,82,68.000000
24,female,10,group B,high school,standard,none,42,52,51,94,10,57,48.333333
25,female,95,group E,high school,standard,completed,74,79,80,84,95,80,77.666667
26,female,47,group E,bachelor's degree,standard,none,65,73,75,56,47,95,71.000000
27,male,33,group B,some high school,standard,completed,51,54,41,46,33,27,48.666667
28,male,11,group B,master's degree,free/reduced,none,49,53,52,58,11,61,51.333333
29,male,89,group B,associate's degree,standard,completed,82,84,78,29,89,47,81.333333
30,female,90,group C,bachelor's degree,free/reduced,none,50,60,59,37,90,37,56.333333
31,female,81,group C,some college,standard,none,59,71,70,65,81,9,66.666667
32,female,99,group D,some college,standard,none,62,70,72,61,99,75,68.000000
33,female,10,group D,some college,standard,none,79,86,81,7,10,60,82.000000
34,female,91,group D,some college,standard,none,77,68,77,4,91,24,74.000000
35,female,95,group B,some high school,free/reduced,completed,74,90,88,54,95,18,84.000000
36,female,11,group D,associate's degree,free/reduced,none,52,59,56,55,11,34,55.666667
37,female,58,group C,associate's degree,standard,completed,68,86,84,96,58,8,79.333333
38,male,46,group C,high school,standard,none,52,53,49,20,46,97,51.333333
39,female,70,group D,some high school,standard,completed,80,92,88,50,70,80,86.666667
40,male,4,group C,some high school,free/reduced,completed,53,37,40,97,4,40,43.333333
41,female,69,group C,some college,standard,completed,64,82,77,38,69,50,74.333333
42,female,94,group B,high school,free/reduced,completed,76,85,82,21,94,87,81.000000
43,female,70,group B,some high school,standard,none,62,64,66,2,70,61,64.000000
44,female,84,group B,master's degree,standard,none,77,90,84,29,84,20,83.666667
45,male,49,group E,associate's degree,standard,none,72,57,62,8,49,66,63.666667
46,female,62,group A,high school,standard,none,61,68,63,12,62,73,64.000000
47,male,67,group D,bachelor's degree,free/reduced,none,63,66,67,84,67,12,65.333333
48,male,19,group D,some high school,standard,none,84,84,80,4,19,51,82.666667
49,male,21,group D,associate's degree,free/reduced,none,52,57,50,33,21,4,53.000000
50,male,69,group E,high school,standard,none,94,73,71,24,69,19,79.333333
51,male,46,group A,some high school,standard,none,64,50,43,76,46,92,52.333333
52,female,32,group B,some college,standard,completed,88,95,92,94,32,68,91.666667
53,female,33,group E,some high school,free/reduced,none,72,79,77,50,33,72,76.000000
54,female,90,group C,some college,standard,none,84,87,91,80,90,15,87.333333
55,female,60,group E,some college,standard,completed,66,74,73,97,60,17,71.000000
56,male,29,group C,high school,standard,completed,53,52,49,49,29,95,51.333333
57,male,82,group D,high school,free/reduced,none,60,57,51,70,82,14,56.000000
58,female,4,group B,high school,standard,completed,68,83,78,39,4,79,76.333333
59,male,96,group D,associate's degree,standard,none,80,68,72,32,96,22,73.333333
60,male,84,group A,some college,standard,completed,100,96,86,16,84,44,94.000000
61,female,40,group C,bachelor's degree,free/reduced,completed,43,51,54,6,40,37,49.333333
62,male,54,group E,some high school,standard,none,94,88,78,3,54,30,86.666667
63,male,94,group E,associate's degree,standard,none,87,74,76,80,94,80,79.000000
64,female,53,group A,associate's degree,standard,completed,55,65,62,87,53,30,60.666667
65,female,97,group D,master's degree,standard,none,74,79,82,27,97,18,78.333333
66,male,81,group E,master's degree,standard,none,90,85,84,96,81,17,86.333333
67,female,41,group C,bachelor's degree,standard,completed,52,61,66,3,41,35,59.666667
68,female,83,group D,some college,standard,completed,68,78,77,40,83,13,74.333333
69,male,19,group A,some high school,standard,completed,66,68,64,72,19,22,66.000000
70,female,29,group E,some college,standard,none,76,78,80,70,29,65,78.000000
71,male,40,group A,bachelor's degree,standard,completed,87,84,87,6,40,76,86.000000
72,female,3,group D,high school,standard,none,51,66,62,70,3,43,59.666667
73,male,62,group E,some high school,standard,completed,87,84,76,78,62,31,82.333333
74,male,52,group C,high school,standard,completed,72,67,64,52,52,71,67.666667
75,female,68,group D,associate's degree,standard,none,65,69,70,47,68,86,68.000000
76,female,25,group D,master's degree,standard,none,62,70,75,31,25,73,69.000000
77,male,14,group C,high school,standard,completed,58,52,54,35,14,3,54.666667
78,male,78,group C,some college,standard,completed,98,86,90,34,78,99,91.333333
79,female,14,group D,associate's degree,free/reduced,completed,42,61,58,84,14,90,53.666667
80,male,7,group D,some college,free/reduced,none,49,57,46,89,7,91,50.666667
81,female,13,group D,some high school,free/reduced,completed,69,86,81,83,13,85,78.666667
82,male,81,group C,some college,free/reduced,none,35,28,27,12,81,14,30.000000
83,male,21,group D,some high school,standard,completed,74,71,78,35,21,86,74.333333
84,female,59,group D,master's degree,standard,none,64,63,66,81,59,16,64.333333
85,female,27,group D,some college,free/reduced,completed,67,86,83,58,27,35,78.666667
86,male,3,group E,associate's degree,free/reduced,completed,78,74,72,34,3,86,74.666667
87,female,63,group C,some college,free/reduced,completed,67,75,70,20,63,55,70.666667
88,male,46,group E,associate's degree,standard,completed,71,74,68,64,46,60,71.000000
89,female,15,group D,bachelor's degree,free/reduced,none,78,90,93,12,15,8,87.000000
90,female,12,group C,bachelor's degree,standard,none,86,92,87,44,12,42,88.333333
91,male,40,group D,some high school,standard,none,62,67,61,32,40,99,63.333333
92,female,66,group C,associate's degree,standard,completed,68,67,73,91,66,96,69.333333
93,female,71,group E,associate's degree,free/reduced,completed,83,86,88,24,71,12,85.666667
94,male,27,group B,associate's degree,standard,none,61,42,41,50,27,37,48.000000
95,male,60,group D,some college,standard,completed,71,61,69,58,60,10,67.000000
96,female,84,group C,bachelor's degree,free/reduced,completed,47,62,66,72,84,94,58.333333
97,male,64,group D,some college,standard,none,76,64,66,61,64,41,68.666667
98,male,39,group C,master's degree,free/reduced,completed,79,77,75,42,39,2,77.000000
99,female,23,group C,master's degree,standard,completed,69,84,85,99,23,98,79.333333
100,male,66,group E,some college,standard,none,53,55,48,98,66,86,52.000000
101,male,58,group D,some high school,free/reduced,none,45,37,37,93,58,55,39.666667
102,female,63,group B,some high school,standard,completed,65,82,78,16,63,80,75.000000
103,female,75,group D,some college,standard,none,65,70,71,81,75,48,68.666667
104,male,51,group C,associate's degree,standard,none,62,65,58,99,51,21,61.666667
105,male,80,group B,some college,standard,completed,91,96,91,14,80,78,92.666667
106,male,39,group C,associate's degree,standard,none,49,51,43,68,39,45,47.666667
107,female,85,group C,bachelor's degree,standard,completed,96,100,100,72,85,82,98.666667
108,female,18,group E,bachelor's degree,standard,completed,71,70,70,49,18,15,70.333333
109,female,11,group B,bachelor's degree,free/reduced,none,77,85,87,39,11,22,83.000000
110,female,48,group D,some college,standard,completed,82,97,96,29,48,60,91.666667
111,female,87,group C,associate's degree,standard,completed,96,96,99,55,87,95,97.000000
112,female,86,group B,associate's degree,standard,none,71,83,78,8,86,45,77.333333
113,male,10,group B,high school,standard,none,57,48,51,40,10,88,52.000000
114,female,47,group C,associate's degree,standard,none,66,77,73,28,47,61,72.000000
115,male,31,group C,some college,standard,none,66,59,52,41,31,33,59.000000
116,female,62,group C,some high school,standard,none,77,91,88,61,62,75,85.333333
117,female,9,group D,some college,free/reduced,none,69,65,74,71,9,98,69.333333
118,male,60,group C,bachelor's degree,standard,completed,94,90,91,30,60,68,91.666667
119,female,29,group A,high school,free/reduced,completed,77,88,85,88,29,33,83.333333
120,female,16,group C,high school,free/reduced,none,35,53,46,25,16,13,44.666667
121,male,4,group B,some college,free/reduced,completed,74,77,76,1,4,5,75.666667
122,female,15,group D,high school,free/reduced,completed,65,61,71,91,15,41,65.666667
123,female,76,group D,high school,free/reduced,none,49,57,52,85,76,96,52.666667
124,male,99,group D,some high school,standard,none,60,59,54,69,99,55,57.666667
125,female,73,group C,high school,free/reduced,none,36,53,43,30,73,69,44.000000
126,male,71,group D,some high school,standard,completed,88,74,75,78,71,32,79.000000
127,male,39,group C,bachelor's degree,free/reduced,none,53,58,55,37,39,21,55.333333
128,female,20,group C,high school,free/reduced,none,35,61,54,23,20,27,50.000000
129,male,78,group A,associate's degree,standard,none,54,53,47,30,78,62,51.333333
130,female,27,group D,master's degree,standard,none,92,100,100,88,27,43,97.333333
131,female,87,group C,some college,free/reduced,none,62,67,62,46,87,18,63.666667
132,male,74,group A,some high school,standard,completed,62,67,69,77,74,57,66.000000
133,female,17,group D,master's degree,free/reduced,completed,61,71,78,57,17,45,70.000000
134,male,13,group C,bachelor's degree,standard,completed,63,64,66,32,13,53,64.333333
135,female,68,group E,bachelor's degree,standard,completed,99,100,100,7,68,18,99.666667
136,male,43,group C,associate's degree,standard,none,92,79,84,16,43,90,85.000000
137,female,57,group E,bachelor's degree,standard,completed,79,81,82,56,57,46,80.666667
138,female,89,group C,some high school,standard,completed,67,74,77,59,89,67,72.666667
139,male,74,group C,high school,free/reduced,none,61,60,55,27,74,92,58.666667
140,female,33,group D,associate's degree,standard,none,71,71,74,64,33,5,72.000000
141,male,10,group A,some college,free/reduced,completed,50,47,54,64,10,61,50.333333
142,male,99,group A,high school,free/reduced,none,48,45,41,30,99,40,44.666667
143,male,88,group D,some college,standard,completed,58,59,58,87,88,67,58.333333
144,male,37,group B,bachelor's degree,free/reduced,none,62,63,56,48,37,30,60.333333
145,female,24,group C,master's degree,free/reduced,completed,65,81,81,43,24,55,75.666667
146,female,52,group E,master's degree,standard,none,81,92,91,53,52,63,88.000000
147,female,17,group B,bachelor's degree,standard,none,52,65,69,47,17,8,62.000000
148,male,17,group D,associate's degree,standard,none,61,55,52,39,17,79,56.000000
149,female,76,group C,bachelor's degree,standard,none,77,88,87,26,76,4,84.000000
150,female,17,group C,bachelor's degree,free/reduced,completed,66,83,83,22,17,28,77.333333
151,female,17,group B,associate's degree,standard,none,53,58,65,42,17,26,58.666667
152,female,23,group C,some college,standard,none,53,62,56,92,23,36,57.000000
153,male,77,group C,associate's degree,free/reduced,none,49,51,51,23,77,74,50.333333
154,female,24,group B,some high school,standard,completed,60,70,70,35,24,15,66.666667
155,female,67,group D,some high school,standard,none,68,71,75,14,67,34,71.333333
156,male,82,group C,high school,standard,completed,75,69,68,3,82,41,70.666667
157,male,35,group C,associate's degree,free/reduced,none,68,65,61,55,35,20,64.666667
158,female,57,group C,associate's degree,standard,completed,75,82,90,75,57,28,82.333333
159,male,8,group B,bachelor's degree,standard,none,63,71,69,92,8,93,67.666667
160,male,60,group E,associate's degree,free/reduced,completed,77,69,68,72,60,99,71.333333
161,female,36,group E,high school,standard,completed,59,63,75,67,36,67,65.666667
162,male,74,group A,associate's degree,standard,none,63,61,61,37,74,85,61.666667
163,male,93,group B,high school,standard,none,70,65,60,51,93,94,65.000000
164,male,22,group C,bachelor's degree,standard,completed,96,90,92,1,22,4,92.666667
165,male,51,group B,some college,standard,completed,87,84,86,78,51,8,85.666667
166,male,62,group C,some college,standard,none,76,78,75,40,62,94,76.333333
167,female,27,group D,master's degree,standard,none,53,61,68,9,27,59,60.666667
168,male,96,group D,some college,free/reduced,none,69,66,60,76,96,12,65.000000
169,female,22,group D,associate's degree,standard,none,85,91,89,85,22,95,88.333333
170,female,8,group C,associate's degree,standard,none,65,76,76,92,8,5,72.333333
171,male,36,group D,some college,standard,none,60,63,59,58,36,60,60.666667
172,male,73,group C,some college,standard,none,59,41,42,45,73,45,47.333333
173,male,9,group D,high school,free/reduced,completed,78,77,80,61,9,85,78.333333
174,male,9,group C,some high school,standard,completed,76,80,73,7,9,87,76.333333
175,female,96,group D,associate's degree,standard,completed,57,78,79,10,96,70,71.333333
176,male,65,group C,high school,standard,none,62,67,58,52,65,89,62.333333
177,male,20,group E,high school,free/reduced,none,55,56,51,33,20,21,54.000000
178,female,86,group D,some high school,free/reduced,none,48,54,53,8,86,16,51.666667
179,female,79,group C,high school,standard,none,76,76,74,21,79,19,75.333333
180,female,7,group C,some high school,free/reduced,completed,65,76,75,21,7,96,72.000000
181,female,59,group C,some college,standard,none,83,83,90,42,59,27,85.333333
182,male,85,group D,some high school,standard,completed,78,81,86,28,85,22,81.666667
183,female,71,group D,master's degree,standard,none,87,100,100,12,71,50,95.666667
184,male,58,group E,some college,free/reduced,none,93,90,83,61,58,63,88.666667
185,male,47,group E,high school,free/reduced,completed,57,56,54,62,47,8,55.666667
186,male,80,group B,associate's degree,standard,none,65,54,57,17,80,38,58.666667
187,female,92,group C,associate's degree,standard,none,69,80,71,73,92,81,73.333333
188,female,7,group D,some high school,standard,none,59,58,59,43,7,45,58.666667
189,female,63,group D,some college,standard,none,74,89,84,28,63,4,82.333333
190,male,50,group D,some high school,standard,none,86,80,75,38,50,29,80.333333
191,female,29,group E,master's degree,free/reduced,none,45,56,54,39,29,46,51.666667
192,female,81,group E,associate's degree,standard,completed,82,85,86,35,81,40,84.333333
193,female,61,group D,bachelor's degree,standard,none,65,67,62,30,61,45,64.666667
194,male,30,group A,associate's degree,free/reduced,completed,40,55,53,74,30,26,49.333333
195,male,48,group D,high school,standard,none,88,78,75,83,48,58,80.333333
196,female,91,group C,bachelor's degree,standard,none,81,88,90,21,91,41,86.333333
197,female,36,group C,high school,standard,none,29,29,30,14,36,47,29.333333
198,male,82,group C,some high school,free/reduced,completed,59,69,65,38,82,88,64.333333
199,male,51,group C,some high school,standard,none,57,61,54,60,51,5,57.333333
200,male,97,group D,associate's degree,free/reduced,none,66,62,64,19,97,46,64.000000
201,female,57,group B,some high school,standard,none,67,89,82,62,57,47,79.333333
202,male,15,group D,master's degree,standard,none,82,82,74,73,15,52,79.333333
203,female,3,group C,associate's degree,standard,completed,74,75,83,19,3,42,77.333333
204,male,13,group E,associate's degree,free/reduced,completed,46,43,44,11,13,84,44.333333
205,male,12,group C,master's degree,standard,none,71,67,67,30,12,99,68.333333
206,male,4,group B,high school,standard,none,62,55,54,45,4,69,57.000000
207,female,66,group D,master's degree,free/reduced,completed,47,58,67,32,66,16,57.333333
208,male,48,group D,some college,standard,completed,100,97,99,89,48,75,98.666667
209,male,32,group D,some high school,free/reduced,completed,55,59,59,50,32,7,57.666667
210,male,58,group B,associate's degree,standard,completed,81,82,82,62,58,3,81.666667
211,female,33,group C,some high school,standard,none,69,75,78,21,33,14,74.000000
212,female,7,group D,some college,standard,none,80,90,89,7,7,86,86.333333
213,female,18,group D,high school,standard,none,69,72,77,38,18,84,72.666667
214,female,30,group B,some high school,free/reduced,none,72,81,79,94,30,90,77.333333
215,female,72,group C,high school,standard,none,66,71,76,85,72,25,71.000000
216,female,60,group C,some high school,standard,none,74,75,82,69,60,25,77.000000
217,female,95,group C,some high school,free/reduced,none,55,65,62,15,95,56,60.666667
218,male,9,group C,associate's degree,standard,none,58,54,52,8,9,97,54.666667
219,male,76,group E,some college,standard,none,69,60,54,68,76,36,61.000000
220,male,77,group E,associate's degree,standard,none,89,76,74,86,77,6,79.666667
221,male,1,group A,some high school,free/reduced,completed,61,62,61,50,1,36,61.333333
222,female,77,group C,associate's degree,standard,completed,65,84,84,68,77,21,77.666667
223,female,89,group C,some high school,standard,completed,70,82,76,48,89,95,76.000000
224,female,24,group C,high school,free/reduced,completed,50,66,64,27,24,74,60.000000
225,female,90,group A,some high school,standard,none,48,66,65,63,90,42,59.666667
226,male,62,group C,master's degree,free/reduced,completed,62,68,75,48,62,57,68.333333
227,male,69,group D,high school,standard,none,66,69,63,48,69,6,66.000000
228,female,16,group A,associate's degree,free/reduced,none,37,57,56,36,16,83,50.000000
229,male,17,group B,some college,free/reduced,none,54,54,45,3,17,42,51.000000
230,male,71,group D,high school,standard,none,41,52,51,72,71,69,48.000000
231,female,80,group E,associate's degree,standard,none,59,62,69,84,80,83,63.333333
232,female,11,group C,some college,standard,none,54,48,52,48,11,42,51.333333
233,female,24,group C,some college,free/reduced,none,46,64,66,72,24,46,58.666667
234,female,49,group B,high school,standard,none,58,68,61,91,49,7,62.333333
235,female,91,group C,bachelor's degree,standard,none,65,72,74,64,91,57,70.333333
236,male,52,group C,master's degree,free/reduced,completed,72,66,72,58,52,83,70.000000
237,female,46,group C,master's degree,standard,none,73,78,74,33,46,71,75.000000
238,female,55,group A,some high school,free/reduced,none,38,43,43,84,55,62,41.333333
239,female,31,group E,associate's degree,standard,none,87,94,95,13,31,48,92.000000
240,female,35,group C,some high school,standard,none,49,63,56,37,35,97,56.000000
241,female,63,group D,associate's degree,free/reduced,completed,75,90,88,78,63,79,84.333333
242,male,1,group B,bachelor's degree,standard,none,59,54,51,88,1,70,54.666667

In [99]:
# sort dataframe descending by new index
df_exams.sort_index(ascending=False, inplace=True)